/BasebandSPI/BasebandSPIDebug.cpp File Reference
BasebandSPIDebug.cpp File Reference
#include <string.h>
#include <IOKit/IOLib.h>
#include <sys/param.h>
#include "BasebandSPILogger.h"
#include "BasebandSPIDebug.h"
Functions
void _BasebandSPITriggerAssertion (unsigned long left, unsigned long right, const char *leftStr, const char *operatorStr, const char *rightStr, const char *file, unsigned line)
void hexdump (const void *buffer, int length)
unsigned SPIsnprintf (char *p, unsigned capacity, const char *fmt,...)
Variables
static const int kBytesPerLine = 16
static const char * kHexDigits = "0123456789ABCDEF"
Function Documentation
void _BasebandSPITriggerAssertion (unsigned long left, unsigned long right, const char * leftStr, const char * operatorStr, const char * rightStr, const char * file, unsigned line)
Definition at line 69 of file BasebandSPIDebug.cpp.
References BasebandSPILogger::report().
 {
         char buff[256];
         BasebandSPILogger::report();
 #if !SPI_ASSERT_LINE_NUMBERS
         unsigned line = 0;
         const char * file = "";
 #endif
         snprintf( buff, sizeof( buff ), "BasebandSPI Assertion failure: %s %s %s. Left operand %p, Right operand %p (%s:%d)\n",
                 leftStr, operatorStr, rightStr, left, right, file, line );
         IOLog( buff );
         PE_enter_debugger( buff );
 }
void hexdump (const void * buffer, int length)
Definition at line 33 of file BasebandSPIDebug.cpp.
References kBytesPerLine, and kHexDigits.
 {
         int i, thisLine, offset, byteOffset;
         unsigned char c;
         char line[80] = "";
         for (i = 0; i < length; i += kBytesPerLine) {
                 offset = 0;
                 thisLine = length - i;
                 if (thisLine > kBytesPerLine) thisLine = kBytesPerLine;
                 for (byteOffset = 0; byteOffset < thisLine; byteOffset++) {
                         c = ((const unsigned char *)buffer)[i + byteOffset];
                         line[offset++] = kHexDigits[c >> 4];
                         line[offset++] = kHexDigits[c & 0xf];
                         line[offset++] = ' ';
                 }
                 memset(line + offset, ' ', (kBytesPerLine + 1 - byteOffset) * 3);
                 offset += (kBytesPerLine + 1 - byteOffset) * 3;
                 for (byteOffset = 0; byteOffset < thisLine; byteOffset++) {
                         c = ((const unsigned char *)buffer)[i + byteOffset];
                         if (c >= 0x20 && c <= 0x7e) line[offset++] = c;
                         else line[offset++] = '.';
                 }
                 line[offset++] = '\r';
                 line[offset++] = '\n';
                 line[offset++] = '\0';
                 IOLog("%s",line);
         }
 }
unsigned SPIsnprintf (char * p, unsigned capacity, const char * fmt, ...)
Definition at line 92 of file BasebandSPIDebug.cpp.
Referenced by AppleS5L8920XBasebandSPIControllerSnapshot::copyAsString(), AppleS5L8900XBasebandSPIControllerSnapshot::copyAsString(), BasebandSPIIFXProtocolSnapshot::copyAsString(), dumpBinary(), BasebandSPILogger::popLogEntryAsStringInternal(), and BasebandSPIController::reportError().
 {
         va_list al;
         va_start( al, fmt );
         unsigned ret = vsnprintf( p, capacity, fmt, al );
         va_end( al );
         return MIN( ret, capacity );
 }
Variable Documentation
const int kBytesPerLine = 16 static
Definition at line 31 of file BasebandSPIDebug.cpp.
Referenced by dumpBinary(), and hexdump().
const char* kHexDigits = "0123456789ABCDEF" static
Definition at line 30 of file BasebandSPIDebug.cpp.
Referenced by dumpBinary(), and hexdump().