/BasebandSPI/BasebandSPILogger.cpp File Reference
BasebandSPILogger.cpp File Reference
#include "BasebandSPILogger.h"
#include <sys/param.h>
#include <pexpert/pexpert.h>
#include <mach/mach_time.h>
#include <IOKit/IOLib.h>
#include <IOKit/IOMemoryDescriptor.h>
#include "BasebandSPIConfig.h"
#include "BasebandSPIIFXProtocol.h"
#include "BasebandSPICommand.h"
Functions
static unsigned dumpBinary (const char *buffer, int length, char *dest, unsigned capacity)
Function Documentation
static unsigned dumpBinary (const char * buffer, int length, char * dest, unsigned capacity) static
Definition at line 17 of file BasebandSPILogger.cpp.
References kBytesPerLine, kHexDigits, and SPIsnprintf().
Referenced by BasebandSPILogger::popLogEntryAsStringInternal(), and BasebandSPILogger::reportInternal().
 {
         static const unsigned kBytesPerLine = 16;
         static const char kHexDigits[] = "0123456789ABCDEF";
         if (length <= 0)
         {
                 dest[0] = 0;
                 return 0;
         }
         unsigned written = 0;
         for (int lineStart = 0; lineStart < length; lineStart += kBytesPerLine)
         {
                 int thisLine = length - lineStart;
                 if (thisLine > kBytesPerLine)
                         thisLine = kBytesPerLine;
                 char line[80] = ""; // 3 * 16 + 1 + 16 + 1 = 66
                 int offset = 0;
                 int byteOffset;
                 for (byteOffset = 0; byteOffset < thisLine; byteOffset++)
                 {
                         unsigned char c = ((const unsigned char*) buffer)[lineStart + byteOffset];
                         line[offset++] = kHexDigits[c >> 4];
                         line[offset++] = kHexDigits[c & 0xf];
                         line[offset++] = ' ';
                 }
                 // Pad with space
                 memset(line + offset, ' ', (kBytesPerLine + 1 - byteOffset) * 3);
                 offset += (kBytesPerLine + 1 - byteOffset) * 3;
                 for (byteOffset = 0; byteOffset < thisLine; byteOffset++)
                 {
                         char c = ((const unsigned char*) buffer)[lineStart + byteOffset];
                         if (c >= 0x20 && c <= 0x7e)
                                 line[offset++] = c;             // Printable
                         else
                                 line[offset++] = '.';   // Non-printable
                 }
                 line[offset++] = '\r';
                 line[offset++] = '\n';
                 line[offset++] = '\0';
                 written += SPIsnprintf( dest + written, capacity - written, "\t%04x  %s", lineStart, line);
         }
         return written;
 }