AppleS5L8900XBasebandSPIController Class Reference
AppleS5L8900XBasebandSPIController Class Reference
#include <AppleS5L8900XBasebandSPIController.h>
Inherits AppleS5LFamilyBasebandSPIController.
Public Member Functions
virtual bool start (IOService *provider)
Public Member Functions inherited from AppleS5LFamilyBasebandSPIController
virtual bool init (OSDictionary *dict)
virtual void stop (IOService *provider)
Public Member Functions inherited from BasebandSPIController
IOReturn activate (BasebandSPIDevice *device, BasebandSPIProtocol *protocol)
void beginBlockInterrupt (void)
Disallow SPI-specific interrupts.
IOReturn cancelAll (void)
bool canStartTransfer (void) const
IOReturn configure (IODMACommand *receiveCommand, IODMACommand *transmitCommand, IOByteCount size)
IOReturn deactivate (void)
bool endBlockInterrupt (void)
IOReturn enterLowPower (void)
IOReturn exitLowPower (BasebandSPIDevice *device, BasebandSPIProtocol *protocol)
IOReturn getSnapshot (BasebandSPIControllerSnapshot **snapshot)
virtual IOWorkLoop * getWorkLoop (void) const
bool intendToInterrupt (void)
bool isEnteringLowPower (void) const
virtual IOService * probe (IOService *provider, SInt32 *score)
bool reportError (BasebandSPIReturn err, const char *details)
IOReturn startTransfer (void)
IOReturn unconfigure (void)
Protected Member Functions
virtual IOReturn configureHardware (UInt32 dmaFlags, IOByteCount size)
const char * getDebugName (void) const
virtual IOReturn loadConfiguration (void)
Parses through the configuration and extract necessary information.
virtual IOReturn preflightSetupHardware (void)
Do a preflight setup of the hardware.
virtual IOReturn startHardware (void)
Start the hardware for the transfer.
virtual IOReturn takeSnapshot (const char *comment, BasebandSPIControllerSnapshot::PinState resetDetectState, BasebandSPIControllerSnapshot **snapshot)
virtual IOReturn unconfigureHardware (void)
Power down the hardware.
virtual bool validateDeviceTypeAndChip (const char *deviceType, UInt32 chipRevision) const
Protected Member Functions inherited from AppleS5LFamilyBasebandSPIController
bool clockEnabled (void) const
void enableClock (bool enable)
const char * getDebugName (void) const
UInt32 readReg32 (UInt32 offset)
void writeReg32 (UInt32 offset, UInt32 data)
Protected Member Functions inherited from BasebandSPIController
void dumpRegisters (int level=DEBUG_SPEW)
const char * eventSourceAsString (IODMAEventSource *es) const
const char * getDebugName (void) const
IOReturn getNewSnapshot (const char *reason)
UInt32 getOverrideClockPeriod (void) const
Private Member Functions
virtual void dumpRegistersInternal (void)
OSDeclareDefaultStructors (AppleS5L8900XBasebandSPIController)
Private Attributes
UInt32 _spiClkConReg
UInt32 _spiClockPeriod
UInt32 _spiConReg
UInt32 _spiIDDReg
UInt32 _spiPreReg
UInt32 _spiWordSize
UInt32 _spiWordTime
Additional Inherited Members
Public Types inherited from BasebandSPIController
enum DMAFlags { kNone = 0, kRxDMA = 1UL << 0, kTxDMA = 1UL << 1 }
Static Protected Member Functions inherited from BasebandSPIController
static const char * stateAsString (State state)
Protected Attributes inherited from AppleS5LFamilyBasebandSPIController
UInt64 fNCLKFrequency
UInt64 fPCLKFrequency
Protected Attributes inherited from BasebandSPIController
IOCommandGate * fCommandGate
BasebandSPIConfig fConfiguration
IODMACommand * fCurrentReceiveCommand
IODMACommand * fCurrentSendCommand
BasebandSPIDevice * fDevice
BasebandSPIDiagnostics * fDiags
bool fEnteringLowPower
UInt32 fHardwareStateFlags
bool fInLowPower
volatile InterruptGuardState fInterruptGuard
UInt32 fPendingDMAs
IODMACommand * fPendingReceiveCommand
IODMACommand * fPendingSendCommand
BasebandSPIProtocol * fProtocol
AppleARMIODevice * fProvider
IODMAEventSource * fRxDMAES
BasebandSPIControllerSnapshot * fSavedSnapshot
State fState
State fStateBeforeLowPower
IOTimerEventSource * fTransferCompleteTimeout
IODMAEventSource * fTxDMAES
volatile UInt32 fVolatileHardwareStateFlags
IOWorkLoop * fWorkLoop
Detailed Description
Definition at line 71 of file AppleS5L8900XBasebandSPIController.h.
Member Function Documentation
IOReturn AppleS5L8900XBasebandSPIController::configureHardware (UInt32 dmaFlags, IOByteCount size) protected virtual
Power up the hardware
Parameters
dmaFlags Flags saying which DMAs we want
size The transfer size
Implements BasebandSPIController.
Definition at line 185 of file AppleS5L8900XBasebandSPIController.cpp.
References DEBUG_SPEW, kS5L8900XSPCLKCON, kS5L8900XSPCLKCONFlushRx, kS5L8900XSPCLKCONFlushTx, kS5L8900XSPCLKCONOn, kS5L8900XSPCNT, kS5L8900XSPCON, kS5L8900XSPCONAGDMode, kS5L8900XSPCONFullDuplex, kS5L8900XSPCONSPIModeDMA, kS5L8900XSPIDD, kS5L8900XSPPIN, kS5L8900XSPPRE, kS5L8900XSPSTA, kS5L8900XSPSTAIntAll, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         SPI_LOG( DEBUG_SPEW, "Flags = %p, size = %u\n", (void *)dmaFlags, (unsigned)size );
         enableClock(true);
         // Reset & Clear Interrupts
         _spiClkConReg = kS5L8900XSPCLKCONOn;
         // disable the clock and flush
         writeReg32(kS5L8900XSPCLKCON, kS5L8900XSPCLKCONFlushTx | kS5L8900XSPCLKCONFlushRx);
         // clear the pin control register
         writeReg32(kS5L8900XSPPIN, 0);
         // set the inter-word data delay
         writeReg32(kS5L8900XSPIDD, _spiIDDReg);
         // clear the count
         writeReg32(kS5L8900XSPCNT, 0);
         // set the baud rate prescaler
         writeReg32(kS5L8900XSPPRE, _spiPreReg);
         // clear all interrupts
         writeReg32(kS5L8900XSPSTA, kS5L8900XSPSTAIntAll);
         // set SPCON
         writeReg32(kS5L8900XSPCON, _spiConReg );
         size = size >> (_spiWordSize >> 1);
         // write the count register
         writeReg32(kS5L8900XSPCNT, size);
         UInt32 spiConReg = _spiConReg | kS5L8900XSPCONSPIModeDMA;
         if ( dmaFlags & kTxDMA )
         {
                 spiConReg |= kS5L8900XSPCONFullDuplex;
         }
         else
         {
                 spiConReg |= kS5L8900XSPCONAGDMode;
         }
         // enable DMA and set garbage tx frame mode (if needed)
         writeReg32(kS5L8900XSPCON, spiConReg );
         return kIOReturnSuccess;
 }
void AppleS5L8900XBasebandSPIController::dumpRegistersInternal (void) private virtual
Implements BasebandSPIController.
Definition at line 249 of file AppleS5L8900XBasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_SPEW, kS5L8900XSPCLKCON, kS5L8900XSPCNT, kS5L8900XSPCON, kS5L8900XSPIDD, kS5L8900XSPPRE, kS5L8900XSPSTA, SPI_LOG, and SPI_LOG_PLAIN.
Referenced by getDebugName().
 {
         if ( !clockEnabled() )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Clock is off\n" );
                 return;
         }
         SPI_LOG_PLAIN( DEBUG_SPEW, "Register dump\n" );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\tSPCLKCON: %#8lx\n", readReg32(kS5L8900XSPCLKCON) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPCON: %#8lx\n", readReg32(kS5L8900XSPCON) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPSTA: %#8lx\n", readReg32(kS5L8900XSPSTA) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPIDD: %#8lx\n", readReg32(kS5L8900XSPIDD) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPPRE: %#8lx\n", readReg32(kS5L8900XSPPRE) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPCNT: %#8lx\n", readReg32(kS5L8900XSPCNT) );
 }
const char* AppleS5L8900XBasebandSPIController::getDebugName (void) const inline protected
Definition at line 92 of file AppleS5L8900XBasebandSPIController.h.
References dumpRegistersInternal(), and takeSnapshot().
         {
                 return "AppleS5L8900XBasebandSPIController";
         }
IOReturn AppleS5L8900XBasebandSPIController::loadConfiguration (void) protected virtual
Parses through the configuration and extract necessary information.
Reimplemented from AppleS5LFamilyBasebandSPIController.
Definition at line 113 of file AppleS5L8900XBasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_SPEW, kS5L8900XSPCONBitOrderLSB, kS5L8900XSPCONClkActiveLow, kS5L8900XSPCONClkEnable, kS5L8900XSPCONClkMissingLast, kS5L8900XSPCONClkSelNClk, kS5L8900XSPCONDataSwap, kS5L8900XSPCONDMAReqOne, kS5L8900XSPCONMasterMode, kS5L8900XSPCONWordSizeShift, SPI_ASSERT, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         IOReturn ret;
         ret = super::loadConfiguration();
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         _spiConReg = kS5L8900XSPCONClkSelNClk | kS5L8900XSPCONClkEnable | kS5L8900XSPCONMasterMode;
         if (fConfiguration.spiClockPolarity) _spiConReg |= kS5L8900XSPCONClkActiveLow;
         if (fConfiguration.spiClockPhase) _spiConReg |= kS5L8900XSPCONClkMissingLast;
         if (!fConfiguration.spiBitFirst) _spiConReg |= kS5L8900XSPCONBitOrderLSB;
         UInt32 sclkPeriod = fConfiguration.spiClockPeriod;
         {
                 UInt32 period = getOverrideClockPeriod();
                 if ( period != 0 )
                 {
                         sclkPeriod = period;
                         SPI_LOG( DEBUG_CRITICAL, "Overriding SCLK to %uns\n", (unsigned)period );
                 }
                 else
                 {
                         SPI_LOG( DEBUG_SPEW, "SCLK period %uns\n", (unsigned)sclkPeriod );
                 }
         }
         SPI_LOG( DEBUG_SPEW, "polarity %p, phase %p\n",
                 (void *)fConfiguration.spiClockPolarity, (void *)fConfiguration.spiClockPhase );
         switch ( fConfiguration.spiWordSize )
         {
         case 8:
                 _spiWordSize = 0;
                 break;
         case 16:
                 _spiWordSize = 1;
                 break;
         case 32:
                 _spiWordSize = 2;
                 break;
         default:
                 SPI_ASSERT( fConfiguration.spiWordSize, ==, 8 );
         }
         _spiConReg |= _spiWordSize << kS5L8900XSPCONWordSizeShift;
         _spiWordSize = 1 << _spiWordSize;
 #if SPI_WORD32
         // Request in the unit of every one buffer. The documentation
         // states one byte however it is wrong.
         // TODO Is it worse to poll the last 4 buffers
         _spiConReg |= kS5L8900XSPCONDMAReqOne | kS5L8900XSPCONDataSwap;
 #endif
         // SPI Clock Value = Cell Clock / prescale
         _spiPreReg = (((UInt64)fNCLKFrequency * sclkPeriod) + 1000000000ULL - 1) / 1000000000ULL;
         SPI_LOG( DEBUG_SPEW, "NCLK %p\t Prescaler %p\n", (void *)fNCLKFrequency, (void *)_spiPreReg );
         // SPI Inter-byte Delay = PCLK period * delay cycles
          _spiIDDReg = (((UInt64)fPCLKFrequency * fConfiguration.spiWordDelay) + 1000000000ULL - 1) / 1000000000ULL;
          SPI_LOG( DEBUG_SPEW, "SPCON: %p\tWord Size: %p\n", (void *)_spiConReg, (void *)_spiWordSize );
          SPI_LOG( DEBUG_SPEW, "SPPRE: %p\tSPIDD: %p\n", (void *)_spiPreReg, (void *)_spiIDDReg );
         return kIOReturnSuccess;
 }
AppleS5L8900XBasebandSPIController::OSDeclareDefaultStructors (AppleS5L8900XBasebandSPIController) private
IOReturn AppleS5L8900XBasebandSPIController::preflightSetupHardware (void) protected virtual
Do a preflight setup of the hardware.
Implements BasebandSPIController.
Definition at line 102 of file AppleS5L8900XBasebandSPIController.cpp.
References DEBUG_INFO, kS5L8900XSPCLKCON, kS5L8900XSPCON, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         // configure the clock registers
         writeReg32(kS5L8900XSPCON, _spiConReg);
         writeReg32(kS5L8900XSPCLKCON, _spiClkConReg);
         return kIOReturnSuccess;
 }
bool AppleS5L8900XBasebandSPIController::start (IOService * provider) virtual
Reimplemented from AppleS5LFamilyBasebandSPIController.
Definition at line 83 of file AppleS5L8900XBasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         bool ret = super::start( provider );
         _spiClockPeriod = 0;
         if ( !ret )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Starting failed\n" );
                 return ret;
         }
         registerService();
         return true;
 }
IOReturn AppleS5L8900XBasebandSPIController::startHardware (void) protected virtual
Start the hardware for the transfer.
Implements BasebandSPIController.
Definition at line 292 of file AppleS5L8900XBasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_SPEW, kS5L8900XSPCLKCON, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         if ( clockEnabled() )
         {
                 writeReg32( kS5L8900XSPCLKCON, _spiClkConReg );
         }
         else
         {
                 SPI_LOG( DEBUG_CRITICAL, "AppleS5L8900XBasebandSPIController::startHardware: clock not enabled\n" );
         }
         return kIOReturnSuccess;
 }
IOReturn AppleS5L8900XBasebandSPIController::takeSnapshot (const char * comment, BasebandSPIControllerSnapshot::PinState resetDetectState, BasebandSPIControllerSnapshot ** snapshot) protected virtual
Implements AppleS5LFamilyBasebandSPIController.
Definition at line 266 of file AppleS5L8900XBasebandSPIController.cpp.
References AppleS5L8900XBasebandSPIControllerSnapshot::AppleS5L8900XBasebandSPIControllerSnapshot(), kS5L8900XSPCLKCON, kS5L8900XSPCNT, kS5L8900XSPCON, and kS5L8900XSPSTA.
Referenced by getDebugName().
 {
         bool wasClockEnabled = clockEnabled();
         // Enable the SPI clock temporarily for snapshot, if not already enabled
         if (!wasClockEnabled)
         {
                 enableClock(true);
         }
         *snapshot = new AppleS5L8900XBasebandSPIControllerSnapshot( comment,
                                                 resetDetectState,
                                                 readReg32(kS5L8900XSPCLKCON),
                                                 readReg32(kS5L8900XSPCON),
                                                 readReg32(kS5L8900XSPSTA),
                                                 readReg32(kS5L8900XSPCNT) );
         // Disable SPI clock temporarily for snapshot, if enabled just for duration of snapshot
         if (!wasClockEnabled)
         {
                 enableClock(false);
         }
         return kIOReturnSuccess;
 }
IOReturn AppleS5L8900XBasebandSPIController::unconfigureHardware (void) protected virtual
Power down the hardware.
Implements BasebandSPIController.
Definition at line 235 of file AppleS5L8900XBasebandSPIController.cpp.
References DEBUG_SPEW, kS5L8900XSPCLKCON, kS5L8900XSPCON, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         if ( clockEnabled() )
         {
                 writeReg32(kS5L8900XSPCON, _spiConReg);
                 writeReg32(kS5L8900XSPCLKCON, 0);
                 enableClock(false);
         }
         return kIOReturnSuccess;
 }
bool AppleS5L8900XBasebandSPIController::validateDeviceTypeAndChip (const char * deviceType, UInt32 chipRevision) const protected virtual
Validates the device type and chip revision
Parameters
deviceTyp the Device type
chipRevision the chip revision
Returns
True if OK, false if not compatible
Implements BasebandSPIController.
Definition at line 308 of file AppleS5L8900XBasebandSPIController.cpp.
 {
         (void)deviceType;
         (void)chipRevision;
         return true;
 }
Member Data Documentation
UInt32 AppleS5L8900XBasebandSPIController::_spiClkConReg private
Definition at line 108 of file AppleS5L8900XBasebandSPIController.h.
UInt32 AppleS5L8900XBasebandSPIController::_spiClockPeriod private
Definition at line 105 of file AppleS5L8900XBasebandSPIController.h.
UInt32 AppleS5L8900XBasebandSPIController::_spiConReg private
Definition at line 109 of file AppleS5L8900XBasebandSPIController.h.
UInt32 AppleS5L8900XBasebandSPIController::_spiIDDReg private
Definition at line 111 of file AppleS5L8900XBasebandSPIController.h.
UInt32 AppleS5L8900XBasebandSPIController::_spiPreReg private
Definition at line 110 of file AppleS5L8900XBasebandSPIController.h.
UInt32 AppleS5L8900XBasebandSPIController::_spiWordSize private
Definition at line 104 of file AppleS5L8900XBasebandSPIController.h.
UInt32 AppleS5L8900XBasebandSPIController::_spiWordTime private
Definition at line 103 of file AppleS5L8900XBasebandSPIController.h.
The documentation for this class was generated from the following files:
/BasebandSPI/AppleS5L8900XBasebandSPIController.h
/BasebandSPI/AppleS5L8900XBasebandSPIController.cpp