BasebandSPICommand Class Reference
BasebandSPICommand Class Reference abstract
#include <BasebandSPICommand.h>
Inherits IODMACommand.
Inherited by BasebandSPICommandVersion1, and BasebandSPICommandVersion2.
Public Member Functions
virtual IOReturn clearMemoryDescriptor (void)
void dumpFrame (int level) const
void * getCookie (void) const
BasebandSPICommand * getNext (void) const
bool isFinalized (void) const
virtual void reset (void)=0
IOReturn setMemoryDescriptor (IOMemoryDescriptor *md, UInt8 *buffer, void *cookie)
void setNext (BasebandSPICommand *command)
virtual IOByteCount writeData (UInt8 *source, IOByteCount amount, IOByteCount dataSize)=0
Protected Member Functions
void clearFinalized (void)
virtual void dumpFrameInternal (int logLevel) const =0
virtual void free (void)
virtual const char * getDebugName (void) const =0
virtual IOReturn init (IODirection direction)
void setFinalized (void)
Protected Attributes
UInt8 * fBuffer
void * fCookie
IODirection fDirection
bool fIsFinalized
IOMemoryDescriptor * fMemoryDescriptor
BasebandSPICommand * fNext
Private Member Functions
OSDeclareAbstractStructors (BasebandSPICommand)
Friends
class BasebandSPILogger
Detailed Description
Definition at line 32 of file BasebandSPICommand.h.
Member Function Documentation
void BasebandSPICommand::clearFinalized (void) inline protected
Definition at line 102 of file BasebandSPICommand.h.
References fIsFinalized.
Referenced by BasebandSPICommandVersion1::reset(), and BasebandSPICommandVersion2::reset().
         {
                 fIsFinalized = false;
         };
IOReturn BasebandSPICommand::clearMemoryDescriptor (void) virtual
Definition at line 70 of file BasebandSPICommand.cpp.
References fBuffer, and fMemoryDescriptor.
Referenced by BasebandSPIIFXProtocolVersion1::handleTransferComplete(), BasebandSPIIFXProtocolVersion2::handleTransferComplete(), and BasebandSPIProtocol::unregisterAllRxBuffers().
 {
         fBuffer                         = NULL;
         fMemoryDescriptor       = NULL;
         return super::clearMemoryDescriptor( false );
 }
void BasebandSPICommand::dumpFrame (int level) const inline
Definition at line 84 of file BasebandSPICommand.h.
References DEBUG_LEVEL, dumpFrameInternal(), free(), and init().
Referenced by BasebandSPIIFXProtocolVersion1::handleTransferComplete(), and BasebandSPIIFXProtocolVersion2::handleTransferComplete().
         {
                 if ( level <= DEBUG_LEVEL )
                 {
                         dumpFrameInternal( level );
                 }
         }
virtual void BasebandSPICommand::dumpFrameInternal (int logLevel) const protected pure virtual
Implemented in BasebandSPICommandVersion2, and BasebandSPICommandVersion1.
Referenced by dumpFrame(), and getNext().
void BasebandSPICommand::free (void) protected virtual
Definition at line 78 of file BasebandSPICommand.cpp.
References fMemoryDescriptor.
Referenced by dumpFrame().
 {
         if ( fMemoryDescriptor )
         {
                 super::setMemoryDescriptor( NULL, false );
                 fMemoryDescriptor->release();
                 fMemoryDescriptor = NULL;
         }
         super::free();
 }
void* BasebandSPICommand::getCookie (void) const inline
Definition at line 58 of file BasebandSPICommand.h.
References fCookie.
Referenced by BasebandSPIIFXProtocolVersion1::handleTransferComplete(), BasebandSPIIFXProtocolVersion2::handleTransferComplete(), BasebandSPIProtocol::registerRxBuffer(), and BasebandSPIProtocol::unregisterAllRxBuffers().
         {
                 return fCookie;
         }
virtual const char* BasebandSPICommand::getDebugName (void) const protected pure virtual
Implemented in BasebandSPICommandVersion2, and BasebandSPICommandVersion1.
Referenced by getNext().
BasebandSPICommand* BasebandSPICommand::getNext (void) const inline
Definition at line 73 of file BasebandSPICommand.h.
References dumpFrameInternal(), fNext, and getDebugName().
Referenced by BasebandSPICommandQueue::dequeueHead().
         {
                 return fNext;
         };
IOReturn BasebandSPICommand::init (IODirection direction) protected virtual
Reimplemented in BasebandSPICommandVersion2, and BasebandSPICommandVersion1.
Definition at line 32 of file BasebandSPICommand.cpp.
References DEBUG_CRITICAL, fBuffer, fCookie, fDirection, fIsFinalized, fNext, and SPI_LOG.
Referenced by dumpFrame(), BasebandSPICommandVersion1::init(), and BasebandSPICommandVersion2::init().
 {
         if ( !super::initWithSpecification(kIODMACommandOutputHost32, 32, 0) )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Failed initialising DMA command\n" );
                 return kIOReturnError;
         }
         if ( direction != kIODirectionIn && direction != kIODirectionOut )
         {
                 SPI_LOG( DEBUG_CRITICAL, "direction must be kIODirectionIn or kIODirectionOut\n" );
                 return kIOReturnError;
         }
         fCookie                 = NULL;
         fDirection              = direction;
         fBuffer                 = NULL;
         fIsFinalized    = false;
         fNext                   = NULL;
         return kIOReturnSuccess;
 }
bool BasebandSPICommand::isFinalized (void) const inline
Definition at line 63 of file BasebandSPICommand.h.
References fIsFinalized.
Referenced by BasebandSPIProtocol::getTxPendingCommand().
         {
                 return fIsFinalized;
         }
BasebandSPICommand::OSDeclareAbstractStructors (BasebandSPICommand) private
virtual void BasebandSPICommand::reset (void) pure virtual
Implemented in BasebandSPICommandVersion2, and BasebandSPICommandVersion1.
Referenced by BasebandSPIProtocol::addRxUnusedCommand(), and BasebandSPIProtocol::addTxUnusedCommand().
void BasebandSPICommand::setFinalized (void) inline protected
Definition at line 97 of file BasebandSPICommand.h.
References fIsFinalized.
Referenced by BasebandSPICommandVersion1::finalize(), and BasebandSPICommandVersion2::finalize().
         {
                 fIsFinalized = true;
         };
IOReturn BasebandSPICommand::setMemoryDescriptor (IOMemoryDescriptor * md, UInt8 * buffer, void * cookie)
Definition at line 55 of file BasebandSPICommand.cpp.
References fBuffer, fCookie, and fMemoryDescriptor.
Referenced by BasebandSPIIFXProtocolVersion1::allocateTxCommand(), BasebandSPIIFXProtocolVersion2::allocateTxCommand(), and BasebandSPIProtocol::registerRxBuffer().
 {
         IOReturn ret = super::setMemoryDescriptor( md, false );
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         fMemoryDescriptor = md;
         fBuffer         = virtualAddress;
         fCookie         = cookie;
         return kIOReturnSuccess;
 }
void BasebandSPICommand::setNext (BasebandSPICommand * command) inline
Definition at line 68 of file BasebandSPICommand.h.
References fNext.
Referenced by BasebandSPICommandQueue::dequeueHead(), and BasebandSPICommandQueue::enqueueTail().
         {
                 fNext = command;
         };
virtual IOByteCount BasebandSPICommand::writeData (UInt8 * source, IOByteCount amount, IOByteCount dataSize) pure virtual
Writes some data into this command
Parameters
source The buffer representing the source of the data to write
amount The amount of data to write from the buffer
dataSize The maximum data that can be written to this command (in total, including what's already written)
Returns
the amount written
Implemented in BasebandSPICommandVersion1, and BasebandSPICommandVersion2.
Referenced by BasebandSPIProtocol::copyTxBuffer().
Friends And Related Function Documentation
friend class BasebandSPILogger friend
Definition at line 36 of file BasebandSPICommand.h.
Member Data Documentation
UInt8* BasebandSPICommand::fBuffer protected
Definition at line 110 of file BasebandSPICommand.h.
Referenced by clearMemoryDescriptor(), BasebandSPICommandVersion1::dumpFrameInternal(), BasebandSPICommandVersion2::dumpFrameInternal(), BasebandSPICommandVersion1::getHeader(), BasebandSPICommandVersion2::getHeader(), BasebandSPICommandVersion1::getPayload(), BasebandSPICommandVersion2::getPayload(), init(), BasebandSPILogger::logFrame(), and setMemoryDescriptor().
void* BasebandSPICommand::fCookie protected
Definition at line 105 of file BasebandSPICommand.h.
Referenced by getCookie(), init(), and setMemoryDescriptor().
IODirection BasebandSPICommand::fDirection protected
Definition at line 109 of file BasebandSPICommand.h.
Referenced by BasebandSPICommandVersion1::dumpFrameInternal(), BasebandSPICommandVersion2::dumpFrameInternal(), and init().
bool BasebandSPICommand::fIsFinalized protected
Definition at line 111 of file BasebandSPICommand.h.
Referenced by clearFinalized(), init(), isFinalized(), and setFinalized().
IOMemoryDescriptor* BasebandSPICommand::fMemoryDescriptor protected
Definition at line 115 of file BasebandSPICommand.h.
Referenced by clearMemoryDescriptor(), BasebandSPICommandVersion1::finalize(), BasebandSPICommandVersion2::finalize(), free(), and setMemoryDescriptor().
BasebandSPICommand* BasebandSPICommand::fNext protected
Definition at line 117 of file BasebandSPICommand.h.
Referenced by getNext(), init(), and setNext().
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPICommand.h
/BasebandSPI/BasebandSPICommand.cpp