BasebandSPIProtocol Class Reference
BasebandSPIProtocol Class Reference abstract
#include <BasebandSPIProtocol.h>
Inherits OSObject.
Inherited by BasebandSPIIFXProtocol, and ReliableBasebandSPIProtocol.
Public Member Functions
virtual IOReturn activate (void)
IOReturn copyTxBuffer (UInt8 *source, IOByteCount length, IOByteCount *remaining, bool transmitNow)
virtual IOReturn deactivate (void)
virtual IOReturn enterLowPower (void)
virtual IOReturn exitLowPower (void)
IOByteCount getFramePayloadSize (void) const
IOByteCount getFrameSize (void) const
IOByteCount getMaxRxBufferCount (void) const
virtual BasebandSPIProtocolSnapshot * getSnapshot (void) const =0
virtual IOReturn handleCancelledRxCommand (IODMACommand *command)=0
virtual IOReturn handleCancelledTxCommand (IODMACommand *command)=0
virtual IOReturn handleTransferCancelled (void)=0
virtual IOReturn handleTransferComplete (IODMACommand *receivedCommand, IODMACommand *sendCommand)=0
virtual bool isSRDYStateHigh (void)=0
virtual IOReturn predeactivate (void)
IOReturn registerRxBuffer (IOMemoryDescriptor *md, UInt8 *virtualAddress, void *cookie)
virtual IOReturn unregisterAllRxBuffers (void)
Static Public Member Functions
static BasebandSPIProtocol * create (BasebandSPIController *controller, BasebandSPIDevice *device)
Protected Types
enum PrepareFlags { kPrepareInitiate = 1UL << 0, kPrepareStart = 1UL << 1, kPrepareRxRegistered = 1UL << 2 }
Protected Member Functions
IOReturn addEventSource (IOEventSource **es, const char *name)
void addRxFreeCommand (BasebandSPICommand *command)
void addRxUnusedCommand (BasebandSPICommand *command)
void addTxUnusedCommand (BasebandSPICommand *command)
virtual BasebandSPICommand * allocateRxCommand (void) const =0
virtual BasebandSPICommand * allocateTxCommand (void) const =0
virtual void free (void)
virtual const char * getDebugName (void) const =0
virtual IOByteCount getHeaderAndFooterSize (void) const =0
UInt32 getNumRxUnusedCommands (void) const
UInt32 getNumTxUnusedCommands (void) const
unsigned getRemainingTimeLeftMicroSec (const uint64_t end, const uint64_t start, unsigned differenceMicroseconds)
BasebandSPICommand * getRxFreeCommand (void)
BasebandSPICommand * getRxUnusedCommand (void)
void getTime (uint64_t *time) const
BasebandSPICommand * getTxPendingCommand (void) const
BasebandSPICommand * getTxUnusedCommand (void)
bool getUInt32PropertyFromController (const char *name, UInt32 *device)
IOWorkLoop * getWorkLoop (void) const
virtual bool init (BasebandSPIController *controller, BasebandSPIDevice *device)
virtual void prepareTransferIfNeeded (UInt32 prepareFlags)=0
Static Protected Member Functions
static const char * getDebugNameStatic (void)
static bool getUInt32PropertyWithProvider (IOService *provider, const char *name, UInt32 *device)
Protected Attributes
BasebandSPICommandQueue * fCommandQueue
BasebandSPIController * fController
BasebandSPIDevice * fDevice
IOByteCount fFramePayloadSize
IOByteCount fFrameSize
bool fInLowPower
UInt32 fRxAvailableBufferCount
UInt32 fRxBufferCount
IOCommandPool * fRxDMACommandPool
IOCommandPool * fRxFreeCommandPool
UInt32 fTxAvailableBufferCount
UInt32 fTxBufferCount
IOCommandPool * fTxDMACommandPool
Private Member Functions
IOReturn allocateCommands (void)
IOReturn flushTxBuffers (void)
IOReturn freeCommands (void)
OSDeclareAbstractStructors (BasebandSPIProtocol)
Detailed Description
Definition at line 32 of file BasebandSPIProtocol.h.
Member Enumeration Documentation
enum BasebandSPIProtocol::PrepareFlags protected
Enumerator
kPrepareInitiate
kPrepareStart
kPrepareRxRegistered
Definition at line 37 of file BasebandSPIProtocol.h.
         {
                 kPrepareInitiate        = 1UL << 0,
                 kPrepareStart           = 1UL << 1,
                 kPrepareRxRegistered = 1UL << 2
         }
Member Function Documentation
IOReturn BasebandSPIProtocol::activate (void) virtual
Reimplemented in BasebandSPIIFXProtocolVersion2, BasebandSPIIFXProtocolVersion1, and BasebandSPIIFXProtocol.
Definition at line 169 of file BasebandSPIProtocol.cpp.
References allocateCommands(), DEBUG_SPEW, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         IOReturn ret;
         ret = allocateCommands();
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIProtocol::addEventSource (IOEventSource ** es, const char * name) protected
Definition at line 287 of file BasebandSPIProtocol.cpp.
References DEBUG_CRITICAL, fDevice, and SPI_LOG.
Referenced by BasebandSPIIFXProtocol::createEventSources().
 {
         if ( !( *es ) )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't get %s event source\n", name );
                 return kIOReturnError;
         }
         IOReturn ret;
         ret = fDevice->getWorkLoop()->addEventSource( *es );
         if ( ret != kIOReturnSuccess )
         {
                 ( *es )->release();
                 ( *es ) = NULL;
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't add source for %s, ret = %p\n", name, (void *)ret );
                 return ret;
         }
         return kIOReturnSuccess;
 }
void BasebandSPIProtocol::addRxFreeCommand (BasebandSPICommand * command) inline protected
Definition at line 181 of file BasebandSPIProtocol.h.
Referenced by allocateCommands(), registerRxBuffer(), and unregisterAllRxBuffers().
         {
                 fRxFreeCommandPool->returnCommand( command );
         };
void BasebandSPIProtocol::addRxUnusedCommand (BasebandSPICommand * command) inline protected
Definition at line 186 of file BasebandSPIProtocol.h.
References DEBUG_SPEW, BasebandSPICommand::reset(), and SPI_LOG.
Referenced by registerRxBuffer().
         {
                 // reset the command so we can reuse it
                 command->reset();
                 fRxAvailableBufferCount++;
                 SPI_LOG( DEBUG_SPEW, "Increase to %u\n", (unsigned)fRxAvailableBufferCount );
                 fRxDMACommandPool->returnCommand( command );
         };
void BasebandSPIProtocol::addTxUnusedCommand (BasebandSPICommand * command) inline protected
Definition at line 172 of file BasebandSPIProtocol.h.
References DEBUG_SPEW, BasebandSPICommand::reset(), and SPI_LOG.
Referenced by allocateCommands(), and flushTxBuffers().
         {
                 // reset the command so we can reuse it
                 command->reset();
                 fTxAvailableBufferCount++;
                 SPI_LOG( DEBUG_SPEW, "Increase to %u\n", (unsigned)fTxAvailableBufferCount );
                 fTxDMACommandPool->returnCommand( command );
         }
IOReturn BasebandSPIProtocol::allocateCommands (void) inline private
Definition at line 332 of file BasebandSPIProtocol.cpp.
References addRxFreeCommand(), addTxUnusedCommand(), allocateRxCommand(), allocateTxCommand(), DEBUG_CRITICAL, DEBUG_INFO, DEBUG_SPEW, fRxBufferCount, fTxBufferCount, SPI_LOG, and SPI_TRACE.
Referenced by activate().
 {
         SPI_TRACE( DEBUG_SPEW );
         for ( unsigned i = 0; i < fRxBufferCount; i++ )
         {
                 BasebandSPICommand * command = allocateRxCommand();
                 if ( !command )
                 {
                         SPI_LOG( DEBUG_CRITICAL, "Failed to allocate Rx command %u\n", i );
                         return kIOReturnNoMemory;
                 }
                 addRxFreeCommand( command );
         }
         SPI_LOG( DEBUG_INFO, "Allocated Rx %u commands\n", (unsigned)fRxBufferCount );
         for ( unsigned i = 0; i < fTxBufferCount; i++ )
         {
                 BasebandSPICommand * command = allocateTxCommand();
                 if ( !command )
                 {
                         SPI_LOG( DEBUG_CRITICAL, "Failed to allocate Tx command %u\n", i );
                         return kIOReturnNoMemory;
                 }
                 addTxUnusedCommand( command );
         }
         SPI_LOG( DEBUG_INFO, "Allocated Tx %u commands\n", (unsigned)fRxBufferCount );
         return kIOReturnSuccess;
 }
virtual BasebandSPICommand* BasebandSPIProtocol::allocateRxCommand (void) const protected pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by allocateCommands().
virtual BasebandSPICommand* BasebandSPIProtocol::allocateTxCommand (void) const protected pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by allocateCommands().
IOReturn BasebandSPIProtocol::copyTxBuffer (UInt8 * source, IOByteCount length, IOByteCount * remaining, bool transmitNow)
Definition at line 409 of file BasebandSPIProtocol.cpp.
References DEBUG_SPEW, BasebandSPICommandQueue::enqueueTail(), fCommandQueue, fFramePayloadSize, fInLowPower, getNumTxUnusedCommands(), BasebandSPICommandQueue::getSize(), getTxPendingCommand(), getTxUnusedCommand(), getWorkLoop(), isSRDYStateHigh(), kPrepareInitiate, BasebandSPILogger::logGeneral(), prepareTransferIfNeeded(), SPI_ASSERT, SPI_TRACE, and BasebandSPICommand::writeData().
 {
         SPI_TRACE( DEBUG_SPEW );
 #if SPI_PEDANTIC_ASSERT
         SPI_ASSERT( length, !=, 0 );
         SPI_ASSERT( source, !=, NULL );
         SPI_ASSERT( getWorkLoop()->inGate(), ==, true );
 #endif
         if ( fInLowPower )
         {
                 *remaining = length;
                 return kIOReturnSuccess;
         }
         BasebandSPICommand * command = getTxPendingCommand();
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "CTx", 0, isSRDYStateHigh() );
 #else
         BasebandSPILogger::logGeneral( "CTx", 0 );
 #endif
         bool isPending;
         if ( command )
         {
                 isPending = true;
         }
         else
         {
                 if ( getNumTxUnusedCommands() < 2 )
                 {
                         *remaining = length;
                         return kIOReturnSuccess;
                 }
                 isPending = false;
                 command = getTxUnusedCommand();
 #if SPI_PEDANTIC_ASSERT
                 SPI_ASSERT( command, !=, NULL );
 #endif
 #if SPI_SRDY_DEBUG
                 BasebandSPILogger::logGeneral( "CTX", 0x9 | ( getNumTxUnusedCommands() << 8 ), isSRDYStateHigh() );
 #else
                 BasebandSPILogger::logGeneral( "CTX", 0x9 | ( getNumTxUnusedCommands() << 8 ) );
 #endif
         }
         while ( 1 )
         {
 #if SPI_SRDY_DEBUG
                 BasebandSPILogger::logGeneral( "CTx", 1, isSRDYStateHigh() );
 #else
                 BasebandSPILogger::logGeneral( "CTx", 1 );
 #endif
                 IOByteCount written = command->writeData( (UInt8 *)source, length, fFramePayloadSize );
                 if ( isPending )
                 {
                         isPending = false;
                 }
                 else
                 {
 #if SPI_SRDY_DEBUG
                         BasebandSPILogger::logGeneral( "CTx", 2  | ( fCommandQueue->getSize() << 8 ), isSRDYStateHigh() );
 #else
                         BasebandSPILogger::logGeneral( "CTx", 2  | ( fCommandQueue->getSize() << 8 ) );
 #endif
                         fCommandQueue->enqueueTail( command );
                 }
                 source += written;
                 length -= written;
                 if ( length )
                 {
                         if ( getNumTxUnusedCommands() < 2 )
{
                                 break;
                         }
                         command = getTxUnusedCommand();
 #if SPI_PEDANTIC_ASSERT
                         SPI_ASSERT( command, !=, NULL );
 #endif
                 }
                 else
                 {
                         break;
                 }
         }
         *remaining = length;
         if ( length || transmitNow )
         {
                 prepareTransferIfNeeded( kPrepareInitiate );
         }
         return kIOReturnSuccess;
 }
BasebandSPIProtocol * BasebandSPIProtocol::create (BasebandSPIController * controller, BasebandSPIDevice * device) static
Definition at line 12 of file BasebandSPIProtocol.cpp.
References DEBUG_CRITICAL, getUInt32PropertyWithProvider(), init(), and SPI_LOG_STATIC.
Referenced by BasebandSPIDevice::start().
 {
         UInt32 protocolVersion;
         if ( !getUInt32PropertyWithProvider( controller->getProvider(), "protocol-version", &protocolVersion ) )
         {
                 return NULL;
         }
         BasebandSPIProtocol * protocol;
         switch( protocolVersion )
         {
         case 1:
                 protocol = new BasebandSPIIFXProtocolVersion1();
                 break;
         case 2:
                 protocol = new BasebandSPIIFXProtocolVersion2();
                 break;
         default:
                 SPI_LOG_STATIC( DEBUG_CRITICAL, "unrecognized version %u\n", (unsigned)protocolVersion );
                 return NULL;
         }
         if ( !protocol->init( controller, device ) )
         {
                 delete protocol;
                 protocol = NULL;
         }
         return protocol;
 }
IOReturn BasebandSPIProtocol::deactivate (void) virtual
Definition at line 189 of file BasebandSPIProtocol.cpp.
References DEBUG_SPEW, flushTxBuffers(), freeCommands(), SPI_ASSERT_SUCCESS, SPI_TRACE, and unregisterAllRxBuffers().
 {
         SPI_TRACE( DEBUG_SPEW );
         IOReturn ret;
         ret = unregisterAllRxBuffers();
         SPI_ASSERT_SUCCESS( ret );
         ret = flushTxBuffers();
         SPI_ASSERT_SUCCESS( ret );
         ret = freeCommands();
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIProtocol::enterLowPower (void) virtual
Reimplemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Definition at line 210 of file BasebandSPIProtocol.cpp.
References fInLowPower, flushTxBuffers(), SPI_ASSERT, and SPI_ASSERT_SUCCESS.
 {
         IOReturn ret;
         ret = flushTxBuffers();
         SPI_ASSERT_SUCCESS( ret );
         SPI_ASSERT( fInLowPower, ==, false );
         fInLowPower = true;
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIProtocol::exitLowPower (void) virtual
Reimplemented in BasebandSPIIFXProtocolVersion2, BasebandSPIIFXProtocolVersion1, and BasebandSPIIFXProtocol.
Definition at line 222 of file BasebandSPIProtocol.cpp.
References fDevice, fInLowPower, BasebandSPIDevice::invokeCompletionCallback(), kBasebandSPIReturnTxReady, and SPI_ASSERT.
 {
         SPI_ASSERT( fInLowPower, ==, true );
         fInLowPower = false;
         fDevice->invokeCompletionCallback( NULL, kBasebandSPIReturnTxReady, 0, 0 );
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIProtocol::flushTxBuffers (void) inline private
Definition at line 264 of file BasebandSPIProtocol.cpp.
References addTxUnusedCommand(), DEBUG_INFO, DEBUG_SPEW, BasebandSPICommandQueue::dequeueHead(), fCommandQueue, BasebandSPICommandQueue::getSize(), BasebandSPICommandQueue::isEmpty(), SPI_ASSERT, SPI_LOG, and SPI_TRACE.
Referenced by deactivate(), and enterLowPower().
 {
         SPI_TRACE( DEBUG_SPEW );
         UInt32 size = fCommandQueue->getSize();
         SPI_LOG( DEBUG_INFO, "Have %u buffers to flush\n", (unsigned)size );
         while ( size )
         {
                 BasebandSPICommand * command = fCommandQueue->dequeueHead();
                 SPI_ASSERT( command, !=, NULL );
                 addTxUnusedCommand( command );
                 size--;
         }
         SPI_ASSERT( fCommandQueue->isEmpty(), ==, true );
         return kIOReturnSuccess;
 }
void BasebandSPIProtocol::free (void) protected virtual
Reimplemented in BasebandSPIIFXProtocolVersion2, BasebandSPIIFXProtocolVersion1, and BasebandSPIIFXProtocol.
Definition at line 111 of file BasebandSPIProtocol.cpp.
References DEBUG_SPEW, fCommandQueue, fRxDMACommandPool, fRxFreeCommandPool, fTxDMACommandPool, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         if ( fRxFreeCommandPool )
         {
                 fRxFreeCommandPool->release();
                 fRxFreeCommandPool = NULL;
         }
         if ( fRxDMACommandPool )
         {
                 fRxDMACommandPool->release();
                 fRxDMACommandPool = NULL;
         }
         if ( fTxDMACommandPool )
         {
                 fTxDMACommandPool->release();
                 fTxDMACommandPool = NULL;
         }
         if ( fCommandQueue )
         {
                 delete fCommandQueue;
                 fCommandQueue = NULL;
         }
         super::free();
 }
IOReturn BasebandSPIProtocol::freeCommands (void) inline private
Definition at line 367 of file BasebandSPIProtocol.cpp.
References DEBUG_SPEW, fRxBufferCount, fRxFreeCommandPool, fTxBufferCount, fTxDMACommandPool, getRxFreeCommand(), getRxUnusedCommand(), getTxUnusedCommand(), SPI_ASSERT, and SPI_TRACE.
Referenced by deactivate().
 {
         SPI_TRACE( DEBUG_SPEW );
         SPI_ASSERT( getRxUnusedCommand(), ==, NULL );
         unsigned i;
         for ( i = 0; ; i++ )
         {
                 BasebandSPICommand * command = getRxFreeCommand();
                 if ( command )
                 {
                         command->release();
                 }
                 else
                 {
                         break;
                 }
         }
         SPI_ASSERT( fRxFreeCommandPool->getCommand( false ), ==, NULL );
         SPI_ASSERT( i, ==, fRxBufferCount );
         for ( i = 0; ; i++ )
         {
                 BasebandSPICommand * command = getTxUnusedCommand();
                 if ( command )
                 {
                         command->release();
                 }
                 else
                 {
                         break;
                 }
         }
         SPI_ASSERT( fTxDMACommandPool->getCommand( false ), ==, NULL );
         SPI_ASSERT( i, ==, fTxBufferCount );
         return kIOReturnSuccess;
 }
virtual const char* BasebandSPIProtocol::getDebugName (void) const protected pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
static const char* BasebandSPIProtocol::getDebugNameStatic (void) inline static protected
Definition at line 55 of file BasebandSPIProtocol.h.
         {
                 return "BasebandSPIProtocol";
         };
IOByteCount BasebandSPIProtocol::getFramePayloadSize (void) const inline
Definition at line 82 of file BasebandSPIProtocol.h.
         {
                 return fFramePayloadSize;
         };
IOByteCount BasebandSPIProtocol::getFrameSize (void) const inline
Definition at line 77 of file BasebandSPIProtocol.h.
         {
                 return fFrameSize;
         }
virtual IOByteCount BasebandSPIProtocol::getHeaderAndFooterSize (void) const protected pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by init().
IOByteCount BasebandSPIProtocol::getMaxRxBufferCount (void) const inline
Definition at line 87 of file BasebandSPIProtocol.h.
         {
                 return fRxBufferCount;
         }
UInt32 BasebandSPIProtocol::getNumRxUnusedCommands (void) const inline protected
Definition at line 200 of file BasebandSPIProtocol.h.
         {
                 return fRxAvailableBufferCount;
         };
UInt32 BasebandSPIProtocol::getNumTxUnusedCommands (void) const inline protected
Definition at line 195 of file BasebandSPIProtocol.h.
Referenced by copyTxBuffer().
         {
                 return fTxAvailableBufferCount;
         };
unsigned BasebandSPIProtocol::getRemainingTimeLeftMicroSec (const uint64_t end, const uint64_t start, unsigned differenceMicroseconds) protected
Definition at line 148 of file BasebandSPIProtocol.cpp.
Referenced by BasebandSPIIFXProtocol::setMRDY().
 {
         uint64_t diff = end - start;
         uint64_t left = 0;
         uint64_t delay;
         nanoseconds_to_absolutetime((differenceMicroseconds * 1000), (AbsoluteTime *)&delay);
         if (diff < delay)
         {
                 uint64_t absDiff = delay - diff;
                 absolutetime_to_nanoseconds(*(AbsoluteTime *)&absDiff, &left);
                 left /= 1000;
         }
         return ( (unsigned) left);
 }
BasebandSPICommand* BasebandSPIProtocol::getRxFreeCommand (void) inline protected
Definition at line 154 of file BasebandSPIProtocol.h.
Referenced by freeCommands(), and registerRxBuffer().
         {
                 return (BasebandSPICommand *)fRxFreeCommandPool->getCommand( false );
         };
BasebandSPICommand* BasebandSPIProtocol::getRxUnusedCommand (void) inline protected
Definition at line 159 of file BasebandSPIProtocol.h.
Referenced by freeCommands(), and unregisterAllRxBuffers().
         {
                 if ( fRxAvailableBufferCount )
                 {
                         fRxAvailableBufferCount--;
                         return (BasebandSPICommand *)fRxDMACommandPool->getCommand( false );
                 }
                 else
                 {
                         return NULL;
                 }
         };
virtual BasebandSPIProtocolSnapshot* BasebandSPIProtocol::getSnapshot (void) const pure virtual
Implemented in BasebandSPIIFXProtocol.
Referenced by BasebandSPIController::getNewSnapshot().
void BasebandSPIProtocol::getTime (uint64_t * time) const inline protected
Definition at line 63 of file BasebandSPIProtocol.h.
Referenced by BasebandSPIIFXProtocol::setMRDY().
         {
                 *time = mach_absolute_time();
         }
BasebandSPICommand* BasebandSPIProtocol::getTxPendingCommand (void) const inline protected
Definition at line 123 of file BasebandSPIProtocol.h.
References BasebandSPICommand::isFinalized(), and SPI_ASSERT.
Referenced by copyTxBuffer().
         {
 #if SPI_PEDANTIC_ASSERT
                 SPI_ASSERT( fCommandQueue, !=, NULL );
 #endif
                 BasebandSPICommand * command = fCommandQueue->peekTail();
                 if ( command )
                 {
                         if ( command->isFinalized() )
{
                                 command = NULL;
                         }
                 }
                 return command;
         };
BasebandSPICommand* BasebandSPIProtocol::getTxUnusedCommand (void) inline protected
Definition at line 140 of file BasebandSPIProtocol.h.
Referenced by copyTxBuffer(), and freeCommands().
         {
                 if ( fTxAvailableBufferCount )
                 {
                         fTxAvailableBufferCount--;
                         return (BasebandSPICommand *)fTxDMACommandPool->getCommand( false );
                 }
                 else
                 {
                         return NULL;
                 }
         };
bool BasebandSPIProtocol::getUInt32PropertyFromController (const char * name, UInt32 * device) protected
Definition at line 327 of file BasebandSPIProtocol.cpp.
References fController, and getUInt32PropertyWithProvider().
Referenced by init().
 {
         return getUInt32PropertyWithProvider( fController->getProvider(), name, dest );
 }
bool BasebandSPIProtocol::getUInt32PropertyWithProvider (IOService * provider, const char * name, UInt32 * device) static protected
Definition at line 311 of file BasebandSPIProtocol.cpp.
References DEBUG_CRITICAL, and SPI_LOG_STATIC.
Referenced by create(), and getUInt32PropertyFromController().
 {
         OSData * data;
         data = OSDynamicCast( OSData, provider->getProperty( name ) );
         if ( !data )
         {
                 SPI_LOG_STATIC( DEBUG_CRITICAL, "Property '%s' not found\n", name );
                 return false;
         }
         *dest = *( (UInt32 *)data->getBytesNoCopy() );
         return true;
 }
IOWorkLoop * BasebandSPIProtocol::getWorkLoop (void) const protected
Definition at line 142 of file BasebandSPIProtocol.cpp.
References fController, and BasebandSPIController::getWorkLoop().
Referenced by copyTxBuffer(), and registerRxBuffer().
 {
         return fController->getWorkLoop();
 }
virtual IOReturn BasebandSPIProtocol::handleCancelledRxCommand (IODMACommand * command) pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by BasebandSPIController::handleCancelledRxDMACommand().
virtual IOReturn BasebandSPIProtocol::handleCancelledTxCommand (IODMACommand * command) pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by BasebandSPIController::handleCancelledTxDMACommand().
virtual IOReturn BasebandSPIProtocol::handleTransferCancelled (void) pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by BasebandSPIController::handleDMACompleteOnCancel().
virtual IOReturn BasebandSPIProtocol::handleTransferComplete (IODMACommand * receivedCommand, IODMACommand * sendCommand) pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by BasebandSPIController::handleDMACompleteOnActive().
bool BasebandSPIProtocol::init (BasebandSPIController * controller, BasebandSPIDevice * device) protected virtual
Reimplemented in BasebandSPIIFXProtocolVersion2, BasebandSPIIFXProtocolVersion1, and BasebandSPIIFXProtocol.
Definition at line 47 of file BasebandSPIProtocol.cpp.
References DEBUG_SPEW, fCommandQueue, fController, fDevice, fFramePayloadSize, fFrameSize, fInLowPower, fRxBufferCount, fRxDMACommandPool, fRxFreeCommandPool, fTxBufferCount, fTxDMACommandPool, getHeaderAndFooterSize(), getUInt32PropertyFromController(), BasebandSPIController::getWorkLoop(), and SPI_TRACE.
Referenced by create().
 {
         SPI_TRACE( DEBUG_SPEW );
         fController                     = NULL;
         fDevice                         = NULL;
         fCommandQueue           = NULL;
         fFramePayloadSize       = NULL;
         fRxBufferCount          = 0;
         fTxBufferCount          = 0;
         fRxFreeCommandPool      = NULL;
         fRxDMACommandPool       = NULL;
         fTxDMACommandPool       = NULL;
         fInLowPower                     = false;
         if ( !super::init() )
         {
                 return false;
         }
         fController                     = controller;
         fDevice                         = device;
         fCommandQueue = new BasebandSPICommandQueue();
         fRxFreeCommandPool = IOCommandPool::withWorkLoop( fController->getWorkLoop() );
         if ( !fRxFreeCommandPool )
         {
                 return false;
         }
         fRxDMACommandPool = IOCommandPool::withWorkLoop( fController->getWorkLoop() );
         if ( !fRxDMACommandPool )
         {
                 return false;
         }
         fTxDMACommandPool = IOCommandPool::withWorkLoop( fController->getWorkLoop() );
         if ( !fTxDMACommandPool )
         {
                 return false;
         }
         if ( !getUInt32PropertyFromController( "max-data-size", (UInt32 *)&fFramePayloadSize ) )
         {
                 return false;
         }
         if ( !getUInt32PropertyFromController( "rx-buffer-count", &fRxBufferCount ) )
         {
                 return false;
         }
         if ( !getUInt32PropertyFromController( "tx-buffer-count", &fTxBufferCount ) )
         {
                 return false;
         }
         fFrameSize = fFramePayloadSize + getHeaderAndFooterSize();
         return true;
 }
virtual bool BasebandSPIProtocol::isSRDYStateHigh (void) pure virtual
Implemented in BasebandSPIIFXProtocol.
Referenced by BasebandSPIController::activate(), BasebandSPIController::configure(), BasebandSPIController::configureDMA(), copyTxBuffer(), BasebandSPIController::deactivate(), BasebandSPIController::eventSourceAsString(), registerRxBuffer(), and BasebandSPIController::unconfigure().
BasebandSPIProtocol::OSDeclareAbstractStructors (BasebandSPIProtocol) private
IOReturn BasebandSPIProtocol::predeactivate (void) virtual
Reimplemented in BasebandSPIIFXProtocolVersion2, BasebandSPIIFXProtocolVersion1, and BasebandSPIIFXProtocol.
Definition at line 184 of file BasebandSPIProtocol.cpp.
 {
         return kIOReturnSuccess;
 }
virtual void BasebandSPIProtocol::prepareTransferIfNeeded (UInt32 prepareFlags) protected pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by copyTxBuffer(), and registerRxBuffer().
IOReturn BasebandSPIProtocol::registerRxBuffer (IOMemoryDescriptor * md, UInt8 * virtualAddress, void * cookie)
Definition at line 518 of file BasebandSPIProtocol.cpp.
References addRxFreeCommand(), addRxUnusedCommand(), DEBUG_CRITICAL, DEBUG_SPEW, fInLowPower, BasebandSPICommand::getCookie(), getRxFreeCommand(), getWorkLoop(), isSRDYStateHigh(), kPrepareRxRegistered, BasebandSPILogger::logGeneral(), prepareTransferIfNeeded(), BasebandSPICommand::setMemoryDescriptor(), SPI_ASSERT, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
 #if SPI_PEDANTIC_ASSERT
         SPI_ASSERT( getWorkLoop()->inGate(), ==, true );
 #endif
         BasebandSPICommand * command = getRxFreeCommand();
         if ( !command )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Registered too many commands\n" );
                 return kIOReturnNotPermitted;
         }
         SPI_LOG( DEBUG_SPEW, "Setting memory descriptor %p with cookie %p\n",
                 md, cookie );
         IOReturn ret = command->setMemoryDescriptor( md, virtualAddress, cookie );
         if ( ret != kIOReturnSuccess )
         {
                 addRxFreeCommand( command );
                 return ret;
         }
 #if SPI_PEDANTIC_ASSERT
         SPI_ASSERT( command->getMemoryDescriptor(), ==, md );
         SPI_ASSERT( command->getCookie(), ==, cookie );
 #endif
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "RRx", 0, isSRDYStateHigh() );
 #else
         BasebandSPILogger::logGeneral( "RRx", 0 );
 #endif
         addRxUnusedCommand( command );
         if ( !fInLowPower )
         {
                 prepareTransferIfNeeded( kPrepareRxRegistered );
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIProtocol::unregisterAllRxBuffers (void) virtual
Reimplemented in BasebandSPIIFXProtocolVersion2.
Definition at line 232 of file BasebandSPIProtocol.cpp.
References addRxFreeCommand(), BasebandSPICommand::clearMemoryDescriptor(), DEBUG_INFO, DEBUG_SPEW, fDevice, fRxDMACommandPool, BasebandSPICommand::getCookie(), getRxUnusedCommand(), BasebandSPIDevice::invokeCompletionCallback(), kBasebandSPIReturnRxFreed, SPI_ASSERT, SPI_LOG, and SPI_TRACE.
Referenced by deactivate().
 {
         SPI_TRACE( DEBUG_SPEW );
         UInt32 count = 0;
         while ( 1 )
         {
                 BasebandSPICommand * command = getRxUnusedCommand();
                 if ( command )
                 {
                         SPI_LOG( DEBUG_SPEW, "Returning memory descriptor %p with cookie %p\n",
                                 command->getMemoryDescriptor(), command->getCookie() );
                         fDevice->invokeCompletionCallback( command->getCookie(), kBasebandSPIReturnRxFreed, 0, 0 );
                         count++;
                         command->clearMemoryDescriptor();
                         addRxFreeCommand( command );
                 }
                 else
                 {
                         break;
                 }
         }
         SPI_ASSERT( fRxDMACommandPool->getCommand( false ), ==, NULL );
         SPI_LOG( DEBUG_INFO, "Freed %u commands\n", (unsigned)count );
         return kIOReturnSuccess;
 }
Member Data Documentation
BasebandSPICommandQueue* BasebandSPIProtocol::fCommandQueue protected
Definition at line 212 of file BasebandSPIProtocol.h.
Referenced by copyTxBuffer(), flushTxBuffers(), free(), and init().
BasebandSPIController* BasebandSPIProtocol::fController protected
Definition at line 210 of file BasebandSPIProtocol.h.
Referenced by BasebandSPIIFXProtocol::createEventSources(), BasebandSPIIFXProtocol::createFunctions(), getUInt32PropertyFromController(), getWorkLoop(), BasebandSPIIFXProtocol::handleSRDYTimeoutAction(), and init().
BasebandSPIDevice* BasebandSPIProtocol::fDevice protected
Definition at line 211 of file BasebandSPIProtocol.h.
Referenced by addEventSource(), exitLowPower(), init(), and unregisterAllRxBuffers().
IOByteCount BasebandSPIProtocol::fFramePayloadSize protected
Definition at line 216 of file BasebandSPIProtocol.h.
Referenced by copyTxBuffer(), and init().
IOByteCount BasebandSPIProtocol::fFrameSize protected
Definition at line 220 of file BasebandSPIProtocol.h.
Referenced by init().
bool BasebandSPIProtocol::fInLowPower protected
Definition at line 214 of file BasebandSPIProtocol.h.
Referenced by BasebandSPIIFXProtocol::canHandleSRDY(), copyTxBuffer(), enterLowPower(), exitLowPower(), init(), and registerRxBuffer().
UInt32 BasebandSPIProtocol::fRxAvailableBufferCount protected
Definition at line 222 of file BasebandSPIProtocol.h.
Referenced by BasebandSPIIFXProtocol::canHandleSRDY().
UInt32 BasebandSPIProtocol::fRxBufferCount protected
Definition at line 217 of file BasebandSPIProtocol.h.
Referenced by allocateCommands(), freeCommands(), and init().
IOCommandPool* BasebandSPIProtocol::fRxDMACommandPool protected
Definition at line 226 of file BasebandSPIProtocol.h.
Referenced by free(), init(), and unregisterAllRxBuffers().
IOCommandPool* BasebandSPIProtocol::fRxFreeCommandPool protected
Definition at line 225 of file BasebandSPIProtocol.h.
Referenced by free(), freeCommands(), and init().
UInt32 BasebandSPIProtocol::fTxAvailableBufferCount protected
Definition at line 223 of file BasebandSPIProtocol.h.
UInt32 BasebandSPIProtocol::fTxBufferCount protected
Definition at line 218 of file BasebandSPIProtocol.h.
Referenced by allocateCommands(), freeCommands(), and init().
IOCommandPool* BasebandSPIProtocol::fTxDMACommandPool protected
Definition at line 227 of file BasebandSPIProtocol.h.
Referenced by free(), freeCommands(), and init().
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPIProtocol.h
/BasebandSPI/BasebandSPIProtocol.cpp