BasebandSPICommandVersion2 Class Reference
BasebandSPICommandVersion2 Class Reference
Inherits BasebandSPICommand.
Classes
struct SPIHeader
Public Member Functions
void assertCreditReset (void)
void assertMoreToTransfer (void)
void clearHeader (void)
void dumpFrameInternal (int logLevel) const
void finalize (IOByteCount framePayloadSize, IOByteCount frameSize, UInt32 creditsGranted)
virtual const char * getDebugName (void) const
UInt32 getGrantedCredits (void) const
IOByteCount getPayloadLength (void) const
bool indicatesMoreToTransfer (void) const
bool indicatesRxError (void) const
virtual void reset (void)
virtual IOByteCount writeData (UInt8 *source, IOByteCount amount, IOByteCount dataSize)
Public Member Functions inherited from BasebandSPICommand
virtual IOReturn clearMemoryDescriptor (void)
void dumpFrame (int level) const
void * getCookie (void) const
BasebandSPICommand * getNext (void) const
bool isFinalized (void) const
IOReturn setMemoryDescriptor (IOMemoryDescriptor *md, UInt8 *buffer, void *cookie)
void setNext (BasebandSPICommand *command)
Static Public Member Functions
static BasebandSPICommandVersion2 * create (IODirection direction)
static const char * getDebugNameStatic (void)
Static Public Attributes
static const unsigned kSPIHeaderCreditBits = 12
static const unsigned kSPIHeaderDataSizeBits = 12
static const unsigned kSPIHeaderMaxDataSize = ((1UL << kSPIHeaderDataSizeBits) - 1)
Protected Member Functions
virtual IOReturn init (IODirection direction)
Protected Member Functions inherited from BasebandSPICommand
void clearFinalized (void)
virtual void free (void)
void setFinalized (void)
Private Member Functions
void dumpHeader (int logLevel) const
SPIHeader * getHeader (void) const
UInt8 * getPayload (void) const
OSDeclareDefaultStructors (BasebandSPICommandVersion2)
Private Attributes
IOByteCount fWriteOffset
Friends
class BasebandSPICommand
class BasebandSPILogger
Additional Inherited Members
Protected Attributes inherited from BasebandSPICommand
UInt8 * fBuffer
void * fCookie
IODirection fDirection
bool fIsFinalized
IOMemoryDescriptor * fMemoryDescriptor
BasebandSPICommand * fNext
Detailed Description
Definition at line 10 of file BasebandSPIIFXProtocolVersion2.cpp.
Member Function Documentation
void BasebandSPICommandVersion2::assertCreditReset (void) inline
Definition at line 67 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::SPIHeader::credit_reset, and getHeader().
Referenced by BasebandSPIIFXProtocolVersion2::prepareTransferIfNeeded().
         {
                 getHeader()->credit_reset = 1;
         }
void BasebandSPICommandVersion2::assertMoreToTransfer (void) inline
Definition at line 57 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::SPIHeader::ext_more, and getHeader().
Referenced by BasebandSPIIFXProtocolVersion2::prepareTransferIfNeeded().
         {
                 getHeader()->ext_more = 1;
         }
void BasebandSPICommandVersion2::clearHeader (void) inline
Definition at line 48 of file BasebandSPIIFXProtocolVersion2.cpp.
References getHeader(), and SPI_ASSERT.
Referenced by BasebandSPIIFXProtocolVersion2::prepareTransferIfNeeded().
         {
                 SPI_ASSERT( sizeof( SPIHeader ), ==, sizeof( UInt32 ) );
                 UInt32 * p = (UInt32 *)getHeader();
                 *p = 0;
         };
BasebandSPICommandVersion2 * BasebandSPICommandVersion2::create (IODirection direction) static
Definition at line 121 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_CRITICAL, init(), and SPI_LOG_STATIC.
Referenced by BasebandSPIIFXProtocolVersion2::allocateCommand().
 {
         BasebandSPICommandVersion2 * command = new BasebandSPICommandVersion2();
         IOReturn ret = command->init( direction );
         if ( ret != kIOReturnSuccess )
         {
                 SPI_LOG_STATIC( DEBUG_CRITICAL, "Command initialization failed with error %p\n", ret );
                 command->release();
                 command = NULL;
         }
         return command;
 }
void BasebandSPICommandVersion2::dumpFrameInternal (int logLevel) const virtual
Implements BasebandSPICommand.
Definition at line 226 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::SPIHeader::curr_size, Dbg_hexdump, dumpHeader(), BasebandSPICommand::fBuffer, BasebandSPICommand::fDirection, getHeader(), getPayload(), kSPIHeaderMaxDataSize, and SPI_LOG_PLAIN.
Referenced by getDebugName().
 {
         IOMemoryDescriptor * md = (IOMemoryDescriptor *)getMemoryDescriptor();
         IOMemoryMap * map = md->map();
         SPI_LOG_PLAIN( logLevel, "--------------------------------------------------\n" );
         SPI_LOG_PLAIN( logLevel, "Direction: %s\tHeader: %p(%p), %d\tMD: %p\n", fDirection == kIODirectionOut ? "Tx" : "Rx",
                 fBuffer, map->getPhysicalAddress(), sizeof( struct BasebandSPICommandVersion2::SPIHeader ), md );
         SPI_LOG_PLAIN( logLevel, "..................................................\n" );
         map->release();
         bool valid = fBuffer != NULL;
         if ( valid )
         {
                 dumpHeader( logLevel );
         }
         else
         {
                 SPI_LOG_PLAIN( logLevel, "INVALID FRAME\n" );
         }
         SPI_LOG_PLAIN( logLevel, "..................................................\n" );
         if (valid && ( getHeader()->curr_size != kSPIHeaderMaxDataSize ) ) {
                 IOByteCount size = MIN( md->getLength(), getHeader()->curr_size );
                 if ( size == 0 )
                 {
                         size = 1024;
                 }
                 Dbg_hexdump( logLevel, getPayload(), size );
         }
         SPI_LOG_PLAIN( logLevel, "--------------------------------------------------\n" );
 }
void BasebandSPICommandVersion2::dumpHeader (int logLevel) const inline private
Definition at line 267 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::SPIHeader::credits, BasebandSPICommandVersion2::SPIHeader::curr_size, Dbg_hexdump, BasebandSPICommandVersion2::SPIHeader::dcd, BasebandSPICommandVersion2::SPIHeader::dsr_dtr, BasebandSPICommandVersion2::SPIHeader::ext_more, getHeader(), BasebandSPICommandVersion2::SPIHeader::ri, BasebandSPICommandVersion2::SPIHeader::rx_err, and SPI_LOG_PLAIN.
Referenced by dumpFrameInternal(), and getDebugName().
 {
         Dbg_hexdump(logLevel, getHeader(), sizeof(struct SPIHeader));
         SPIHeader * header = getHeader();
         SPI_LOG_PLAIN( logLevel, "\tcurr_size: %p\tcredits: %p\n", header->curr_size, header->credits );
         SPI_LOG_PLAIN( logLevel, "\text_more: %p\trx_err: %p\tri: %p\n", header->ext_more, header->rx_err, header->ri );
         SPI_LOG_PLAIN( logLevel, "\tdcd: %p\tdsr_dtr: %p\n", header->dcd, header->dsr_dtr );
 }
void BasebandSPICommandVersion2::finalize (IOByteCount framePayloadSize, IOByteCount frameSize, UInt32 creditsGranted) inline
Definition at line 158 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::SPIHeader::credits, BasebandSPICommandVersion2::SPIHeader::curr_size, BasebandSPICommand::fMemoryDescriptor, fWriteOffset, getHeader(), getPayload(), and BasebandSPICommand::setFinalized().
Referenced by BasebandSPIIFXProtocolVersion2::prepareTransferIfNeeded().
 {
         SPIHeader * header = getHeader();
         // set our size fields
         header->curr_size = fWriteOffset;
         header->credits = grantedCredits;
 #if 0
         if ( fWriteOffset == 0 )
         {
                 UInt8 * p = getPayload();
                 UInt32 remaining = frameSize - fWriteOffset - sizeof( SPIHeader );
                 for ( UInt32 i = 0; i < remaining; i++ )
                 {
                         switch ( i & 0x3 )
{
                         case 0:
                                 p[i] = 0x00;
                                 break;
                         case 1:
                                 p[i] = 0x01;
                                 break;
                         case 2:
                                 p[i] = 0x01;
                                 break;
                         case 3:
                         default:
                                 p[i] = 0x03;
                                 break;
                         }
                 }
         }
 #endif
         // store the data from cache to memory
         fMemoryDescriptor->performOperation( kIOMemoryIncoherentIOStore, 0, frameSize );
         // mark this as finalized
         setFinalized();
 }
virtual const char* BasebandSPICommandVersion2::getDebugName (void) const inline virtual
Implements BasebandSPICommand.
Definition at line 93 of file BasebandSPIIFXProtocolVersion2.cpp.
References dumpFrameInternal(), dumpHeader(), and getDebugNameStatic().
         {
                 return getDebugNameStatic();
         };
static const char* BasebandSPICommandVersion2::getDebugNameStatic (void) inline static
Definition at line 88 of file BasebandSPIIFXProtocolVersion2.cpp.
Referenced by getDebugName().
         {
                 return "BasebandSPICommandVersion2";
         };
UInt32 BasebandSPICommandVersion2::getGrantedCredits (void) const inline
Definition at line 82 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::SPIHeader::credits, and getHeader().
Referenced by BasebandSPIIFXProtocolVersion2::handleTransferComplete().
         {
                 return getHeader()->credits;
         }
SPIHeader* BasebandSPICommandVersion2::getHeader (void) const inline private
Definition at line 104 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommand::fBuffer.
Referenced by assertCreditReset(), assertMoreToTransfer(), clearHeader(), dumpFrameInternal(), dumpHeader(), finalize(), getGrantedCredits(), getPayloadLength(), indicatesMoreToTransfer(), and indicatesRxError().
         {
                 return (SPIHeader *)fBuffer;
         }
UInt8* BasebandSPICommandVersion2::getPayload (void) const inline private
Definition at line 109 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommand::fBuffer.
Referenced by dumpFrameInternal(), finalize(), and writeData().
         {
                 return fBuffer + sizeof( SPIHeader );
         };
IOByteCount BasebandSPICommandVersion2::getPayloadLength (void) const inline
Definition at line 77 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::SPIHeader::curr_size, and getHeader().
Referenced by BasebandSPIIFXProtocolVersion2::handleTransferComplete().
         {
                 return getHeader()->curr_size;
         }
bool BasebandSPICommandVersion2::indicatesMoreToTransfer (void) const inline
Definition at line 62 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::SPIHeader::ext_more, and getHeader().
Referenced by BasebandSPIIFXProtocolVersion2::handleTransferComplete().
         {
                 return getHeader()->ext_more;
         }
bool BasebandSPICommandVersion2::indicatesRxError (void) const inline
Definition at line 72 of file BasebandSPIIFXProtocolVersion2.cpp.
References getHeader(), and BasebandSPICommandVersion2::SPIHeader::rx_err.
Referenced by BasebandSPIIFXProtocolVersion2::handleTransferComplete().
         {
                 return getHeader()->rx_err;
         };
IOReturn BasebandSPICommandVersion2::init (IODirection direction) protected virtual
Reimplemented from BasebandSPICommand.
Definition at line 138 of file BasebandSPIIFXProtocolVersion2.cpp.
References fWriteOffset, and BasebandSPICommand::init().
Referenced by create().
 {
         IOReturn ret = BasebandSPICommand::init( direction );
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         fWriteOffset = 0;
         return kIOReturnSuccess;
 }
BasebandSPICommandVersion2::OSDeclareDefaultStructors (BasebandSPICommandVersion2) private
void BasebandSPICommandVersion2::reset (void) virtual
Implements BasebandSPICommand.
Definition at line 152 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommand::clearFinalized(), and fWriteOffset.
 {
         fWriteOffset = 0;
         clearFinalized();
 }
IOByteCount BasebandSPICommandVersion2::writeData (UInt8 * source, IOByteCount amount, IOByteCount dataSize) virtual
Writes some data into this command
Parameters
source The buffer representing the source of the data to write
amount The amount of data to write from the buffer
dataSize The maximum data that can be written to this command (in total, including what's already written)
Returns
the amount written
Implements BasebandSPICommand.
Definition at line 206 of file BasebandSPIIFXProtocolVersion2.cpp.
References fWriteOffset, and getPayload().
 {
         IOByteCount remaining = dataSize - fWriteOffset;
         // if we have less room than allows, then only write for how much room we have
         if ( remaining < amount )
         {
                 amount = remaining;
         }
         // copy the data over
         memcpy( getPayload() + fWriteOffset, source, amount );
         // increase the write offset
         fWriteOffset += amount;
          return amount;
 }
Friends And Related Function Documentation
friend class BasebandSPICommand friend
Definition at line 15 of file BasebandSPIIFXProtocolVersion2.cpp.
friend class BasebandSPILogger friend
Definition at line 14 of file BasebandSPIIFXProtocolVersion2.cpp.
Member Data Documentation
IOByteCount BasebandSPICommandVersion2::fWriteOffset private
Definition at line 112 of file BasebandSPIIFXProtocolVersion2.cpp.
Referenced by finalize(), init(), reset(), and writeData().
const unsigned BasebandSPICommandVersion2::kSPIHeaderCreditBits = 12 static
Definition at line 19 of file BasebandSPIIFXProtocolVersion2.cpp.
const unsigned BasebandSPICommandVersion2::kSPIHeaderDataSizeBits = 12 static
Definition at line 18 of file BasebandSPIIFXProtocolVersion2.cpp.
const unsigned BasebandSPICommandVersion2::kSPIHeaderMaxDataSize = ((1UL << kSPIHeaderDataSizeBits) - 1) static
Definition at line 20 of file BasebandSPIIFXProtocolVersion2.cpp.
Referenced by dumpFrameInternal(), and BasebandSPIIFXProtocolVersion2::handleTransferComplete().
The documentation for this class was generated from the following file:
/BasebandSPI/BasebandSPIIFXProtocolVersion2.cpp