BasebandSPIIFXProtocolVersion2 Class Reference
BasebandSPIIFXProtocolVersion2 Class Reference
#include <BasebandSPIIFXProtocolVersion2.h>
Inherits BasebandSPIIFXProtocol.
Public Member Functions
virtual IOReturn activate (void)
virtual IOReturn enterLowPower (void)
virtual IOReturn exitLowPower (void)
virtual IOReturn handleCancelledRxCommand (IODMACommand *command)
virtual IOReturn handleCancelledTxCommand (IODMACommand *command)
virtual IOReturn handleTransferCancelled (void)
virtual IOReturn handleTransferComplete (IODMACommand *receivedCommand, IODMACommand *sendCommand)
virtual IOReturn predeactivate (void)
virtual IOReturn unregisterAllRxBuffers (void)
Public Member Functions inherited from BasebandSPIIFXProtocol
virtual BasebandSPIProtocolSnapshot * getSnapshot (void) const
virtual bool isSRDYStateHigh (void)
Public Member Functions inherited from BasebandSPIProtocol
IOReturn copyTxBuffer (UInt8 *source, IOByteCount length, IOByteCount *remaining, bool transmitNow)
virtual IOReturn deactivate (void)
IOByteCount getFramePayloadSize (void) const
IOByteCount getFrameSize (void) const
IOByteCount getMaxRxBufferCount (void) const
IOReturn registerRxBuffer (IOMemoryDescriptor *md, UInt8 *virtualAddress, void *cookie)
Protected Member Functions
virtual BasebandSPICommand * allocateRxCommand (void) const
virtual BasebandSPICommand * allocateTxCommand (void) const
virtual void free (void)
virtual IOByteCount getHeaderAndFooterSize (void) const
virtual IOInterruptEventAction getSRDYAction (void) const
virtual IOFilterInterruptAction getSRDYFilterAction (void) const
virtual bool init (BasebandSPIController *controller, BasebandSPIDevice *device)
virtual void prepareTransferIfNeeded (UInt32 prepareFlags)
Protected Member Functions inherited from BasebandSPIIFXProtocol
bool canHandleSRDY (void) const
void clearSRDYMissCount (void)
virtual IOReturn createEventSources (void)
virtual IOReturn createFunctions (void)
void handleSRDYTimeoutAction (IOTimerEventSource *es)
void lowerMRDY (void)
void raiseMRDY (void)
virtual IOReturn releaseEventSources (void)
virtual IOReturn releaseFunctions (void)
void setMRDY (UInt32 value)
void startSRDYTimeoutTimer (void)
void stopSRDYTimeoutTimer (void)
Protected Member Functions inherited from BasebandSPIProtocol
IOReturn addEventSource (IOEventSource **es, const char *name)
void addRxFreeCommand (BasebandSPICommand *command)
void addRxUnusedCommand (BasebandSPICommand *command)
void addTxUnusedCommand (BasebandSPICommand *command)
UInt32 getNumRxUnusedCommands (void) const
UInt32 getNumTxUnusedCommands (void) const
unsigned getRemainingTimeLeftMicroSec (const uint64_t end, const uint64_t start, unsigned differenceMicroseconds)
BasebandSPICommand * getRxFreeCommand (void)
BasebandSPICommand * getRxUnusedCommand (void)
void getTime (uint64_t *time) const
BasebandSPICommand * getTxPendingCommand (void) const
BasebandSPICommand * getTxUnusedCommand (void)
bool getUInt32PropertyFromController (const char *name, UInt32 *device)
IOWorkLoop * getWorkLoop (void) const
Private Types
enum StateFlags { kFlagMasterMoreAsserted = 1UL << 1, kFlagMasterCreditReset = 1UL << 2, kFlagSlaveMoreAsserted = 1UL << 17 }
enum TransferFlags { kFlagTxActivated = 1UL << 0, kFlagRxActivated = 1UL << 1, kFlagActive = 1UL << 2, kFlagMissedSRDY = 1UL << 3 }
Private Member Functions
BasebandSPICommand * allocateCommand (IODirection direction) const
virtual const char * getDebugName (void) const
bool handleSRDY (void)
bool handleSRDYFilterInterruptAction (IOFilterInterruptEventSource *filterES)
void handleSRDYInterruptAction (IOInterruptEventSource *es, int count)
OSDeclareDefaultStructors (BasebandSPIIFXProtocolVersion2)
Private Attributes
UInt32 fCurrentRxCredits
UInt32 fCurrentTxCredits
UInt16 fLastStateFlags
UInt32 fSlaveRxCredits
UInt16 fStateFlags
volatile UInt32 fTransferFlags
Static Private Attributes
static const UInt16 kMasterStateFlagMask = 0xFF
static const UInt32 kRxCreditDifferenceThreshold = 8
static const UInt16 kSlaveStateFlagMask = 0xFF << 8
Friends
class BasebandSPIProtocol
Additional Inherited Members
Static Public Member Functions inherited from BasebandSPIProtocol
static BasebandSPIProtocol * create (BasebandSPIController *controller, BasebandSPIDevice *device)
Protected Types inherited from BasebandSPIProtocol
enum PrepareFlags { kPrepareInitiate = 1UL << 0, kPrepareStart = 1UL << 1, kPrepareRxRegistered = 1UL << 2 }
Static Protected Member Functions inherited from BasebandSPIProtocol
static const char * getDebugNameStatic (void)
static bool getUInt32PropertyWithProvider (IOService *provider, const char *name, UInt32 *device)
Protected Attributes inherited from BasebandSPIIFXProtocol
AppleARMFunction * fMRDYFunction
uint64_t fMRDYModificationTime
UInt32 fMRDYState
IOInterruptEventSource * fSRDYEventSource
AppleARMFunction * fSRDYFunction
IOTimerEventSource * fSRDYTimeoutEventSource
Protected Attributes inherited from BasebandSPIProtocol
BasebandSPICommandQueue * fCommandQueue
BasebandSPIController * fController
BasebandSPIDevice * fDevice
IOByteCount fFramePayloadSize
IOByteCount fFrameSize
bool fInLowPower
UInt32 fRxAvailableBufferCount
UInt32 fRxBufferCount
IOCommandPool * fRxDMACommandPool
IOCommandPool * fRxFreeCommandPool
UInt32 fTxAvailableBufferCount
UInt32 fTxBufferCount
IOCommandPool * fTxDMACommandPool
Static Protected Attributes inherited from BasebandSPIIFXProtocol
static const UInt32 kSRDYTimeoutInterval = 2*1000
Detailed Description
Definition at line 9 of file BasebandSPIIFXProtocolVersion2.h.
Member Enumeration Documentation
enum BasebandSPIIFXProtocolVersion2::StateFlags private
Enumerator
kFlagMasterMoreAsserted
kFlagMasterCreditReset
kFlagSlaveMoreAsserted
Definition at line 24 of file BasebandSPIIFXProtocolVersion2.h.
         {
                 kFlagMasterMoreAsserted                         = 1UL << 1,
                 kFlagMasterCreditReset                          = 1UL << 2,
                 kFlagSlaveMoreAsserted                          = 1UL << 17
         } StateFlags;
enum BasebandSPIIFXProtocolVersion2::TransferFlags private
Enumerator
kFlagTxActivated
kFlagRxActivated
kFlagActive
kFlagMissedSRDY
Definition at line 16 of file BasebandSPIIFXProtocolVersion2.h.
         {
                 kFlagTxActivated        = 1UL << 0,
                 kFlagRxActivated        = 1UL << 1,
                 kFlagActive                     = 1UL << 2,
                 kFlagMissedSRDY         = 1UL << 3
         } TransferFlags;
Member Function Documentation
IOReturn BasebandSPIIFXProtocolVersion2::activate (void) virtual
Reimplemented from BasebandSPIIFXProtocol.
Definition at line 323 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_INFO, SPI_ASSERT, SPI_ASSERT_SUCCESS, and SPI_TRACE.
Referenced by getDebugName().
 {
         SPI_TRACE( DEBUG_INFO );
         fController->beginBlockInterrupt();
         IOReturn ret = super::activate();
         SPI_ASSERT_SUCCESS( ret );
         fStateFlags             = kFlagMasterCreditReset;
         fLastStateFlags = kFlagMasterCreditReset;
         SPI_ASSERT( fTransferFlags, ==, 0 );
         fController->endBlockInterrupt();
         return kIOReturnSuccess;
 }
BasebandSPICommand * BasebandSPIIFXProtocolVersion2::allocateCommand (IODirection direction) const private
Definition at line 373 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::create().
Referenced by getDebugName().
 {
         return BasebandSPICommandVersion2::create( direction );
 }
BasebandSPICommand * BasebandSPIIFXProtocolVersion2::allocateRxCommand (void) const protected virtual
Implements BasebandSPIProtocol.
Definition at line 398 of file BasebandSPIIFXProtocolVersion2.cpp.
Referenced by getDebugName().
 {
         return allocateCommand( kIODirectionIn );
 }
BasebandSPICommand * BasebandSPIIFXProtocolVersion2::allocateTxCommand (void) const protected virtual
Implements BasebandSPIProtocol.
Definition at line 378 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommand::setMemoryDescriptor().
Referenced by getDebugName().
 {
         BasebandSPICommand * command = allocateCommand( kIODirectionOut );
         if ( command )
         {
                 IOBufferMemoryDescriptor * bmd = IOBufferMemoryDescriptor::withOptions( kIOMapDefaultCache, getFrameSize(), 4 );
                 if ( bmd )
                 {
                         command->setMemoryDescriptor( bmd, (UInt8 *)bmd->getBytesNoCopy(), NULL );
                 }
                 else
                 {
                         command->release();
                         command = NULL;
                 }
         }
         return command;
 }
IOReturn BasebandSPIIFXProtocolVersion2::enterLowPower (void) virtual
Reimplemented from BasebandSPIProtocol.
Definition at line 988 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_INFO, SPI_ASSERT_SUCCESS, and SPI_TRACE.
Referenced by getDebugName().
 {
         SPI_TRACE( DEBUG_INFO );
         IOReturn ret = super::enterLowPower();
         SPI_ASSERT_SUCCESS( ret );
         fController->beginBlockInterrupt();
         fTransferFlags &= ~ ( kFlagTxActivated | kFlagRxActivated );
         fController->endBlockInterrupt();
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIIFXProtocolVersion2::exitLowPower (void) virtual
Reimplemented from BasebandSPIIFXProtocol.
Definition at line 1004 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_INFO, SPI_ASSERT_SUCCESS, and SPI_TRACE.
Referenced by getDebugName().
 {
         SPI_TRACE( DEBUG_INFO );
         IOReturn ret = super::exitLowPower();
         SPI_ASSERT_SUCCESS( ret );
         return kIOReturnSuccess;
 }
void BasebandSPIIFXProtocolVersion2::free (void) protected virtual
Reimplemented from BasebandSPIIFXProtocol.
Definition at line 306 of file BasebandSPIIFXProtocolVersion2.cpp.
Referenced by getDebugName().
 {
         super::free();
 }
virtual const char* BasebandSPIIFXProtocolVersion2::getDebugName (void) const inline private virtual
Implements BasebandSPIProtocol.
Definition at line 37 of file BasebandSPIIFXProtocolVersion2.h.
References activate(), allocateCommand(), allocateRxCommand(), allocateTxCommand(), enterLowPower(), exitLowPower(), free(), getHeaderAndFooterSize(), getSRDYAction(), getSRDYFilterAction(), handleCancelledRxCommand(), handleCancelledTxCommand(), handleSRDY(), handleSRDYFilterInterruptAction(), handleSRDYInterruptAction(), handleTransferCancelled(), handleTransferComplete(), init(), predeactivate(), prepareTransferIfNeeded(), and unregisterAllRxBuffers().
         {
                 return "BasebandSPIIFXProtocolVersion2";
         };
IOByteCount BasebandSPIIFXProtocolVersion2::getHeaderAndFooterSize (void) const protected virtual
Implements BasebandSPIProtocol.
Definition at line 474 of file BasebandSPIIFXProtocolVersion2.cpp.
Referenced by getDebugName().
 {
         return sizeof( BasebandSPICommandVersion2::SPIHeader );
 }
IOInterruptEventAction BasebandSPIIFXProtocolVersion2::getSRDYAction (void) const protected virtual
Implements BasebandSPIIFXProtocol.
Definition at line 311 of file BasebandSPIIFXProtocolVersion2.cpp.
References handleSRDYInterruptAction().
Referenced by getDebugName().
 {
         return OSMemberFunctionCast(IOInterruptEventAction, this, &BasebandSPIIFXProtocolVersion2::handleSRDYInterruptAction);
 }
IOFilterInterruptAction BasebandSPIIFXProtocolVersion2::getSRDYFilterAction (void) const protected virtual
Implements BasebandSPIIFXProtocol.
Definition at line 317 of file BasebandSPIIFXProtocolVersion2.cpp.
References handleSRDYFilterInterruptAction().
Referenced by getDebugName().
 {
         return OSMemberFunctionCast( IOFilterInterruptAction, this, &BasebandSPIIFXProtocolVersion2::handleSRDYFilterInterruptAction );
 }
IOReturn BasebandSPIIFXProtocolVersion2::handleCancelledRxCommand (IODMACommand * command) virtual
Implements BasebandSPIProtocol.
Definition at line 970 of file BasebandSPIIFXProtocolVersion2.cpp.
References SPI_ASSERT.
Referenced by getDebugName().
 {
         SPI_ASSERT( fRxAvailableBufferCount, <, fRxBufferCount );
         BasebandSPICommandVersion2 * c = OSDynamicCast( BasebandSPICommandVersion2, command );
         SPI_ASSERT( c, !=, NULL );
         addRxUnusedCommand( c );
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIIFXProtocolVersion2::handleCancelledTxCommand (IODMACommand * command) virtual
Implements BasebandSPIProtocol.
Definition at line 979 of file BasebandSPIIFXProtocolVersion2.cpp.
References SPI_ASSERT.
Referenced by getDebugName().
 {
         SPI_ASSERT( fTxAvailableBufferCount, <, fTxBufferCount );
         BasebandSPICommandVersion2 * c = OSDynamicCast( BasebandSPICommandVersion2, command );
         SPI_ASSERT( c, !=, NULL );
         addTxUnusedCommand( c );
         return kIOReturnSuccess;
 }
bool BasebandSPIIFXProtocolVersion2::handleSRDY (void) private
Definition at line 441 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_SPEW, BasebandSPILogger::logGeneral(), SPI_ASSERT_SUCCESS, and SPI_LOG.
Referenced by getDebugName().
 {
         bool allowed = fController->intendToInterrupt();
         BasebandSPILogger::logGeneral( "SRDYH", 0 );
         if ( !allowed )
         {
                 return false;
         }
         if ( fController->canStartTransfer() )
         {
                 BasebandSPILogger::logGeneral( "SRDYH", 1 );
                 fTransferFlags |= kFlagActive;
                 IOReturn ret = fController->startTransfer();
                 SPI_ASSERT_SUCCESS( ret );
                 return false;
         }
         else
         {
                 BasebandSPILogger::logGeneral( "SRDYH", 2 );
                 SPI_LOG( DEBUG_SPEW, "Deferring SRDY\n" );
                 if ( fTransferFlags & kFlagActive )
                 {
                         fTransferFlags |= kFlagMissedSRDY;
                 }
                 return true;
         }
 }
bool BasebandSPIIFXProtocolVersion2::handleSRDYFilterInterruptAction (IOFilterInterruptEventSource * filterES) private
Definition at line 404 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPILogger::logSRDYAsserted().
Referenced by getDebugName(), and getSRDYFilterAction().
 {
         (void)es;
 #if SPI_USE_REAL_ISR_FOR_DEBUG
         BasebandSPILogger::logSRDYAsserted();
         return true;
 #else
         return handleSRDY();
 #endif
 }
void BasebandSPIIFXProtocolVersion2::handleSRDYInterruptAction (IOInterruptEventSource * es, int count) private virtual
Implements BasebandSPIIFXProtocol.
Definition at line 417 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_SPEW, BasebandSPILogger::logGeneral(), and SPI_TRACE.
Referenced by getDebugName(), and getSRDYAction().
 {
         (void)es;
         (void)count;
         SPI_TRACE( DEBUG_SPEW );
 #if !SPI_USE_REAL_ISR
         bool powerUp = handleSRDY();
         if ( !powerUp )
         {
                 return;
         }
 #endif
         if ( !canHandleSRDY() || fController->isEnteringLowPower() )
         {
                 BasebandSPILogger::logGeneral( "SRDYI", 1 );
                 return;
         }
         prepareTransferIfNeeded( kPrepareInitiate | kPrepareStart );
 }
IOReturn BasebandSPIIFXProtocolVersion2::handleTransferCancelled (void) virtual
Implements BasebandSPIProtocol.
Definition at line 766 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_SPEW, and SPI_TRACE.
Referenced by getDebugName().
 {
         SPI_TRACE( DEBUG_SPEW );
         lowerMRDY();
         stopSRDYTimeoutTimer();
         fController->beginBlockInterrupt();
         fController->unconfigure();
         fController->endBlockInterrupt();
         // We need to clean up the transfer flags as well
         // Commands are already placed back to the queue
         fTransferFlags = 0;
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIIFXProtocolVersion2::handleTransferComplete (IODMACommand * receivedCommand, IODMACommand * sendCommand) virtual
Implements BasebandSPIProtocol.
Definition at line 785 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommand::clearMemoryDescriptor(), DEBUG_CRITICAL, DEBUG_SPEW, BasebandSPICommand::dumpFrame(), BasebandSPICommand::getCookie(), BasebandSPICommandVersion2::getGrantedCredits(), BasebandSPICommandVersion2::getPayloadLength(), BasebandSPICommandVersion2::indicatesMoreToTransfer(), BasebandSPICommandVersion2::indicatesRxError(), kBasebandSPIReturnProtocolError, kBasebandSPIReturnRxReady, kBasebandSPIReturnTxReady, BasebandSPICommandVersion2::kSPIHeaderMaxDataSize, BasebandSPILogger::logFrameReceived(), BasebandSPILogger::logGeneral(), BasebandSPILogger::logReceiveCallbackBegin(), BasebandSPILogger::logReceiveCallbackEnd(), SPI_ASSERT, SPI_LOG, and SPI_TRACE.
Referenced by getDebugName().
 {
         SPI_TRACE( DEBUG_SPEW );
         BasebandSPICommandVersion2 * command;
         SPI_LOG( DEBUG_SPEW, "Transfer flags = %p\n", fTransferFlags );
         // if we didn't indicate MORE last time, lower MRDY
         if ( !( fLastStateFlags & kFlagMasterMoreAsserted ) )
         {
                 lowerMRDY();
         }
         stopSRDYTimeoutTimer();
         fController->beginBlockInterrupt();
         fController->unconfigure();
         bool missed = fController->endBlockInterrupt();
         UInt32 prepareFlags;
         // if we missed an SRDY while we blocked the interupt
         // or we missed it because our transfer was active, mark that we
         // want to initiate and start a transfer
         if ( missed || ( fTransferFlags & kFlagMissedSRDY )  )
         {
                 prepareFlags = kPrepareInitiate | kPrepareStart;
         }
         else
         {
                 prepareFlags = 0;
         }
         fTransferFlags = 0;
         UInt32 callbackFlags = 0;
         if ( sendCommand )
         {
                 // only go in here if we sent a valid frame (either with real payload or header-only)
                 command = OSDynamicCast( BasebandSPICommandVersion2, sendCommand );
 #if SPI_PEDANTIC_ASSERT
                 SPI_ASSERT( command, !=, NULL );
 #endif
                 command->dumpFrame( DEBUG_SPEW );
                 // If we were low on Tx commands, mark that we want to notify our
                 // client that a Tx buffer is now free
                 if ( getNumTxUnusedCommands() == 1 )
                 {
                         callbackFlags |= kBasebandSPIReturnTxReady;
                 }
                 // <rdar://problem/8730644> AP might initiate Tx transfers unnecessarily
                 /*
                 if ( fCommandQueue->getSize() )
                 {
                         prepareFlags |= kPrepareInitiate;
                 }
                 */
                 addTxUnusedCommand( command );
         }
         {
                 // we always go in here since we always prepare for an Rx
                 command = OSDynamicCast( BasebandSPICommandVersion2, receivedCommand );
                 SPI_ASSERT( command, !=, NULL );
                 command->dumpFrame( DEBUG_SPEW );
                 IOByteCount payloadLength = command->getPayloadLength();
                 if ( payloadLength > getFramePayloadSize() )
                 {
                         if ( payloadLength < BasebandSPICommandVersion2::kSPIHeaderMaxDataSize )
{
                                 // the payload length is greater than what we expected, but the field isn't all 1's (in binary)
                                 // so dump the frame as we shouldn't get here
                                 SPI_LOG( DEBUG_CRITICAL, "Recieved frame of payload size %u, frame size %u\n",
                                         payloadLength, getFramePayloadSize() );
                                 command->dumpFrame( DEBUG_CRITICAL );
                         }
                         else
{
                                 // the frame was all 1's (in binary) and thus the slave had nothing to send us
                         }
                         addRxUnusedCommand( command );
                         // ramp up the controller agin
                         prepareTransferIfNeeded( prepareFlags );
                 }
                 else
                 {
                         // add the number of credits we have
                         fCurrentTxCredits += command->getGrantedCredits();
 #if SPI_SRDY_DEBUG
                         BasebandSPILogger::logGeneral( "CRDGTx", (command->getGrantedCredits() << 16 ) | fCurrentTxCredits, isSRDYStateHigh() );
 #else
                         BasebandSPILogger::logGeneral( "CRDGTx", (command->getGrantedCredits() << 16 ) | fCurrentTxCredits );
 #endif
                         // set our state to only the master flags as we be reading in the new slave flags
                         fStateFlags = fStateFlags & kMasterStateFlagMask;
                         // go through what we received, set flags in our state accordingly
                         if ( command->indicatesMoreToTransfer() )
{
 #if SPI_SRDY_DEBUG
                                 BasebandSPILogger::logGeneral( "SMORE", 1, isSRDYStateHigh() );
 #else
                                 BasebandSPILogger::logGeneral( "SMORE", 1 );
 #endif
                                 fStateFlags |= kFlagSlaveMoreAsserted;
                                 prepareFlags |= kPrepareInitiate | kPrepareStart;
                         }
                         // if there is an error reported, throw up an error
                         if ( command->indicatesRxError() )
{
                                 fController->reportError( kBasebandSPIReturnProtocolError, "Rx Error" );
                         }
                         SPI_LOG( DEBUG_SPEW, "State flags %p\n", fStateFlags );
                         // ramp up the controller again
                         // we do this here because if there was another pending SRDY, it can transfer
                         // while the client processes the frame we received
                         prepareTransferIfNeeded( prepareFlags );
                         if ( payloadLength )
{
 #if SPI_PEDANTIC_ASSERT
                                 SPI_ASSERT( fSlaveRxCredits, >, 0 );
 #endif
                                 // we received real data, so the baseband consumed a credit
                                 fSlaveRxCredits--;
                                 fCurrentRxCredits--;
 #if SPI_SRDY_DEBUG
                                 BasebandSPILogger::logGeneral( "CRDDRx", ( fSlaveRxCredits << 16 ) | fCurrentRxCredits, isSRDYStateHigh() );
 #else
                                 BasebandSPILogger::logGeneral( "CRDDRx", ( fSlaveRxCredits << 16 ) | fCurrentRxCredits );
 #endif
                                 SPI_LOG( DEBUG_SPEW, "Slave consumed %u credits\n", fCurrentRxCredits );
                                 // if there was an actual payload, mark that this is a real Rx
                                 callbackFlags |= kBasebandSPIReturnRxReady;
                                 BasebandSPILogger::logFrameReceived( payloadLength + sizeof( BasebandSPICommandVersion2::SPIHeader ), command );
                                 // clear the memory descriptor of the command and put it back in the free pool
                                 command->clearMemoryDescriptor();
                                 addRxFreeCommand( command );
                                 // do the actual callback
                                 BasebandSPILogger::logReceiveCallbackBegin();
                                 fDevice->invokeCompletionCallback( command->getCookie(), callbackFlags,
                                         sizeof( BasebandSPICommandVersion2::SPIHeader ), payloadLength );
                                 BasebandSPILogger::logReceiveCallbackEnd();
                         }
                         else
{
                                 // this was a header-only frame, recycle the command and use it for another receive
                                 BasebandSPILogger::logFrameReceived( sizeof( BasebandSPICommandVersion2::SPIHeader ), command );
                                 addRxUnusedCommand( command );
                         }
                 }
         }
         return kIOReturnSuccess;
 }
bool BasebandSPIIFXProtocolVersion2::init (BasebandSPIController * controller, BasebandSPIDevice * device) protected virtual
Reimplemented from BasebandSPIIFXProtocol.
Definition at line 285 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_INFO, and SPI_TRACE.
Referenced by getDebugName().
 {
         SPI_TRACE( DEBUG_INFO );
         fTransferFlags  = 0;
         fCurrentRxCredits       = 0;
         fSlaveRxCredits         = fCurrentRxCredits;
         fCurrentTxCredits       = 0;
         bool ret = super::init( controller, device );
         if ( !ret )
         {
                 return ret;
         }
         return true;
 }
BasebandSPIIFXProtocolVersion2::OSDeclareDefaultStructors (BasebandSPIIFXProtocolVersion2) private
IOReturn BasebandSPIIFXProtocolVersion2::predeactivate (void) virtual
Reimplemented from BasebandSPIIFXProtocol.
Definition at line 342 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_INFO, SPI_ASSERT_SUCCESS, and SPI_TRACE.
Referenced by getDebugName().
 {
         SPI_TRACE( DEBUG_INFO );
         fController->beginBlockInterrupt();
         fTransferFlags          = 0;
         fCurrentRxCredits       = 0;
         IOReturn ret = super::predeactivate();
         SPI_ASSERT_SUCCESS( ret );
         fController->endBlockInterrupt();
         return kIOReturnSuccess;
 }
void BasebandSPIIFXProtocolVersion2::prepareTransferIfNeeded (UInt32 prepareFlags) protected virtual
Implements BasebandSPIProtocol.
Definition at line 479 of file BasebandSPIIFXProtocolVersion2.cpp.
References BasebandSPICommandVersion2::assertCreditReset(), BasebandSPICommandVersion2::assertMoreToTransfer(), BasebandSPICommandVersion2::clearHeader(), DEBUG_SPEW, BasebandSPICommandVersion2::finalize(), BasebandSPILogger::logFrameSent(), BasebandSPILogger::logGeneral(), SPI_ASSERT, SPI_ASSERT_SUCCESS, SPI_LOG, and SPI_TRACE.
Referenced by getDebugName().
 {
         SPI_TRACE( DEBUG_SPEW );
         fController->beginBlockInterrupt();
         UInt32 currentTransferFlags = fTransferFlags;
         SPI_LOG( DEBUG_SPEW, "prepare = %p, transferFlags = %p, state flags = %p\n", prepareFlags, currentTransferFlags, fStateFlags );
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "STI", currentTransferFlags, isSRDYStateHigh() );
 #else
         BasebandSPILogger::logGeneral( "STI", currentTransferFlags );
 #endif
         if ( prepareFlags & kPrepareRxRegistered )
         {
                 // if a new buffer was registered, then increment the credit count
                 fCurrentRxCredits++;
                 SPI_LOG( DEBUG_SPEW, "Increased credits to %u\n", fCurrentRxCredits );
 #if SPI_SRDY_DEBUG
                 BasebandSPILogger::logGeneral( "CRDIRx", ( fSlaveRxCredits << 16 ) | fCurrentRxCredits, isSRDYStateHigh() );
 #else
                 BasebandSPILogger::logGeneral( "CRDIRx", ( fSlaveRxCredits << 16 ) | fCurrentRxCredits );
 #endif
         }
         if ( !( currentTransferFlags & kFlagActive ) )
         {
                 // Only start touching our state if a transfer is not in flight
                 bool changedFlags = false;
                 BasebandSPICommandVersion2 * txCommand = NULL;
 #if SPI_SRDY_DEBUG
                 BasebandSPILogger::logGeneral( "STI0", 0, isSRDYStateHigh() );
 #else
                 BasebandSPILogger::logGeneral( "STI0", 0 );
 #endif
                 UInt32 creditsGranted;
                 if ( !( fTransferFlags & kFlagTxActivated ) )
                 {
                         // Don't touch Tx if it's already set up
                         BasebandSPICommandVersion2 * command = NULL;
                         SPI_LOG( DEBUG_SPEW, "Tx Queue Size %u\n", fCommandQueue->getSize() );
                         SPI_LOG( DEBUG_SPEW, "Slave credits %u vs current %u\n", fSlaveRxCredits, fCurrentRxCredits );
                         creditsGranted  = fCurrentRxCredits - fSlaveRxCredits;
                         UInt32 minimumDifference = MIN( kRxCreditDifferenceThreshold, fSlaveRxCredits );
                         // Do not send out a credit update if Mux is in process of entering low power
                         if ( ( creditsGranted > minimumDifference ) &&  !( fDevice->isMuxEnteringLowPower() ) )
{
                                 // if the number of credits the baseband thinks we have is
                                 // different from what we really have then we need to notify BB
                                 prepareFlags |= kPrepareInitiate;
                                 changedFlags = true;
                         }
                         if ( fStateFlags & kFlagMasterMoreAsserted )
{
                                 // Clear the MORE flag unconditionally
                                 // and indicate that we want to start a transfer to notify the slave
                                 // In case we have more data to send this flag will be set again below.
                                 // But in case we ran out we should signal the BB that no further frames are expected
                                 fStateFlags &= ~ kFlagMasterMoreAsserted;
                                 prepareFlags |= kPrepareInitiate;
                                 changedFlags = true;
                         }
                         if ( fCommandQueue->isEmpty() )
{
 #if SPI_SRDY_DEBUG
                                 BasebandSPILogger::logGeneral( "STI0", 3, isSRDYStateHigh() );
 #else
                                 BasebandSPILogger::logGeneral( "STI0", 3 );
 #endif
                                 if ( changedFlags )
{
                                         // if we have no real payload to send, but we want to start a transfer anyway
                                         // (to send a header-only frame) then get an empty command
 #if SPI_SRDY_DEBUG
                                         BasebandSPILogger::logGeneral( "STI0", 4, isSRDYStateHigh() );
 #else
                                         BasebandSPILogger::logGeneral( "STI0", 4 );
 #endif
                                         command = OSDynamicCast( BasebandSPICommandVersion2, getTxUnusedCommand() );
                                 }
                         }
                         else
{
                                 if ( fCurrentTxCredits == 0 )
{
                                         // Only get a Unused commands if the flags have changed and we want to initiate a transfer
                                         // kPrepareInitiate is always set when we want to Tx or if we receive a SRDY interrupt
                                         if ( changedFlags && ( prepareFlags & kPrepareInitiate ) ) {
                                                 // if we can't send real data, then we need to send a
                                                 // header-only frame then get an empty command
 #if SPI_SRDY_DEBUG
                                                 BasebandSPILogger::logGeneral( "STI0", 6, isSRDYStateHigh() );
 #else
                                                 BasebandSPILogger::logGeneral( "STI0", 6 );
 #endif
                                                 command = OSDynamicCast( BasebandSPICommandVersion2, getTxUnusedCommand() );
                                         }
                                 }
                                 else
{
                                         if ( fCommandQueue->getSize() > 1 )
{
                                                 // If there is more than command in the queue, then mark the MORE flag
                                                 // and indicate that we want to start a transfer to notify the slave
 #if SPI_SRDY_DEBUG
                                                 BasebandSPILogger::logGeneral( "STI0", 2, isSRDYStateHigh() );
 #else
                                                 BasebandSPILogger::logGeneral( "STI0", 2 );
 #endif
                                                 fStateFlags |= kFlagMasterMoreAsserted;
                                                 changedFlags = true;
                                         }
                                         // otherwise just get the command
                                         BasebandSPICommand * tmp = fCommandQueue->dequeueHead();
                                         command = OSDynamicCast( BasebandSPICommandVersion2, tmp );
 #if SPI_PEDANTIC_ASSERT
                                         SPI_ASSERT( command, !=, NULL );
                                         SPI_ASSERT( fCurrentTxCredits, >, 0 );
 #endif
 #if SPI_SRDY_DEBUG
                                         BasebandSPILogger::logGeneral( "CRDDTx", fCurrentTxCredits, isSRDYStateHigh() );
 #else
                                         BasebandSPILogger::logGeneral( "CRDDTx", fCurrentTxCredits );
 #endif
                                         // This is a real payload, we need to decrement our credit count
                                         fCurrentTxCredits--;
                                         prepareFlags |= kPrepareInitiate;
                                 }
                         }
                         txCommand = command;
                 }
                 BasebandSPICommandVersion2 * rxCommand = NULL;
                 if ( !( currentTransferFlags & kFlagRxActivated ) )
                 {
                         // only start touching Rx if there isn't already one active
                         if ( prepareFlags & kPrepareInitiate )
{
                                 rxCommand = OSDynamicCast( BasebandSPICommandVersion2, getRxUnusedCommand() );
 #if SPI_PEDANTIC_ASSERT
                                 SPI_ASSERT( rxCommand, !=, NULL );
 #endif
 #if SPI_SRDY_DEBUG
                                 BasebandSPILogger::logGeneral( "STIRx", fLastStateFlags, isSRDYStateHigh() );
 #else
                                 BasebandSPILogger::logGeneral( "STIRx", fLastStateFlags );
 #endif
                                 // indicate that Rx is activated in our copy, and set the flag to update the field
                                 currentTransferFlags |= kFlagRxActivated;
                                 // <rdar://problem/8629724> CoreDump generated on 8E89 -- SPI Frame 0xBFFFFFFF uplink [Case Number : 00007223]
                                 if ( txCommand == NULL )
{
                                         txCommand = OSDynamicCast( BasebandSPICommandVersion2, getTxUnusedCommand() );
                                 }
                         }
                 }
                 if ( txCommand )
                 {
                         // we have something to tx (either a real frame or header-only) depending on the code above
                         // clear the header
                         txCommand->clearHeader();
                         // start filling in bits of the header
                         if (  fStateFlags & kFlagMasterMoreAsserted )
{
 #if SPI_SRDY_DEBUG
                                 BasebandSPILogger::logGeneral( "MMORE", 1, isSRDYStateHigh() );
 #else
                                 BasebandSPILogger::logGeneral( "MMORE", 1 );
 #endif
                                 txCommand->assertMoreToTransfer();
                         }
                         if ( fStateFlags & kFlagMasterCreditReset )
{
 #if SPI_SRDY_DEBUG
                                 BasebandSPILogger::logGeneral( "CRDRST", 0, isSRDYStateHigh() );
 #else
                                 BasebandSPILogger::logGeneral( "CRDRST", 0 );
 #endif
                                 fStateFlags &= ~ kFlagMasterCreditReset;
                                 txCommand->assertCreditReset();
                         }
                         fSlaveRxCredits = fCurrentRxCredits;
                         SPI_ASSERT( (SInt32)creditsGranted, >=, 0 );
                         SPI_LOG( DEBUG_SPEW, "Granting credits %u\n", creditsGranted );
 #if SPI_SRDY_DEBUG
                         BasebandSPILogger::logGeneral( "CRDGRx", creditsGranted, isSRDYStateHigh() );
 #else
                         BasebandSPILogger::logGeneral( "CRDGRx", creditsGranted );
 #endif
                         // finalize the command by writing some last minute fields and
                         // flushing the buffer
                         txCommand->finalize( getFramePayloadSize(), getFrameSize(), creditsGranted );
                         BasebandSPILogger::logFrameSent( getFrameSize(), txCommand );
                         // set the last state flags to the current state, this keeps track of
                         // what the slave thinks our state is
                         fLastStateFlags         = fStateFlags;
                         // mark that Tx is active in the local copy
                         currentTransferFlags |= kFlagTxActivated;
 #if SPI_SRDY_DEBUG
                         BasebandSPILogger::logGeneral( "STITx", fLastStateFlags, isSRDYStateHigh() );
 #else
                         BasebandSPILogger::logGeneral( "STITx", fLastStateFlags );
 #endif
                 }
                 if ( rxCommand || txCommand )
                 {
                         // configure the hardware
                         IOReturn ret = fController->configure( rxCommand, txCommand, getFrameSize() );
                         SPI_ASSERT_SUCCESS( ret );
                 }
                 if ( prepareFlags & kPrepareStart )
                 {
                         // if we want to actually start the transfer, start it
                         // this implies the precondition that the slave has already
                         // raised SRDY and we deferred handling it
                         fController->startTransfer();
                         // mark that the transfer is active in our local copy
                         currentTransferFlags    |= kFlagActive;
                 }
                 else if ( prepareFlags & kPrepareInitiate )
                 {
                         // if we want to initiate the transfer, raise MRDY
                         raiseMRDY();
                         startSRDYTimeoutTimer();
                 }
                 // if we touched the flags, copy it over
                 fTransferFlags = currentTransferFlags;
                 SPI_LOG( DEBUG_SPEW, "Current State flags %p\n", fStateFlags );
         }
         bool missed = fController->endBlockInterrupt();
         if ( missed )
         {
                 // if we missed an SRDY while we were blocking it, handle it now
                 handleSRDY();
         }
 }
IOReturn BasebandSPIIFXProtocolVersion2::unregisterAllRxBuffers (void) virtual
Reimplemented from BasebandSPIProtocol.
Definition at line 359 of file BasebandSPIIFXProtocolVersion2.cpp.
References DEBUG_INFO, SPI_ASSERT_SUCCESS, and SPI_TRACE.
Referenced by getDebugName().
 {
         SPI_TRACE( DEBUG_INFO );
         IOReturn ret = super::unregisterAllRxBuffers();
         SPI_ASSERT_SUCCESS( ret );
         fCurrentRxCredits       = 0;
         fSlaveRxCredits         = 0;
         fCurrentTxCredits       = 0;
         return kIOReturnSuccess;
 }
Friends And Related Function Documentation
friend class BasebandSPIProtocol friend
Definition at line 13 of file BasebandSPIIFXProtocolVersion2.h.
Member Data Documentation
UInt32 BasebandSPIIFXProtocolVersion2::fCurrentRxCredits private
Definition at line 90 of file BasebandSPIIFXProtocolVersion2.h.
UInt32 BasebandSPIIFXProtocolVersion2::fCurrentTxCredits private
Definition at line 93 of file BasebandSPIIFXProtocolVersion2.h.
UInt16 BasebandSPIIFXProtocolVersion2::fLastStateFlags private
Definition at line 88 of file BasebandSPIIFXProtocolVersion2.h.
UInt32 BasebandSPIIFXProtocolVersion2::fSlaveRxCredits private
Definition at line 91 of file BasebandSPIIFXProtocolVersion2.h.
UInt16 BasebandSPIIFXProtocolVersion2::fStateFlags private
Definition at line 87 of file BasebandSPIIFXProtocolVersion2.h.
volatile UInt32 BasebandSPIIFXProtocolVersion2::fTransferFlags private
Definition at line 86 of file BasebandSPIIFXProtocolVersion2.h.
const UInt16 BasebandSPIIFXProtocolVersion2::kMasterStateFlagMask = 0xFF static private
Definition at line 31 of file BasebandSPIIFXProtocolVersion2.h.
const UInt32 BasebandSPIIFXProtocolVersion2::kRxCreditDifferenceThreshold = 8 static private
Definition at line 34 of file BasebandSPIIFXProtocolVersion2.h.
const UInt16 BasebandSPIIFXProtocolVersion2::kSlaveStateFlagMask = 0xFF << 8 static private
Definition at line 32 of file BasebandSPIIFXProtocolVersion2.h.
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPIIFXProtocolVersion2.h
/BasebandSPI/BasebandSPIIFXProtocolVersion2.cpp