BasebandSPILogger Class Reference
BasebandSPILogger Class Reference
#include <BasebandSPILogger.h>
Classes
struct LogEntry
Public Member Functions
BasebandSPILogger ()
~BasebandSPILogger ()
Static Public Member Functions
static void clear (void)
static unsigned getDelta (unsigned now, unsigned before)
static void logDMACancel (const char *msg=0)
static void logDMAComplete (const char *msg=0)
static void logDMAError (const char *msg=0)
static void logFrameReceived (int size, BasebandSPICommand *cmd)
static void logFrameSent (int size, BasebandSPICommand *cmd)
static void logGeneral (const char *msg, int arg=0, bool srdy_state=false)
static void logMRDY (int level, const char *msg=0)
static void logReceiveCallbackBegin (const char *msg=0)
static void logReceiveCallbackEnd (const char *msg=0)
static void logSRDY (int level, const char *msg=0)
static void logSRDYAsserted (void)
static bool popLogEntryAsString (char *buffer, unsigned capacity)
static void report (void)
Private Types
enum {
kTypeMRDY, kTypeSRDY, kTypeGeneral, kTypeFrameReceived,
kTypeFrameSent, kTypeReceiveCallback, kTypeSRDYInterrupt, kTypeDMAComplete,
kTypeDMACancel, kTypeDMAError
}
Private Member Functions
void addEntry (unsigned type, int arg, const char *msg, unsigned messageSize, bool state=false)
void clearInternal (void)
LogEntry & getEntry (unsigned offset)
void logDMACancelInternal (const char *msg)
void logDMACompleteInternal (const char *msg)
void logDMAErrorInternal (const char *msg)
void logFrame (unsigned type, int size, BasebandSPICommand *cmd)
void logFrameReceivedInternal (int size, BasebandSPICommand *cmd)
void logFrameSentInternal (int size, BasebandSPICommand *cmd)
void logGeneralInternal (const char *msg, int arg, bool state)
void logMRDYInternal (int level, const char *msg)
void logReceiveCallbackBeginInternal (const char *msg)
void logReceiveCallbackEndInternal (const char *msg)
void logSRDYAssertedInternal (void)
void logSRDYInternal (int level, const char *msg)
bool popLogEntryAsStringInternal (char *buffer, unsigned capacity)
void reportInternal (void)
Static Private Member Functions
static bool isEnabled (void)
Private Attributes
const bool fCanHasDebugger
unsigned fHead
UInt32 fLastSampledNumSRDYs
LogEntry fLog [kBufferSize]
UInt32 fNumSRDYs
unsigned fSize
struct {
clock_sec_t tv_sec
clock_usec_t tv_usec
} fSRDYAssertedTime
unsigned fTail
Static Private Attributes
static BasebandSPILogger fsBasebandSPILogger
static const unsigned kBufferSize = 1UL << kBufferSizePower
static const unsigned kBufferSizePower = 10
static const bool kEnabledMaster = SPI_GM_TASK
static const unsigned kMaxMessageSize = 32
Detailed Description
Definition at line 9 of file BasebandSPILogger.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
kTypeMRDY
kTypeSRDY
kTypeGeneral
kTypeFrameReceived
kTypeFrameSent
kTypeReceiveCallback
kTypeSRDYInterrupt
kTypeDMAComplete
kTypeDMACancel
kTypeDMAError
Definition at line 19 of file BasebandSPILogger.h.
         {
                 kTypeMRDY,
                 kTypeSRDY,
                 kTypeGeneral,
                 kTypeFrameReceived,
                 kTypeFrameSent,
                 kTypeReceiveCallback,
 #if SPI_USE_REAL_ISR_FOR_DEBUG
                 kTypeSRDYInterrupt,
 #endif
                 kTypeDMAComplete,
                 kTypeDMACancel,
                 kTypeDMAError
         };
Constructor & Destructor Documentation
BasebandSPILogger::BasebandSPILogger ()
Definition at line 71 of file BasebandSPILogger.cpp.
References clear(), fLastSampledNumSRDYs, fLog, fNumSRDYs, fSRDYAssertedTime, and isEnabled().
Referenced by isEnabled().
         : fCanHasDebugger( PE_i_can_has_debugger( NULL ) )
 {
         clear();
 #if SPI_USE_REAL_ISR_FOR_DEBUG
         bzero( &fSRDYAssertedTime, sizeof(fSRDYAssertedTime) );
         fNumSRDYs = 0;
         fLastSampledNumSRDYs = 0;
 #endif
         if ( isEnabled() )
         {
                 IOLog( ">>>> SPI Log is located at %p\n", fLog );
         }
 }
BasebandSPILogger::~BasebandSPILogger ()
Definition at line 88 of file BasebandSPILogger.cpp.
Referenced by isEnabled().
 {
 }
Member Function Documentation
void BasebandSPILogger::addEntry (unsigned type, int arg, const char * msg, unsigned messageSize, bool state = false) private
Definition at line 120 of file BasebandSPILogger.cpp.
References BasebandSPILogger::LogEntry::arg, fHead, fLastSampledNumSRDYs, fNumSRDYs, fSize, fSRDYAssertedTime, fTail, getEntry(), isEnabled(), kBufferSize, kMaxMessageSize, kTypeSRDYInterrupt, BasebandSPILogger::LogEntry::message, BasebandSPILogger::LogEntry::srdy_debug, BasebandSPILogger::LogEntry::timestamp, and BasebandSPILogger::LogEntry::type.
Referenced by logDMACancelInternal(), logDMACompleteInternal(), logDMAErrorInternal(), logFrame(), logGeneralInternal(), logMRDYInternal(), logReceiveCallbackBeginInternal(), logReceiveCallbackEndInternal(), and logSRDYInternal().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         clock_sec_t s;
         clock_usec_t us;
         LogEntry * entry = &getEntry( fHead );
 #if SPI_USE_REAL_ISR_FOR_DEBUG
         // If a new SRDY was asserted from the time the last entry was
         // added, add a new entry for the SRDY interrupt assertion
         if (fNumSRDYs != fLastSampledNumSRDYs)
         {
                 fLastSampledNumSRDYs = fNumSRDYs;
                 s = fSRDYAssertedTime.tv_sec;
                 us = fSRDYAssertedTime.tv_usec;
                 entry->timestamp                = s*1000*1000 + us;
                 entry->type                     = kTypeSRDYInterrupt;
                 entry->arg                      = fLastSampledNumSRDYs;
                 fHead++;
                 entry = &getEntry( fHead );
                 if ( fSize < kBufferSize )
                 {
                         fSize++;
                 }
                 else
                 {
                         fTail++;
                 }
         }
 #endif
         clock_get_system_microtime( &s, &us );
         entry->timestamp                = s*1000*1000 + us;
         entry->type                     = type;
         entry->arg                      = arg;
 #if SPI_SRDY_DEBUG
         entry->srdy_debug   = state;
 #endif
         if  ( msg )
         {
                 memcpy( entry->message, msg, MIN( kMaxMessageSize, messageSize ) );
         }
         else
         {
                 entry->message[0] = 0;
         }
         fHead++;
         if ( fSize < kBufferSize )
         {
                 fSize++;
         }
         else
         {
                 fTail++;
         }
 }
static void BasebandSPILogger::clear (void) inline static
Definition at line 83 of file BasebandSPILogger.h.
References clearInternal(), and isEnabled().
Referenced by BasebandSPILogger().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.clearInternal();
                 }
         };
void BasebandSPILogger::clearInternal (void) private
Definition at line 109 of file BasebandSPILogger.cpp.
References fHead, fSize, and fTail.
Referenced by clear(), and popLogEntryAsString().
 {
         fHead = fTail = fSize = 0;
 }
unsigned BasebandSPILogger::getDelta (unsigned now, unsigned before) static
Definition at line 92 of file BasebandSPILogger.cpp.
References isEnabled().
Referenced by isEnabled(), popLogEntryAsStringInternal(), and reportInternal().
 {
         if ( !isEnabled() )
         {
                 return 0;
         }
         if ( now < before )
         {
                 return now + 0xFFFFFFFF - before;
         }
         else
         {
                 return now - before;
         }
 }
BasebandSPILogger::LogEntry & BasebandSPILogger::getEntry (unsigned offset) private
Definition at line 114 of file BasebandSPILogger.cpp.
References fLog, and kBufferSize.
Referenced by addEntry(), popLogEntryAsStringInternal(), and reportInternal().
 {
         offset = offset & ( kBufferSize - 1);
         return fLog[offset];
 }
static bool BasebandSPILogger::isEnabled (void) inline static private
Definition at line 72 of file BasebandSPILogger.h.
References BasebandSPILogger(), fCanHasDebugger, getDelta(), and ~BasebandSPILogger().
Referenced by addEntry(), BasebandSPILogger(), clear(), getDelta(), logDMACancel(), logDMACancelInternal(), logDMAComplete(), logDMACompleteInternal(), logDMAError(), logDMAErrorInternal(), logFrame(), logFrameReceived(), logFrameReceivedInternal(), logFrameSent(), logFrameSentInternal(), logGeneral(), logGeneralInternal(), logMRDY(), logMRDYInternal(), logReceiveCallbackBegin(), logReceiveCallbackBeginInternal(), logReceiveCallbackEnd(), logReceiveCallbackEndInternal(), logSRDY(), logSRDYAsserted(), logSRDYInternal(), popLogEntryAsString(), popLogEntryAsStringInternal(), report(), and reportInternal().
         {
                 return kEnabledMaster && fsBasebandSPILogger.fCanHasDebugger;
         }
static void BasebandSPILogger::logDMACancel (const char * msg = 0) inline static
Definition at line 162 of file BasebandSPILogger.h.
References isEnabled(), and logDMACancelInternal().
Referenced by BasebandSPIController::dmaCompleteAction().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logDMACancelInternal( msg );
                 }
         }
void BasebandSPILogger::logDMACancelInternal (const char * msg) private
Definition at line 289 of file BasebandSPILogger.cpp.
References addEntry(), isEnabled(), and kTypeDMACancel.
Referenced by logDMACancel(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         size_t length = msg?(strlen( msg ) + 1):0;
         addEntry( kTypeDMACancel, 0, msg, length );
 }
static void BasebandSPILogger::logDMAComplete (const char * msg = 0) inline static
Definition at line 154 of file BasebandSPILogger.h.
References isEnabled(), and logDMACompleteInternal().
Referenced by BasebandSPIController::dmaCompleteAction().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logDMACompleteInternal( msg );
                 }
         }
void BasebandSPILogger::logDMACompleteInternal (const char * msg) private
Definition at line 278 of file BasebandSPILogger.cpp.
References addEntry(), isEnabled(), and kTypeDMAComplete.
Referenced by logDMAComplete(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         size_t length = msg?(strlen( msg ) + 1):0;
         addEntry( kTypeDMAComplete, 0, msg, length );
 }
static void BasebandSPILogger::logDMAError (const char * msg = 0) inline static
Definition at line 170 of file BasebandSPILogger.h.
References isEnabled(), and logDMAErrorInternal().
Referenced by BasebandSPIController::dmaCompleteAction().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logDMAErrorInternal( msg );
                 }
         }
void BasebandSPILogger::logDMAErrorInternal (const char * msg) private
Definition at line 300 of file BasebandSPILogger.cpp.
References addEntry(), isEnabled(), and kTypeDMAError.
Referenced by logDMAError(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         size_t length = msg?(strlen( msg ) + 1):0;
         addEntry( kTypeDMAError, 0, msg, length );
 }
void BasebandSPILogger::logFrame (unsigned type, int size, BasebandSPICommand * cmd) private
Definition at line 188 of file BasebandSPILogger.cpp.
References addEntry(), BasebandSPICommand::fBuffer, isEnabled(), and kMaxMessageSize.
Referenced by logFrameReceivedInternal(), and logFrameSentInternal().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         if ( cmd )
         {
                 size = MIN( size, kMaxMessageSize );
                 addEntry( type, size, (const char *)cmd->fBuffer, size );
         }
 }
static void BasebandSPILogger::logFrameReceived (int size, BasebandSPICommand * cmd) inline static
Definition at line 124 of file BasebandSPILogger.h.
References isEnabled(), and logFrameReceivedInternal().
Referenced by BasebandSPIIFXProtocolVersion1::handleTransferComplete(), and BasebandSPIIFXProtocolVersion2::handleTransferComplete().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logFrameReceivedInternal( size, cmd );
                 }
         };
void BasebandSPILogger::logFrameReceivedInternal (int size, BasebandSPICommand * cmd) private
Definition at line 203 of file BasebandSPILogger.cpp.
References isEnabled(), kTypeFrameReceived, and logFrame().
Referenced by logFrameReceived(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         logFrame( kTypeFrameReceived, size, cmd );
 }
static void BasebandSPILogger::logFrameSent (int size, BasebandSPICommand * cmd) inline static
Definition at line 132 of file BasebandSPILogger.h.
References isEnabled(), and logFrameSentInternal().
Referenced by BasebandSPIIFXProtocolVersion1::prepareTransferIfNeeded(), and BasebandSPIIFXProtocolVersion2::prepareTransferIfNeeded().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logFrameSentInternal( size, cmd );
                 }
         }
void BasebandSPILogger::logFrameSentInternal (int size, BasebandSPICommand * cmd) private
Definition at line 213 of file BasebandSPILogger.cpp.
References isEnabled(), kTypeFrameSent, and logFrame().
Referenced by logFrameSent(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         logFrame( kTypeFrameSent, size, cmd );
 }
static void BasebandSPILogger::logGeneral (const char * msg, int arg = 0, bool srdy_state = false) inline static
Definition at line 116 of file BasebandSPILogger.h.
References isEnabled(), and logGeneralInternal().
Referenced by BasebandSPIController::activate(), BasebandSPIController::beginBlockInterrupt(), BasebandSPIController::configure(), BasebandSPIController::configureDMA(), BasebandSPIProtocol::copyTxBuffer(), BasebandSPIController::deactivate(), BasebandSPICommandQueue::dequeueHead(), BasebandSPIController::endBlockInterrupt(), BasebandSPICommandQueue::enqueueTail(), BasebandSPIIFXProtocolVersion1::handleSRDY(), BasebandSPIIFXProtocolVersion2::handleSRDY(), BasebandSPIIFXProtocolVersion1::handleSRDYInterruptAction(), BasebandSPIIFXProtocolVersion2::handleSRDYInterruptAction(), BasebandSPIIFXProtocol::handleSRDYTimeoutAction(), BasebandSPIIFXProtocolVersion1::handleTransferComplete(), BasebandSPIIFXProtocolVersion2::handleTransferComplete(), BasebandSPIIFXProtocolVersion1::prepareTransferIfNeeded(), BasebandSPIIFXProtocolVersion2::prepareTransferIfNeeded(), BasebandSPIProtocol::registerRxBuffer(), BasebandSPIIFXProtocol::setMRDY(), and BasebandSPIController::unconfigure().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logGeneralInternal( msg, arg, srdy_state );
                 }
         }
void BasebandSPILogger::logGeneralInternal (const char * msg, int arg, bool state) private
Definition at line 245 of file BasebandSPILogger.cpp.
References addEntry(), isEnabled(), and kTypeGeneral.
Referenced by logGeneral(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         size_t length = strlen( msg ) + 1;
         addEntry( kTypeGeneral, arg, msg, length, state );
 }
static void BasebandSPILogger::logMRDY (int level, const char * msg = 0) inline static
Definition at line 101 of file BasebandSPILogger.h.
References isEnabled(), and logMRDYInternal().
Referenced by BasebandSPIIFXProtocol::setMRDY().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logMRDYInternal( level, msg );
                 }
         };
void BasebandSPILogger::logMRDYInternal (int level, const char * msg) private
Definition at line 223 of file BasebandSPILogger.cpp.
References addEntry(), isEnabled(), and kTypeMRDY.
Referenced by logMRDY(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         size_t length = msg?(strlen( msg ) + 1):0;
         addEntry( kTypeMRDY, level, msg, length );
 }
static void BasebandSPILogger::logReceiveCallbackBegin (const char * msg = 0) inline static
Definition at line 139 of file BasebandSPILogger.h.
References isEnabled(), and logReceiveCallbackBeginInternal().
Referenced by BasebandSPIIFXProtocolVersion1::handleTransferComplete(), and BasebandSPIIFXProtocolVersion2::handleTransferComplete().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logReceiveCallbackBeginInternal( msg );
                 }
         }
void BasebandSPILogger::logReceiveCallbackBeginInternal (const char * msg) private
Definition at line 256 of file BasebandSPILogger.cpp.
References addEntry(), isEnabled(), and kTypeReceiveCallback.
Referenced by logReceiveCallbackBegin(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         size_t length = msg?(strlen( msg ) + 1):0;
         addEntry( kTypeReceiveCallback, 0, msg, length );
 }
static void BasebandSPILogger::logReceiveCallbackEnd (const char * msg = 0) inline static
Definition at line 146 of file BasebandSPILogger.h.
References isEnabled(), and logReceiveCallbackEndInternal().
Referenced by BasebandSPIIFXProtocolVersion1::handleTransferComplete(), and BasebandSPIIFXProtocolVersion2::handleTransferComplete().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logReceiveCallbackEndInternal( msg );
                 }
         }
void BasebandSPILogger::logReceiveCallbackEndInternal (const char * msg) private
Definition at line 267 of file BasebandSPILogger.cpp.
References addEntry(), isEnabled(), and kTypeReceiveCallback.
Referenced by logReceiveCallbackEnd(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         size_t length = msg?(strlen( msg ) + 1):0;
         addEntry( kTypeReceiveCallback, 1, msg, length );
 }
static void BasebandSPILogger::logSRDY (int level, const char * msg = 0) inline static
Definition at line 108 of file BasebandSPILogger.h.
References isEnabled(), and logSRDYInternal().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logSRDYInternal( level, msg );
                 }
         };
static void BasebandSPILogger::logSRDYAsserted (void) inline static
Definition at line 92 of file BasebandSPILogger.h.
References isEnabled(), and logSRDYAssertedInternal().
Referenced by BasebandSPIIFXProtocolVersion1::handleSRDYFilterInterruptAction(), and BasebandSPIIFXProtocolVersion2::handleSRDYFilterInterruptAction().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.logSRDYAssertedInternal();
                 }
         };
void BasebandSPILogger::logSRDYAssertedInternal (void) private
Definition at line 312 of file BasebandSPILogger.cpp.
References fNumSRDYs, and fSRDYAssertedTime.
Referenced by logSRDYAsserted(), and popLogEntryAsString().
 {
         clock_get_system_microtime( &(fSRDYAssertedTime.tv_sec),
                                     &(fSRDYAssertedTime.tv_usec) );
         fNumSRDYs++;
 }
void BasebandSPILogger::logSRDYInternal (int level, const char * msg) private
Definition at line 234 of file BasebandSPILogger.cpp.
References addEntry(), isEnabled(), and kTypeSRDY.
Referenced by logSRDY(), and popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         size_t length = msg?(strlen( msg ) + 1):0;
         addEntry( kTypeSRDY, level, msg, length );
 }
static bool BasebandSPILogger::popLogEntryAsString (char * buffer, unsigned capacity) inline static
Definition at line 187 of file BasebandSPILogger.h.
References clearInternal(), isEnabled(), logDMACancelInternal(), logDMACompleteInternal(), logDMAErrorInternal(), logFrameReceivedInternal(), logFrameSentInternal(), logGeneralInternal(), logMRDYInternal(), logReceiveCallbackBeginInternal(), logReceiveCallbackEndInternal(), logSRDYAssertedInternal(), logSRDYInternal(), popLogEntryAsStringInternal(), and reportInternal().
Referenced by BasebandSPIDevice::getLogEntry().
         {
                 if ( isEnabled() )
                 {
                         return fsBasebandSPILogger.popLogEntryAsStringInternal( buffer, capacity );
                 }
                 else
                 {
                         return false;
                 }
         }
bool BasebandSPILogger::popLogEntryAsStringInternal (char * buffer, unsigned capacity) private
Definition at line 385 of file BasebandSPILogger.cpp.
References BasebandSPILogger::LogEntry::arg, dumpBinary(), fSize, fTail, getDelta(), getEntry(), isEnabled(), kTypeDMACancel, kTypeDMAComplete, kTypeDMAError, kTypeFrameReceived, kTypeFrameSent, kTypeGeneral, kTypeMRDY, kTypeReceiveCallback, kTypeSRDY, kTypeSRDYInterrupt, BasebandSPILogger::LogEntry::message, SPIsnprintf(), BasebandSPILogger::LogEntry::srdy_debug, BasebandSPILogger::LogEntry::timestamp, and BasebandSPILogger::LogEntry::type.
Referenced by popLogEntryAsString().
 {
         if ( !isEnabled() )
         {
                 return false;
         }
         if ( fSize == 0 )
         {
                 return false;
         }
         else
         {
                 static UInt32 lastTimestamp = 0;
                 LogEntry * entry = &getEntry( fTail );
                 fSize--;
                 fTail++;
                 IOByteCount copied = 0;
                 UInt32 delta = getDelta( entry->timestamp, lastTimestamp );
                 lastTimestamp = entry->timestamp;
                 copied += SPIsnprintf( buffer + copied, capacity - copied, "%010u:%010u: ", lastTimestamp, delta );
                 switch ( entry->type )
                 {
                 case kTypeMRDY:
                         copied += SPIsnprintf( buffer + copied, capacity - copied, "MRDY: %d - %s", entry->arg, entry->message );
                         break;
                 case kTypeSRDY:
                         copied += SPIsnprintf( buffer + copied, capacity - copied, "SRDY: %d - %s", entry->arg, entry->message );
                         break;
 #if SPI_USE_REAL_ISR_FOR_DEBUG
                 case kTypeSRDYInterrupt:
                         copied += SPIsnprintf( buffer + copied, capacity - copied, "SRDYA: %d", entry->arg );
                         break;
 #endif
                 case kTypeGeneral:
 #if SPI_SRDY_DEBUG
                                 copied += SPIsnprintf( buffer + copied, capacity - copied, "EVENT: %s, %p, (%d)", entry->message, entry->arg,( entry->srdy_debug ? 1 : 0 ) );
 #else
                         copied += SPIsnprintf( buffer + copied, capacity - copied, "EVENT: %s, %p", entry->message, entry->arg );
 #endif
                         break;
                 case kTypeFrameReceived:
                 case kTypeFrameSent:
                         copied += SPIsnprintf( buffer + copied, capacity - copied, "Frame %s:", entry->type == kTypeFrameReceived? "Rx": "Tx" );
                         copied += dumpBinary( entry->message, entry->arg, buffer + copied, capacity - copied );
                         break;
                 case kTypeReceiveCallback:
                         copied += SPIsnprintf( buffer + copied, capacity - copied, "Rx Callback: %d - %s", entry->arg, entry->message );
                         break;
                 case kTypeDMAComplete:
                         copied += SPIsnprintf( buffer + copied, capacity - copied, "DMA Complete: %s", entry->message );
                         break;
                 case kTypeDMACancel:
                         copied += SPIsnprintf( buffer + copied, capacity - copied, "DMA Cancel: %s", entry->message );
                         break;
                 case kTypeDMAError:
                         copied += SPIsnprintf( buffer + copied, capacity - copied, "DMA Error: %s", entry->message );
                         break;
                 }
                 return true;
         }
 }
static void BasebandSPILogger::report (void) inline static
Definition at line 178 of file BasebandSPILogger.h.
References isEnabled(), and reportInternal().
Referenced by _BasebandSPITriggerAssertion().
         {
                 if ( isEnabled() )
                 {
                         fsBasebandSPILogger.reportInternal();
                 }
         }
void BasebandSPILogger::reportInternal (void) private
Definition at line 320 of file BasebandSPILogger.cpp.
References BasebandSPILogger::LogEntry::arg, dumpBinary(), fSize, fTail, getDelta(), getEntry(), isEnabled(), kTypeDMAComplete, kTypeFrameReceived, kTypeFrameSent, kTypeGeneral, kTypeMRDY, kTypeReceiveCallback, kTypeSRDY, kTypeSRDYInterrupt, BasebandSPILogger::LogEntry::message, BasebandSPILogger::LogEntry::timestamp, and BasebandSPILogger::LogEntry::type.
Referenced by popLogEntryAsString(), and report().
 {
         if ( !isEnabled() )
         {
                 return;
         }
         unsigned lastTimestamp = 0;
         IOLog( "--- BEGIN SPI LOG ---\n" );
         for( UInt32 i = 0; i < fSize; i++ )
         {
                 LogEntry * entry = &getEntry( fTail + i );
                 UInt32 delta = getDelta( entry->timestamp, lastTimestamp );
                 lastTimestamp = entry->timestamp;
                 IOLog( "%010u:%010u: ", lastTimestamp, delta );
                 switch ( entry->type )
                 {
                 case kTypeMRDY:
                         IOLog( "MRDY: %d - %s\n", entry->arg, entry->message );
                         break;
                 case kTypeSRDY:
                         IOLog( "SRDY: %d - %s\n", entry->arg, entry->message );
                         break;
 #if SPI_USE_REAL_ISR_FOR_DEBUG
                 case kTypeSRDYInterrupt:
                         IOLog( "SRDYA: %d\n", entry->arg );
                         break;
 #endif
                 case kTypeGeneral:
                         IOLog( "EVENT: %s, %p\n", entry->message, entry->arg );
                         break;
                 case kTypeFrameReceived:
                 case kTypeFrameSent:
{
                                 char buff[256];
                                 IOLog( "Frame %s(%u):\n", entry->type == kTypeFrameReceived? "Rx": "Tx", entry->arg );
                                 dumpBinary( entry->message, entry->arg, buff, sizeof( buff ) );
                                 IOLog( "%s", buff );
                         }
                         break;
                 case kTypeReceiveCallback:
                         IOLog( "Rx Callback: %d - %s\n", entry->arg, entry->message );
                         break;
                 case kTypeDMAComplete:
                         IOLog( "DMA Complete: %s\n", entry->message );
                         break;
                 }
         }
         IOLog( "--- END SPI LOG ---\n" );
 }
Member Data Documentation
const bool BasebandSPILogger::fCanHasDebugger private
Definition at line 47 of file BasebandSPILogger.h.
Referenced by isEnabled().
unsigned BasebandSPILogger::fHead private
Definition at line 51 of file BasebandSPILogger.h.
Referenced by addEntry(), and clearInternal().
UInt32 BasebandSPILogger::fLastSampledNumSRDYs private
Definition at line 63 of file BasebandSPILogger.h.
Referenced by addEntry(), and BasebandSPILogger().
LogEntry BasebandSPILogger::fLog[kBufferSize] private
Definition at line 49 of file BasebandSPILogger.h.
Referenced by BasebandSPILogger(), and getEntry().
UInt32 BasebandSPILogger::fNumSRDYs private
Definition at line 62 of file BasebandSPILogger.h.
Referenced by addEntry(), BasebandSPILogger(), and logSRDYAssertedInternal().
BasebandSPILogger BasebandSPILogger::fsBasebandSPILogger static private
Definition at line 55 of file BasebandSPILogger.h.
unsigned BasebandSPILogger::fSize private
Definition at line 53 of file BasebandSPILogger.h.
Referenced by addEntry(), clearInternal(), popLogEntryAsStringInternal(), and reportInternal().
struct { ... } BasebandSPILogger::fSRDYAssertedTime
Referenced by addEntry(), BasebandSPILogger(), and logSRDYAssertedInternal().
unsigned BasebandSPILogger::fTail private
Definition at line 52 of file BasebandSPILogger.h.
Referenced by addEntry(), clearInternal(), popLogEntryAsStringInternal(), and reportInternal().
const unsigned BasebandSPILogger::kBufferSize = 1UL << kBufferSizePower static private
Definition at line 13 of file BasebandSPILogger.h.
Referenced by addEntry(), and getEntry().
const unsigned BasebandSPILogger::kBufferSizePower = 10 static private
Definition at line 12 of file BasebandSPILogger.h.
const bool BasebandSPILogger::kEnabledMaster = SPI_GM_TASK static private
Definition at line 17 of file BasebandSPILogger.h.
const unsigned BasebandSPILogger::kMaxMessageSize = 32 static private
Definition at line 15 of file BasebandSPILogger.h.
Referenced by addEntry(), and logFrame().
clock_sec_t BasebandSPILogger::tv_sec
Definition at line 59 of file BasebandSPILogger.h.
clock_usec_t BasebandSPILogger::tv_usec
Definition at line 60 of file BasebandSPILogger.h.
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPILogger.h
/BasebandSPI/BasebandSPILogger.cpp