RAInterface Class Reference
RAInterface Class Reference
#include <RegisterAccessorLib.h>
Classes
class Exception
Public Member Functions
void connect (void)
void disconnect (void)
RAInterface ()
unsigned read (unsigned reg) const
void write (unsigned reg, unsigned value) const
void writeMasked (unsigned reg, unsigned value, unsigned mask) const
~RAInterface ()
Private Member Functions
void ioctl (unsigned what, void *data) const
Private Attributes
int fFD
Static Private Attributes
static const std::string kDevicePath = "/dev/RegisterAccess"
Detailed Description
Definition at line 16 of file RegisterAccessorLib.h.
Constructor & Destructor Documentation
RAInterface::RAInterface ()
Definition at line 32 of file RegisterAccessorLib.cpp.
         : fFD( -1 )
 {
 }
RAInterface::~RAInterface ()
Definition at line 37 of file RegisterAccessorLib.cpp.
References disconnect(), and fFD.
 {
         if( fFD != -1 )
         {
                 disconnect();
         }
 }
Member Function Documentation
void RAInterface::connect (void)
Definition at line 45 of file RegisterAccessorLib.cpp.
References fFD, and kDevicePath.
Referenced by main().
 {
         if ( fFD != -1 )
         {
                 throw Exception( "FD is %d\n", fFD );
         }
         fFD = ::open( kDevicePath.c_str(), O_RDWR );
         if ( fFD < 0 )
         {
                 throw Exception( "Opening %s failed\n", kDevicePath.c_str() );
         }
 }
void RAInterface::disconnect (void)
Definition at line 59 of file RegisterAccessorLib.cpp.
References fFD.
Referenced by main(), and ~RAInterface().
 {
         if ( fFD == -1 )
         {
                 throw Exception( "Cannot disconnect when not open, FD is %d\n", fFD );
         }
         ::close( fFD );
         fFD = -1;
 }
void RAInterface::ioctl (unsigned what, void * data) const private
Definition at line 72 of file RegisterAccessorLib.cpp.
References fFD.
Referenced by read(), write(), and writeMasked().
 {
         int ret = ::ioctl( fFD, what, data );
         if ( ret != 0 )
         {
                 int err = errno;
                 throw Exception( "ioctl failed with ret %d, errno %d\n", ret, err );
         }
 }
unsigned RAInterface::read (unsigned reg) const inline
Definition at line 49 of file RegisterAccessorLib.h.
References ioctl(), and RAREAD.
Referenced by main().
                 {
                         ioctl( RAREAD, &reg );
                         return reg;
                 }
void RAInterface::write (unsigned reg, unsigned value) const inline
Definition at line 55 of file RegisterAccessorLib.h.
References RAWriteInfo::addr, ioctl(), RAWRITE, and RAWriteInfo::value.
Referenced by configureGPIO(), and main().
                 {
                         RAWriteInfo info;
                         info.addr = reg;
                         info.value = value;
                         ioctl( RAWRITE, &info );
                 }
void RAInterface::writeMasked (unsigned reg, unsigned value, unsigned mask) const inline
Definition at line 63 of file RegisterAccessorLib.h.
References RAMaskedWriteInfo::addr, ioctl(), RAMaskedWriteInfo::mask, RAMASKEDWRITE, and RAMaskedWriteInfo::value.
Referenced by configureGPIO(), configureHCLK(), and main().
                 {
                         RAMaskedWriteInfo info;
                         info.addr = reg;
                         info.value = value;
                         info.mask = mask;
                         ioctl( RAMASKEDWRITE, &info );
                 }
Member Data Documentation
int RAInterface::fFD private
Definition at line 36 of file RegisterAccessorLib.h.
Referenced by connect(), disconnect(), ioctl(), and ~RAInterface().
const std::string RAInterface::kDevicePath = "/dev/RegisterAccess" static private
Definition at line 33 of file RegisterAccessorLib.h.
Referenced by connect().
The documentation for this class was generated from the following files:
/BasebandSPI/Utilities/RegisterAccessor/RegisterAccessorLib.h
/BasebandSPI/Utilities/RegisterAccessor/RegisterAccessorLib.cpp