BasebandSPICommandQueue Class Reference
BasebandSPICommandQueue Class Reference
#include <BasebandSPICommandQueue.h>
Public Member Functions
BasebandSPICommandQueue ()
BasebandSPICommand * dequeueHead (void)
BasebandSPICommand * dequeueTail (void)
void enqueueTail (BasebandSPICommand *command)
UInt32 getSize (void) const
bool isEmpty (void) const
BasebandSPICommand * peekHead (void) const
BasebandSPICommand * peekTail (void) const
~BasebandSPICommandQueue ()
Static Private Member Functions
static const char * getDebugName (void)
Private Attributes
BasebandSPICommand * fHead
UInt32 fSize
BasebandSPICommand * fTail
Detailed Description
Definition at line 10 of file BasebandSPICommandQueue.h.
Constructor & Destructor Documentation
BasebandSPICommandQueue::BasebandSPICommandQueue ()
Definition at line 7 of file BasebandSPICommandQueue.cpp.
         : fSize( 0 ), fHead( NULL ), fTail( NULL )
 {
 }
BasebandSPICommandQueue::~BasebandSPICommandQueue ()
Definition at line 12 of file BasebandSPICommandQueue.cpp.
References fHead, fSize, fTail, and SPI_ASSERT.
 {
         SPI_ASSERT( fSize, ==, 0 );
         SPI_ASSERT( fHead, ==, NULL );
         SPI_ASSERT( fTail, ==, NULL );
 }
Member Function Documentation
BasebandSPICommand * BasebandSPICommandQueue::dequeueHead (void)
Definition at line 19 of file BasebandSPICommandQueue.cpp.
References DEBUG_SPEW, fHead, fSize, fTail, BasebandSPICommand::getNext(), isEmpty(), BasebandSPILogger::logGeneral(), BasebandSPICommand::setNext(), SPI_ASSERT, and SPI_LOG.
Referenced by BasebandSPIProtocol::flushTxBuffers(), and getDebugName().
 {
         if ( isEmpty() )
         {
                 return NULL;
         }
 #if SPI_PEDANTIC_ASSERT
         SPI_ASSERT( fHead, !=, NULL );
         SPI_ASSERT( fTail, !=, NULL );
 #endif
         BasebandSPICommand * ret = fHead;
         fSize--;
         if ( fSize )
         {
                 fHead = fHead->getNext();
                 ret->setNext( NULL );
         }
         else
         {
                 fHead = NULL;
                 fTail = NULL;
         }
         BasebandSPILogger::logGeneral( "DQ", fSize );
         SPI_LOG( DEBUG_SPEW, "queue size is now %u\n", fSize );
         return ret;
 };
BasebandSPICommand* BasebandSPICommandQueue::dequeueTail (void)
Referenced by getDebugName().
void BasebandSPICommandQueue::enqueueTail (BasebandSPICommand * command)
Definition at line 53 of file BasebandSPICommandQueue.cpp.
References DEBUG_SPEW, fHead, fSize, fTail, isEmpty(), BasebandSPILogger::logGeneral(), BasebandSPICommand::setNext(), and SPI_LOG.
Referenced by BasebandSPIProtocol::copyTxBuffer(), and getDebugName().
 {
         if ( isEmpty() )
         {
                 fHead = command;
         }
         else
         {
                 fTail->setNext( command );
         }
         fTail = command;
         fSize++;
         BasebandSPILogger::logGeneral( "NQ", fSize );
         SPI_LOG( DEBUG_SPEW, "queue size is now %u\n", fSize );
 }
static const char* BasebandSPICommandQueue::getDebugName (void) inline static private
Definition at line 17 of file BasebandSPICommandQueue.h.
References dequeueHead(), dequeueTail(), and enqueueTail().
         {
                 return "BasebandSPICommandQueue";
         }
UInt32 BasebandSPICommandQueue::getSize (void) const inline
Definition at line 36 of file BasebandSPICommandQueue.h.
References fSize.
Referenced by BasebandSPIProtocol::copyTxBuffer(), BasebandSPIProtocol::flushTxBuffers(), and isEmpty().
         {
                 return fSize;
         };
bool BasebandSPICommandQueue::isEmpty (void) const inline
Definition at line 41 of file BasebandSPICommandQueue.h.
References getSize().
Referenced by dequeueHead(), enqueueTail(), and BasebandSPIProtocol::flushTxBuffers().
         {
                 return getSize() == 0;
         };
BasebandSPICommand* BasebandSPICommandQueue::peekHead (void) const inline
Definition at line 26 of file BasebandSPICommandQueue.h.
References fHead.
         {
                 return fHead;
         };
BasebandSPICommand* BasebandSPICommandQueue::peekTail (void) const inline
Definition at line 31 of file BasebandSPICommandQueue.h.
References fTail.
         {
                 return fTail;
         };
Member Data Documentation
BasebandSPICommand* BasebandSPICommandQueue::fHead private
Definition at line 49 of file BasebandSPICommandQueue.h.
Referenced by dequeueHead(), enqueueTail(), peekHead(), and ~BasebandSPICommandQueue().
UInt32 BasebandSPICommandQueue::fSize private
Definition at line 44 of file BasebandSPICommandQueue.h.
Referenced by dequeueHead(), enqueueTail(), getSize(), and ~BasebandSPICommandQueue().
BasebandSPICommand* BasebandSPICommandQueue::fTail private
Definition at line 48 of file BasebandSPICommandQueue.h.
Referenced by dequeueHead(), enqueueTail(), peekTail(), and ~BasebandSPICommandQueue().
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPICommandQueue.h
/BasebandSPI/BasebandSPICommandQueue.cpp