BasebandSPIIFXProtocol Class Reference
BasebandSPIIFXProtocol Class Reference abstract
#include <BasebandSPIIFXProtocol.h>
Inherits BasebandSPIProtocol.
Inherited by BasebandSPIIFXProtocolVersion1, and BasebandSPIIFXProtocolVersion2.
Public Member Functions
virtual IOReturn activate (void)
virtual IOReturn exitLowPower (void)
virtual void free (void)
virtual BasebandSPIProtocolSnapshot * getSnapshot (void) const
virtual bool init (BasebandSPIController *controller, BasebandSPIDevice *device)
virtual bool isSRDYStateHigh (void)
virtual IOReturn predeactivate (void)
Public Member Functions inherited from BasebandSPIProtocol
IOReturn copyTxBuffer (UInt8 *source, IOByteCount length, IOByteCount *remaining, bool transmitNow)
virtual IOReturn deactivate (void)
virtual IOReturn enterLowPower (void)
IOByteCount getFramePayloadSize (void) const
IOByteCount getFrameSize (void) const
IOByteCount getMaxRxBufferCount (void) const
virtual IOReturn handleCancelledRxCommand (IODMACommand *command)=0
virtual IOReturn handleCancelledTxCommand (IODMACommand *command)=0
virtual IOReturn handleTransferCancelled (void)=0
virtual IOReturn handleTransferComplete (IODMACommand *receivedCommand, IODMACommand *sendCommand)=0
IOReturn registerRxBuffer (IOMemoryDescriptor *md, UInt8 *virtualAddress, void *cookie)
virtual IOReturn unregisterAllRxBuffers (void)
Protected Member Functions
bool canHandleSRDY (void) const
void clearSRDYMissCount (void)
virtual IOReturn createEventSources (void)
virtual IOReturn createFunctions (void)
virtual IOInterruptEventAction getSRDYAction (void) const =0
virtual IOFilterInterruptAction getSRDYFilterAction (void) const =0
virtual void handleSRDYInterruptAction (IOInterruptEventSource *es, int count)=0
void handleSRDYTimeoutAction (IOTimerEventSource *es)
void lowerMRDY (void)
void raiseMRDY (void)
virtual IOReturn releaseEventSources (void)
virtual IOReturn releaseFunctions (void)
void setMRDY (UInt32 value)
void startSRDYTimeoutTimer (void)
void stopSRDYTimeoutTimer (void)
Protected Member Functions inherited from BasebandSPIProtocol
IOReturn addEventSource (IOEventSource **es, const char *name)
void addRxFreeCommand (BasebandSPICommand *command)
void addRxUnusedCommand (BasebandSPICommand *command)
void addTxUnusedCommand (BasebandSPICommand *command)
virtual BasebandSPICommand * allocateRxCommand (void) const =0
virtual BasebandSPICommand * allocateTxCommand (void) const =0
virtual const char * getDebugName (void) const =0
virtual IOByteCount getHeaderAndFooterSize (void) const =0
UInt32 getNumRxUnusedCommands (void) const
UInt32 getNumTxUnusedCommands (void) const
unsigned getRemainingTimeLeftMicroSec (const uint64_t end, const uint64_t start, unsigned differenceMicroseconds)
BasebandSPICommand * getRxFreeCommand (void)
BasebandSPICommand * getRxUnusedCommand (void)
void getTime (uint64_t *time) const
BasebandSPICommand * getTxPendingCommand (void) const
BasebandSPICommand * getTxUnusedCommand (void)
bool getUInt32PropertyFromController (const char *name, UInt32 *device)
IOWorkLoop * getWorkLoop (void) const
virtual void prepareTransferIfNeeded (UInt32 prepareFlags)=0
Protected Attributes
AppleARMFunction * fMRDYFunction
uint64_t fMRDYModificationTime
UInt32 fMRDYState
IOInterruptEventSource * fSRDYEventSource
AppleARMFunction * fSRDYFunction
IOTimerEventSource * fSRDYTimeoutEventSource
Protected Attributes inherited from BasebandSPIProtocol
BasebandSPICommandQueue * fCommandQueue
BasebandSPIController * fController
BasebandSPIDevice * fDevice
IOByteCount fFramePayloadSize
IOByteCount fFrameSize
bool fInLowPower
UInt32 fRxAvailableBufferCount
UInt32 fRxBufferCount
IOCommandPool * fRxDMACommandPool
IOCommandPool * fRxFreeCommandPool
UInt32 fTxAvailableBufferCount
UInt32 fTxBufferCount
IOCommandPool * fTxDMACommandPool
Static Protected Attributes
static const UInt32 kSRDYTimeoutInterval = 2*1000
Private Member Functions
OSDeclareAbstractStructors (BasebandSPIIFXProtocol)
Private Attributes
bool fAllowSRDY
Additional Inherited Members
Static Public Member Functions inherited from BasebandSPIProtocol
static BasebandSPIProtocol * create (BasebandSPIController *controller, BasebandSPIDevice *device)
Protected Types inherited from BasebandSPIProtocol
enum PrepareFlags { kPrepareInitiate = 1UL << 0, kPrepareStart = 1UL << 1, kPrepareRxRegistered = 1UL << 2 }
Static Protected Member Functions inherited from BasebandSPIProtocol
static const char * getDebugNameStatic (void)
static bool getUInt32PropertyWithProvider (IOService *provider, const char *name, UInt32 *device)
Detailed Description
Definition at line 15 of file BasebandSPIIFXProtocol.h.
Member Function Documentation
IOReturn BasebandSPIIFXProtocol::activate (void) virtual
Reimplemented from BasebandSPIProtocol.
Reimplemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Definition at line 256 of file BasebandSPIIFXProtocol.cpp.
References clearSRDYMissCount(), DEBUG_INFO, fAllowSRDY, fSRDYEventSource, SPI_ASSERT_SUCCESS, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         IOReturn ret = super::activate();
         SPI_ASSERT_SUCCESS( ret );
         clearSRDYMissCount();
         fAllowSRDY = true;
         fSRDYEventSource->enable();
         return kIOReturnSuccess;
 }
bool BasebandSPIIFXProtocol::canHandleSRDY (void) const inline protected
Definition at line 80 of file BasebandSPIIFXProtocol.h.
References fAllowSRDY, BasebandSPIProtocol::fInLowPower, BasebandSPIProtocol::fRxAvailableBufferCount, and handleSRDYTimeoutAction().
         {
                 return fAllowSRDY && !fInLowPower && fRxAvailableBufferCount;
         }
void BasebandSPIIFXProtocol::clearSRDYMissCount (void) inline protected
Definition at line 88 of file BasebandSPIIFXProtocol.h.
Referenced by activate(), init(), and stopSRDYTimeoutTimer().
         {
 #if SPI_PROTOCOL_RERAISE_MRDY
                 fSRDYMissCount = 0;
 #endif
         }
IOReturn BasebandSPIIFXProtocol::createEventSources (void) protected virtual
Definition at line 64 of file BasebandSPIIFXProtocol.cpp.
References BasebandSPIProtocol::addEventSource(), DEBUG_INFO, BasebandSPIProtocol::fController, fSRDYEventSource, fSRDYTimeoutEventSource, getSRDYAction(), getSRDYFilterAction(), handleSRDYTimeoutAction(), and SPI_TRACE.
Referenced by init().
 {
         IOReturn ret;
         SPI_TRACE( DEBUG_INFO );
         IOInterruptEventAction interruptAction = getSRDYAction();
 #if ( SPI_USE_REAL_ISR || SPI_USE_REAL_ISR_FOR_DEBUG )
         IOFilterInterruptAction filterInterruptAction = getSRDYFilterAction();
         fSRDYEventSource = IOFilterInterruptEventSource::filterInterruptEventSource( this,
                 interruptAction,
                 filterInterruptAction,
                 fController->getProvider(), 0 );
 #else
         fSRDYEventSource = IOInterruptEventSource::interruptEventSource(this,
                 interruptAction,
                 fController->getProvider(), 0);
 #endif
         ret = addEventSource( (IOEventSource **)&fSRDYEventSource, "SRDY Interrupt" );
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         IOTimerEventSource::Action action;
         action = OSMemberFunctionCast( IOTimerEventSource::Action, this,
                                                                                         &BasebandSPIIFXProtocol::handleSRDYTimeoutAction );
         fSRDYTimeoutEventSource = IOTimerEventSource::timerEventSource( this, action );
         ret = addEventSource( (IOEventSource **)&fSRDYTimeoutEventSource, "SRDY Timeout" );
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIIFXProtocol::createFunctions (void) protected virtual
Definition at line 125 of file BasebandSPIIFXProtocol.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, BasebandSPIProtocol::fController, fMRDYFunction, fMRDYState, fSRDYFunction, SPI_LOG, and SPI_TRACE.
Referenced by init().
 {
         SPI_TRACE( DEBUG_INFO );
         fMRDYFunction = AppleARMFunction::withProvider( fController->getProvider(), "function-mrdy");
         if (!fMRDYFunction)
         {
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't get function-mrdy\n" );
                 return kIOReturnError;
         }
         fMRDYState = 3;
         // Reconfigure IPC_SRDY. iBoot sets it as UART1_NCTS
         fSRDYFunction = AppleARMFunction::withProvider( fController->getProvider(), "function-srdy");
         if ( !fSRDYFunction )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't get function-srdy\n" );
                 return kIOReturnError;
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIIFXProtocol::exitLowPower (void) virtual
Reimplemented from BasebandSPIProtocol.
Reimplemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Definition at line 361 of file BasebandSPIIFXProtocol.cpp.
References fSRDYEventSource, handleSRDYInterruptAction(), and isSRDYStateHigh().
 {
         IOReturn ret = super::exitLowPower();
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         if ( isSRDYStateHigh() )
         {
                 handleSRDYInterruptAction( fSRDYEventSource, 1 );
         }
         return kIOReturnSuccess;
 }
void BasebandSPIIFXProtocol::free (void) virtual
Reimplemented from BasebandSPIProtocol.
Reimplemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Definition at line 53 of file BasebandSPIIFXProtocol.cpp.
References DEBUG_INFO, releaseEventSources(), releaseFunctions(), and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         releaseEventSources();
         releaseFunctions();
         super::free();
 }
BasebandSPIProtocolSnapshot * BasebandSPIIFXProtocol::getSnapshot (void) const virtual
Implements BasebandSPIProtocol.
Definition at line 316 of file BasebandSPIIFXProtocol.cpp.
References fMRDYState, fSRDYFunction, BasebandSPIControllerSnapshot::kDunno, BasebandSPIControllerSnapshot::kHigh, and BasebandSPIControllerSnapshot::kLow.
 {
         BasebandSPIControllerSnapshot::PinState mrdyState = BasebandSPIControllerSnapshot::kDunno;
         if ( fMRDYState == 1 )
         {
                 mrdyState = BasebandSPIControllerSnapshot::kHigh;
         }
         else if ( fMRDYState == 0 )
         {
                 mrdyState = BasebandSPIControllerSnapshot::kLow;
         }
         BasebandSPIControllerSnapshot::PinState srdyState = BasebandSPIControllerSnapshot::kDunno;
         if ( fSRDYFunction )
         {
                 UInt32 dest = 0;
                 fSRDYFunction->callFunction(NULL, &dest );
                 if ( dest == 1)
                 {
                         srdyState = BasebandSPIControllerSnapshot::kHigh;
                 }
                 else if ( dest == 0 )
                 {
                         srdyState = BasebandSPIControllerSnapshot::kLow;
                 }
         }
         return new BasebandSPIIFXProtocolSnapshot( mrdyState, srdyState );
 };
virtual IOInterruptEventAction BasebandSPIIFXProtocol::getSRDYAction (void) const protected pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by createEventSources().
virtual IOFilterInterruptAction BasebandSPIIFXProtocol::getSRDYFilterAction (void) const protected pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by createEventSources().
virtual void BasebandSPIIFXProtocol::handleSRDYInterruptAction (IOInterruptEventSource * es, int count) protected pure virtual
Implemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Referenced by exitLowPower().
void BasebandSPIIFXProtocol::handleSRDYTimeoutAction (IOTimerEventSource * es) protected
Definition at line 229 of file BasebandSPIIFXProtocol.cpp.
References DEBUG_CRITICAL, BasebandSPIProtocol::fController, isSRDYStateHigh(), kBasebandSPIReturnProtocolError, BasebandSPILogger::logGeneral(), lowerMRDY(), raiseMRDY(), BasebandSPIController::reportError(), SPI_LOG, SPI_TRACE, and startSRDYTimeoutTimer().
Referenced by canHandleSRDY(), and createEventSources().
 {
         (void)es;
         SPI_TRACE( DEBUG_CRITICAL );
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "SRDYT", 0, isSRDYStateHigh() );
 #else
         BasebandSPILogger::logGeneral( "SRDYT", 0 );
 #endif
 #if SPI_PROTOCOL_RERAISE_MRDY
         if ( fSRDYMissCount++ < 5 )
         {
                 SPI_LOG( DEBUG_CRITICAL, "SRDY Timeout, retry number %u\n", fSRDYMissCount );
                 lowerMRDY();
                 raiseMRDY();
                 startSRDYTimeoutTimer();
                 return;
         }
 #endif
         fController->reportError( kBasebandSPIReturnProtocolError, "SRDY Timeout" );
 }
bool BasebandSPIIFXProtocol::init (BasebandSPIController * controller, BasebandSPIDevice * device) virtual
Reimplemented from BasebandSPIProtocol.
Reimplemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Definition at line 14 of file BasebandSPIIFXProtocol.cpp.
References clearSRDYMissCount(), createEventSources(), createFunctions(), DEBUG_INFO, fMRDYFunction, fMRDYModificationTime, fSRDYEventSource, fSRDYFunction, fSRDYTimeoutEventSource, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         fMRDYFunction    = NULL;
         fSRDYFunction    = NULL;
         fSRDYEventSource                        = NULL;
         fSRDYTimeoutEventSource         = NULL;
         clearSRDYMissCount();
         fMRDYModificationTime = 0;
         bool ret = super::init( controller, device );
         if ( !ret )
         {
                 return ret;
         }
         IOReturn result;
         result = createFunctions();
         if ( result != kIOReturnSuccess )
         {
                 return false;
         }
         result = createEventSources();
         if ( result != kIOReturnSuccess )
         {
                 return false;
         }
         return true;
 }
bool BasebandSPIIFXProtocol::isSRDYStateHigh (void) virtual
Implements BasebandSPIProtocol.
Definition at line 350 of file BasebandSPIIFXProtocol.cpp.
References fSRDYFunction.
Referenced by exitLowPower(), handleSRDYTimeoutAction(), and setMRDY().
 {
         UInt32 dest = 0;
         if ( fSRDYFunction )
         {
                 fSRDYFunction->callFunction(NULL, &dest );
         }
         return ( dest == 1 );
 }
void BasebandSPIIFXProtocol::lowerMRDY (void) inline protected
Definition at line 64 of file BasebandSPIIFXProtocol.h.
References setMRDY().
Referenced by handleSRDYTimeoutAction(), and predeactivate().
         {
                 setMRDY( 0 );
         }
BasebandSPIIFXProtocol::OSDeclareAbstractStructors (BasebandSPIIFXProtocol) private
IOReturn BasebandSPIIFXProtocol::predeactivate (void) virtual
Reimplemented from BasebandSPIProtocol.
Reimplemented in BasebandSPIIFXProtocolVersion2, and BasebandSPIIFXProtocolVersion1.
Definition at line 271 of file BasebandSPIIFXProtocol.cpp.
References DEBUG_INFO, fAllowSRDY, fSRDYEventSource, lowerMRDY(), SPI_ASSERT_SUCCESS, SPI_TRACE, and stopSRDYTimeoutTimer().
 {
         SPI_TRACE( DEBUG_INFO );
         fSRDYEventSource->disable();
         fAllowSRDY = false;
         lowerMRDY();
         stopSRDYTimeoutTimer();
         IOReturn ret = super::predeactivate();
         SPI_ASSERT_SUCCESS( ret );
         return kIOReturnSuccess;
 }
void BasebandSPIIFXProtocol::raiseMRDY (void) inline protected
Definition at line 60 of file BasebandSPIIFXProtocol.h.
References setMRDY().
Referenced by handleSRDYTimeoutAction().
         {
                 setMRDY( 1 );
         }
IOReturn BasebandSPIIFXProtocol::releaseEventSources (void) protected virtual
Definition at line 106 of file BasebandSPIIFXProtocol.cpp.
References DEBUG_INFO, fSRDYEventSource, fSRDYTimeoutEventSource, and SPI_TRACE.
Referenced by free().
 {
         SPI_TRACE( DEBUG_INFO );
         if ( fSRDYEventSource )
         {
                 fSRDYEventSource->release();
                 fSRDYEventSource = NULL;
         }
         if ( fSRDYTimeoutEventSource )
         {
                 fSRDYTimeoutEventSource->release();
                 fSRDYTimeoutEventSource = NULL;
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIIFXProtocol::releaseFunctions (void) protected virtual
Definition at line 150 of file BasebandSPIIFXProtocol.cpp.
References DEBUG_INFO, fMRDYFunction, fSRDYFunction, and SPI_TRACE.
Referenced by free().
 {
         SPI_TRACE( DEBUG_INFO );
         if ( fMRDYFunction )
         {
                 fMRDYFunction->release();
                 fMRDYFunction = NULL;
         }
         if ( fSRDYFunction )
         {
                 fSRDYFunction->release();
                 fSRDYFunction = NULL;
         }
         return kIOReturnSuccess;
 }
void BasebandSPIIFXProtocol::setMRDY (UInt32 value) protected
Definition at line 170 of file BasebandSPIIFXProtocol.cpp.
References DEBUG_SPEW, fMRDYFunction, fMRDYModificationTime, fMRDYState, BasebandSPIProtocol::getRemainingTimeLeftMicroSec(), BasebandSPIProtocol::getTime(), isSRDYStateHigh(), BasebandSPILogger::logGeneral(), BasebandSPILogger::logMRDY(), SPI_ASSERT_SUCCESS, and SPI_LOG.
Referenced by lowerMRDY(), and raiseMRDY().
 {
         bool bSRDYHigh = isSRDYStateHigh();
         SPI_LOG( DEBUG_SPEW, "To %u\n", value );
         if ( fMRDYState != value )
         {
                 fMRDYState = value;
                 uint64_t now;
                 getTime(&now);
                 // only have to delay if raising MRDY
                 if ( value )
                 {
                         UInt32 delta = getRemainingTimeLeftMicroSec( now, fMRDYModificationTime, 200 );
                         if ( delta )
{
 #if SPI_SRDY_DEBUG
                                 BasebandSPILogger::logGeneral( "MRDYDFR", delta, isSRDYStateHigh() );
 #else
                                 BasebandSPILogger::logGeneral( "MRDYDFR", delta );
 #endif
                                 IODelay( delta );
                                 getTime(&fMRDYModificationTime);
                         }
                         else {
                                 fMRDYModificationTime = now;
                         }
                 }
                 else {
                         fMRDYModificationTime = now;
                 }
                 if ( bSRDYHigh )
                 {
                         BasebandSPILogger::logMRDY( value , "SRDYHI" );
                 }
                 else
                 {
                         BasebandSPILogger::logMRDY( value , "SRDYLO" );
                 }
                 IOReturn ret = fMRDYFunction->callFunction( &fMRDYState );
                 SPI_ASSERT_SUCCESS( ret );
         }
         else
         {
                 if ( bSRDYHigh )
                 {
                         BasebandSPILogger::logMRDY( value, "same (SRDYHI)" );
                 }
                 else
                 {
                         BasebandSPILogger::logMRDY( value, "same (SRDYLO)" );
                 }
         }
 }
void BasebandSPIIFXProtocol::startSRDYTimeoutTimer (void) inline protected
Definition at line 69 of file BasebandSPIIFXProtocol.h.
References fSRDYTimeoutEventSource.
Referenced by handleSRDYTimeoutAction().
         {
                 fSRDYTimeoutEventSource->setTimeoutMS( kSRDYTimeoutInterval );
         }
void BasebandSPIIFXProtocol::stopSRDYTimeoutTimer (void) inline protected
Definition at line 74 of file BasebandSPIIFXProtocol.h.
References clearSRDYMissCount(), and fSRDYTimeoutEventSource.
Referenced by predeactivate().
         {
                 clearSRDYMissCount();
                 fSRDYTimeoutEventSource->cancelTimeout();
         }
Member Data Documentation
bool BasebandSPIIFXProtocol::fAllowSRDY private
Definition at line 111 of file BasebandSPIIFXProtocol.h.
Referenced by activate(), canHandleSRDY(), and predeactivate().
AppleARMFunction* BasebandSPIIFXProtocol::fMRDYFunction protected
Definition at line 100 of file BasebandSPIIFXProtocol.h.
Referenced by createFunctions(), init(), releaseFunctions(), and setMRDY().
uint64_t BasebandSPIIFXProtocol::fMRDYModificationTime protected
Definition at line 106 of file BasebandSPIIFXProtocol.h.
Referenced by init(), and setMRDY().
UInt32 BasebandSPIIFXProtocol::fMRDYState protected
Definition at line 108 of file BasebandSPIIFXProtocol.h.
Referenced by BasebandSPIIFXProtocolSnapshot::copyAsString(), createFunctions(), getSnapshot(), and setMRDY().
IOInterruptEventSource* BasebandSPIIFXProtocol::fSRDYEventSource protected
Definition at line 103 of file BasebandSPIIFXProtocol.h.
Referenced by activate(), createEventSources(), exitLowPower(), init(), predeactivate(), and releaseEventSources().
AppleARMFunction* BasebandSPIIFXProtocol::fSRDYFunction protected
Definition at line 101 of file BasebandSPIIFXProtocol.h.
Referenced by createFunctions(), getSnapshot(), init(), isSRDYStateHigh(), and releaseFunctions().
IOTimerEventSource* BasebandSPIIFXProtocol::fSRDYTimeoutEventSource protected
Definition at line 104 of file BasebandSPIIFXProtocol.h.
Referenced by createEventSources(), init(), releaseEventSources(), startSRDYTimeoutTimer(), and stopSRDYTimeoutTimer().
const UInt32 BasebandSPIIFXProtocol::kSRDYTimeoutInterval = 2*1000 static protected
Definition at line 23 of file BasebandSPIIFXProtocol.h.
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPIIFXProtocol.h
/BasebandSPI/BasebandSPIIFXProtocol.cpp