AppleS5LFamilyBasebandSPIController Class Reference
AppleS5LFamilyBasebandSPIController Class Reference abstract
#include <AppleS5LFamilyBasebandSPIController.h>
Inherits BasebandSPIController.
Inherited by AppleS5L8900XBasebandSPIController, and AppleS5L8920XBasebandSPIController.
Public Member Functions
virtual bool init (OSDictionary *dict)
virtual bool start (IOService *provider)
virtual void stop (IOService *provider)
Public Member Functions inherited from BasebandSPIController
IOReturn activate (BasebandSPIDevice *device, BasebandSPIProtocol *protocol)
void beginBlockInterrupt (void)
Disallow SPI-specific interrupts.
IOReturn cancelAll (void)
bool canStartTransfer (void) const
IOReturn configure (IODMACommand *receiveCommand, IODMACommand *transmitCommand, IOByteCount size)
IOReturn deactivate (void)
bool endBlockInterrupt (void)
IOReturn enterLowPower (void)
IOReturn exitLowPower (BasebandSPIDevice *device, BasebandSPIProtocol *protocol)
IOReturn getSnapshot (BasebandSPIControllerSnapshot **snapshot)
virtual IOWorkLoop * getWorkLoop (void) const
bool intendToInterrupt (void)
bool isEnteringLowPower (void) const
virtual IOService * probe (IOService *provider, SInt32 *score)
bool reportError (BasebandSPIReturn err, const char *details)
IOReturn startTransfer (void)
IOReturn unconfigure (void)
Protected Member Functions
bool clockEnabled (void) const
void enableClock (bool enable)
const char * getDebugName (void) const
virtual IOReturn loadConfiguration (void)
Parses through the configuration and extract necessary information.
UInt32 readReg32 (UInt32 offset)
virtual IOReturn takeSnapshot (const char *comment, BasebandSPIControllerSnapshot::PinState resetDetectState, BasebandSPIControllerSnapshot **snapshot)=0
void writeReg32 (UInt32 offset, UInt32 data)
Protected Member Functions inherited from BasebandSPIController
virtual IOReturn configureHardware (UInt32 dmaFlags, IOByteCount size)=0
void dumpRegisters (int level=DEBUG_SPEW)
virtual void dumpRegistersInternal (void)=0
const char * eventSourceAsString (IODMAEventSource *es) const
const char * getDebugName (void) const
IOReturn getNewSnapshot (const char *reason)
UInt32 getOverrideClockPeriod (void) const
virtual IOReturn preflightSetupHardware (void)=0
Do a preflight setup of the hardware.
virtual IOReturn startHardware (void)=0
Start the hardware for the transfer.
virtual IOReturn unconfigureHardware (void)=0
Power down the hardware.
virtual bool validateDeviceTypeAndChip (const char *deviceType, UInt32 chipRevision) const =0
Protected Attributes
UInt64 fNCLKFrequency
UInt64 fPCLKFrequency
Protected Attributes inherited from BasebandSPIController
IOCommandGate * fCommandGate
BasebandSPIConfig fConfiguration
IODMACommand * fCurrentReceiveCommand
IODMACommand * fCurrentSendCommand
BasebandSPIDevice * fDevice
BasebandSPIDiagnostics * fDiags
bool fEnteringLowPower
UInt32 fHardwareStateFlags
bool fInLowPower
volatile InterruptGuardState fInterruptGuard
UInt32 fPendingDMAs
IODMACommand * fPendingReceiveCommand
IODMACommand * fPendingSendCommand
BasebandSPIProtocol * fProtocol
AppleARMIODevice * fProvider
IODMAEventSource * fRxDMAES
BasebandSPIControllerSnapshot * fSavedSnapshot
State fState
State fStateBeforeLowPower
IOTimerEventSource * fTransferCompleteTimeout
IODMAEventSource * fTxDMAES
volatile UInt32 fVolatileHardwareStateFlags
IOWorkLoop * fWorkLoop
Private Member Functions
IOReturn configurePins (void)
IOReturn createFunctions (void)
OSDeclareAbstractStructors (AppleS5LFamilyBasebandSPIController)
IOReturn releaseFunctions (void)
Private Attributes
IOLogicalAddress fBaseAddress
bool fClockEnabled
IOMemoryMap * fMemoryMap
Additional Inherited Members
Public Types inherited from BasebandSPIController
enum DMAFlags { kNone = 0, kRxDMA = 1UL << 0, kTxDMA = 1UL << 1 }
Static Protected Member Functions inherited from BasebandSPIController
static const char * stateAsString (State state)
Detailed Description
Definition at line 18 of file AppleS5LFamilyBasebandSPIController.h.
Member Function Documentation
bool AppleS5LFamilyBasebandSPIController::clockEnabled (void) const inline protected
Definition at line 61 of file AppleS5LFamilyBasebandSPIController.h.
References DEBUG_SPEW, fClockEnabled, init(), SPI_LOG, start(), and stop().
         {
                 SPI_LOG( DEBUG_SPEW, "Clock enabled %u\n", fClockEnabled );
                 return fClockEnabled;
         }
IOReturn AppleS5LFamilyBasebandSPIController::configurePins (void) inline private
Definition at line 73 of file AppleS5LFamilyBasebandSPIController.cpp.
References DEBUG_CRITICAL, BasebandSPIController::fProvider, and SPI_LOG.
Referenced by getDebugName(), and start().
 {
         AppleARMFunction * function;
         // Reconfigure IPC_MOSI. iBoot sets it as input
         function = AppleARMFunction::withProvider(fProvider, "function-mosi");
         if (!function)
         {
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't get function-mosi\n" );
                 return kIOReturnError;
         }
         function->callFunction();
         function->release();
         return kIOReturnSuccess;
 }
IOReturn AppleS5LFamilyBasebandSPIController::createFunctions (void) inline private
Definition at line 92 of file AppleS5LFamilyBasebandSPIController.cpp.
Referenced by getDebugName(), and start().
 {
         return kIOReturnSuccess;
 }
void AppleS5LFamilyBasebandSPIController::enableClock (bool enable) inline protected
Definition at line 54 of file AppleS5LFamilyBasebandSPIController.h.
References DEBUG_SPEW, BasebandSPIController::fProvider, and SPI_LOG.
         {
                 SPI_LOG( DEBUG_SPEW, "Enable Clock from %u to %u\n", fClockEnabled, enable );
                 fProvider->enableDeviceClock( enable );
                 fClockEnabled = enable;
         }
const char* AppleS5LFamilyBasebandSPIController::getDebugName (void) const inline protected
Definition at line 33 of file AppleS5LFamilyBasebandSPIController.h.
References configurePins(), createFunctions(), loadConfiguration(), readReg32(), releaseFunctions(), takeSnapshot(), and writeReg32().
         {
                 return "AppleS5LFamilyBasebandSPIController";
         }
bool AppleS5LFamilyBasebandSPIController::init (OSDictionary * dict) virtual
Reimplemented from BasebandSPIController.
Definition at line 22 of file AppleS5LFamilyBasebandSPIController.cpp.
References fBaseAddress, fMemoryMap, fNCLKFrequency, and fPCLKFrequency.
Referenced by clockEnabled().
 {
         fMemoryMap                                              = NULL;
         fBaseAddress                                    = 0;
         fPCLKFrequency                                  = 0;
         fNCLKFrequency                                  = 0;
         bool ret = super::init( dict );
         if ( !ret )
         {
                 return ret;
         }
         return true;
 }
IOReturn AppleS5LFamilyBasebandSPIController::loadConfiguration (void) protected virtual
Parses through the configuration and extract necessary information.
Reimplemented from BasebandSPIController.
Reimplemented in AppleS5L8920XBasebandSPIController, and AppleS5L8900XBasebandSPIController.
Definition at line 102 of file AppleS5LFamilyBasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, DEBUG_SPEW, fBaseAddress, BasebandSPIController::fConfiguration, fMemoryMap, fNCLKFrequency, fPCLKFrequency, BasebandSPIController::fProvider, SPI_LOG, SPI_TRACE, BasebandSPIConfig::spiClockPeriod, and BasebandSPIConfig::spiWordSize.
Referenced by getDebugName().
 {
         IOReturn ret = super::loadConfiguration();
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         if ( !fConfiguration.spiClockPeriod )
         {
                 SPI_LOG( DEBUG_CRITICAL, "SPI clock period == 0\n" );
                 return kIOReturnBadArgument;
         }
         if ((((fNCLKFrequency * fConfiguration.spiClockPeriod) + 1000000000ULL - 1) / 1000000000ULL) > 2048) {
                 SPI_LOG( DEBUG_CRITICAL, "Invalid SPI clock period %u\n", fConfiguration.spiClockPeriod);
                 return kIOReturnBadArgument;
         }
         // S5L8920X supports only 8, 16 & 32 bit words
         switch ( fConfiguration.spiWordSize )
         {
                 case 8:
                 case 16:
                 case 32:
                         break;
                 default:
                         SPI_LOG( DEBUG_CRITICAL, "Invalid SPI word size %u\n", fConfiguration.spiWordSize);
                         return kIOReturnBadArgument;
         }
                 SPI_TRACE( DEBUG_SPEW );
         // get our clock frequencies
         fPCLKFrequency = fProvider->getClockFrequency("pclk");
         if (!fPCLKFrequency) return false;
         fNCLKFrequency = fProvider->getClockFrequency("nclk");
         if (!fNCLKFrequency) return false;
         // get our memory map and base address
         fMemoryMap = fProvider->mapDeviceMemoryWithIndex(0);
         if (!fMemoryMap) return false;
         fBaseAddress = fMemoryMap->getVirtualAddress();
         SPI_LOG( DEBUG_INFO, "baseAddress %p, physical %p\n", fBaseAddress,
                 fMemoryMap->getPhysicalAddress() );
         return kIOReturnSuccess;
 }
AppleS5LFamilyBasebandSPIController::OSDeclareAbstractStructors (AppleS5LFamilyBasebandSPIController) private
UInt32 AppleS5LFamilyBasebandSPIController::readReg32 (UInt32 offset) inline protected
Definition at line 74 of file AppleS5LFamilyBasebandSPIController.h.
References fBaseAddress.
Referenced by getDebugName().
 {
         return *(volatile UInt32 *)( fBaseAddress + offset);
 }
IOReturn AppleS5LFamilyBasebandSPIController::releaseFunctions (void) inline private
Definition at line 97 of file AppleS5LFamilyBasebandSPIController.cpp.
Referenced by getDebugName(), and stop().
 {
         return kIOReturnSuccess;
 }
bool AppleS5LFamilyBasebandSPIController::start (IOService * provider) virtual
Reimplemented from BasebandSPIController.
Reimplemented in AppleS5L8920XBasebandSPIController, and AppleS5L8900XBasebandSPIController.
Definition at line 40 of file AppleS5LFamilyBasebandSPIController.cpp.
References configurePins(), createFunctions(), DEBUG_INFO, and SPI_TRACE.
Referenced by clockEnabled().
 {
         SPI_TRACE( DEBUG_INFO );
         if ( !super::start(provider) )
         {
                 return false;
         }
         IOReturn ret;
         ret = configurePins();
         if ( ret != kIOReturnSuccess )
         {
                 return false;
         }
         ret = createFunctions();
         if ( ret != kIOReturnSuccess )
         {
                 return false;
         }
         return true;
 }
void AppleS5LFamilyBasebandSPIController::stop (IOService * provider) virtual
Reimplemented from BasebandSPIController.
Definition at line 66 of file AppleS5LFamilyBasebandSPIController.cpp.
References releaseFunctions().
Referenced by clockEnabled().
 {
         releaseFunctions();
         super::stop( provider );
 }
virtual IOReturn AppleS5LFamilyBasebandSPIController::takeSnapshot (const char * comment, BasebandSPIControllerSnapshot::PinState resetDetectState, BasebandSPIControllerSnapshot ** snapshot) protected pure virtual
Implements BasebandSPIController.
Implemented in AppleS5L8920XBasebandSPIController, and AppleS5L8900XBasebandSPIController.
Referenced by getDebugName().
void AppleS5LFamilyBasebandSPIController::writeReg32 (UInt32 offset, UInt32 data) inline protected
Definition at line 79 of file AppleS5LFamilyBasebandSPIController.h.
References fBaseAddress.
Referenced by getDebugName().
 {
         *(volatile UInt32 *)( fBaseAddress + offset) = data;
 }
Member Data Documentation
IOLogicalAddress AppleS5LFamilyBasebandSPIController::fBaseAddress private
Definition at line 24 of file AppleS5LFamilyBasebandSPIController.h.
Referenced by init(), loadConfiguration(), readReg32(), and writeReg32().
bool AppleS5LFamilyBasebandSPIController::fClockEnabled private
Definition at line 26 of file AppleS5LFamilyBasebandSPIController.h.
Referenced by clockEnabled().
IOMemoryMap* AppleS5LFamilyBasebandSPIController::fMemoryMap private
Definition at line 23 of file AppleS5LFamilyBasebandSPIController.h.
Referenced by init(), and loadConfiguration().
UInt64 AppleS5LFamilyBasebandSPIController::fNCLKFrequency protected
Definition at line 30 of file AppleS5LFamilyBasebandSPIController.h.
Referenced by init(), and loadConfiguration().
UInt64 AppleS5LFamilyBasebandSPIController::fPCLKFrequency protected
Definition at line 29 of file AppleS5LFamilyBasebandSPIController.h.
Referenced by init(), and loadConfiguration().
The documentation for this class was generated from the following files:
/BasebandSPI/AppleS5LFamilyBasebandSPIController.h
/BasebandSPI/AppleS5LFamilyBasebandSPIController.cpp