BasebandSPIController Class Reference
BasebandSPIController Class Reference abstract
#include <BasebandSPIController.h>
Inherits IOService.
Inherited by AppleS5LFamilyBasebandSPIController.
Public Types
enum DMAFlags { kNone = 0, kRxDMA = 1UL << 0, kTxDMA = 1UL << 1 }
Public Member Functions
IOReturn activate (BasebandSPIDevice *device, BasebandSPIProtocol *protocol)
void beginBlockInterrupt (void)
Disallow SPI-specific interrupts.
IOReturn cancelAll (void)
bool canStartTransfer (void) const
IOReturn configure (IODMACommand *receiveCommand, IODMACommand *transmitCommand, IOByteCount size)
IOReturn deactivate (void)
bool endBlockInterrupt (void)
IOReturn enterLowPower (void)
IOReturn exitLowPower (BasebandSPIDevice *device, BasebandSPIProtocol *protocol)
IOReturn getSnapshot (BasebandSPIControllerSnapshot **snapshot)
virtual IOWorkLoop * getWorkLoop (void) const
virtual bool init (OSDictionary *dict)
bool intendToInterrupt (void)
bool isEnteringLowPower (void) const
virtual IOService * probe (IOService *provider, SInt32 *score)
bool reportError (BasebandSPIReturn err, const char *details)
virtual bool start (IOService *provider)
IOReturn startTransfer (void)
virtual void stop (IOService *provider)
IOReturn unconfigure (void)
Protected Member Functions
virtual IOReturn configureHardware (UInt32 dmaFlags, IOByteCount size)=0
void dumpRegisters (int level=DEBUG_SPEW)
virtual void dumpRegistersInternal (void)=0
const char * eventSourceAsString (IODMAEventSource *es) const
const char * getDebugName (void) const
IOReturn getNewSnapshot (const char *reason)
UInt32 getOverrideClockPeriod (void) const
virtual IOReturn loadConfiguration (void)
Parses through the configuration and extract necessary information.
virtual IOReturn preflightSetupHardware (void)=0
Do a preflight setup of the hardware.
virtual IOReturn startHardware (void)=0
Start the hardware for the transfer.
virtual IOReturn takeSnapshot (const char *comment, BasebandSPIControllerSnapshot::PinState resetDetectState, BasebandSPIControllerSnapshot **snapshot)=0
virtual IOReturn unconfigureHardware (void)=0
Power down the hardware.
virtual bool validateDeviceTypeAndChip (const char *deviceType, UInt32 chipRevision) const =0
Static Protected Member Functions
static const char * stateAsString (State state)
Protected Attributes
IOCommandGate * fCommandGate
BasebandSPIConfig fConfiguration
IODMACommand * fCurrentReceiveCommand
IODMACommand * fCurrentSendCommand
BasebandSPIDevice * fDevice
BasebandSPIDiagnostics * fDiags
bool fEnteringLowPower
UInt32 fHardwareStateFlags
bool fInLowPower
volatile InterruptGuardState fInterruptGuard
UInt32 fPendingDMAs
IODMACommand * fPendingReceiveCommand
IODMACommand * fPendingSendCommand
BasebandSPIProtocol * fProtocol
AppleARMIODevice * fProvider
IODMAEventSource * fRxDMAES
BasebandSPIControllerSnapshot * fSavedSnapshot
State fState
State fStateBeforeLowPower
IOTimerEventSource * fTransferCompleteTimeout
IODMAEventSource * fTxDMAES
volatile UInt32 fVolatileHardwareStateFlags
IOWorkLoop * fWorkLoop
Private Types
enum InterruptGuardState { kOpen = 0, kBlocked = 1, kBlockedAndRejected = 2 }
enum State { kStateActive, kStateInactive, kStateDeactivating }
enum VolatileHardwareStateFlags { kFlagHardwareActive = 1UL << 0, kFlagTransferActive = 1UL << 1, kFlagError = 1UL << 2 }
Private Member Functions
IOReturn cancelDMA (IODMAEventSource *es)
void cancelTransferCompleteTimer (void)
void changeState (State newState)
IOReturn configureDMA (IODMACommand *command, IOByteCount size, DMAFlags what)
IOReturn createEventSources (void)
void dmaCompleteAction (IODMAEventSource *es, IODMACommand *command, IOReturn status, IOByteCount byteCount)
void dmaNotifyAction (IODMAEventSource *es, IODMACommand *command, IOReturn status, IOByteCount byteCount)
IOReturn handleCancelledRxDMACommand (IODMACommand *command)
IOReturn handleCancelledTxDMACommand (IODMACommand *command)
IOReturn handleDMACompleteOnActive (IODMAEventSource *eventSource, IODMACommand *command, IOReturn status, IOByteCount byteCount)
IOReturn handleDMACompleteOnCancel (IODMAEventSource *eventSource, IODMACommand *command, IOReturn status, IOByteCount byteCount)
IOReturn handleDMACompleteOnError (IODMAEventSource *eventSource, IODMACommand *command, IOReturn status, IOByteCount byteCount)
OSDeclareAbstractStructors (BasebandSPIController)
IOReturn queueDMAWithCommand (IODMAEventSource *es, IODirection direction, IODMACommand *command, IOByteCount size)
IOReturn releaseEventSources (void)
void startTransferCompleteTimer (void)
void transferCompleteTimeoutAction (IOTimerEventSource *es)
IOReturn validateHardware (void)
IOReturn waitForDMACompletion (void)
IOReturn waitForStateChange (State expectedState)
Detailed Description
Definition at line 18 of file BasebandSPIController.h.
Member Enumeration Documentation
enum BasebandSPIController::DMAFlags
Enumerator
kNone
kRxDMA
kTxDMA
Definition at line 23 of file BasebandSPIController.h.
         {
                 kNone            = 0,
                 kRxDMA           = 1UL << 0,
                 kTxDMA           = 1UL << 1,
         }
enum BasebandSPIController::InterruptGuardState private
Enumerator
kOpen
kBlocked
kBlockedAndRejected
Definition at line 47 of file BasebandSPIController.h.
         {
                 kOpen = 0,
                 kBlocked = 1,
                 kBlockedAndRejected = 2
         }
enum BasebandSPIController::State private
Enumerator
kStateActive
kStateInactive
kStateDeactivating
Definition at line 32 of file BasebandSPIController.h.
         {
                 kStateActive,
                 kStateInactive,
                 kStateDeactivating
         } State;
enum BasebandSPIController::VolatileHardwareStateFlags private
Enumerator
kFlagHardwareActive
kFlagTransferActive
kFlagError
Definition at line 39 of file BasebandSPIController.h.
         {
                 kFlagHardwareActive             = 1UL << 0,
                 kFlagTransferActive             = 1UL << 1,
                 kFlagError                              = 1UL << 2
         }
Member Function Documentation
IOReturn BasebandSPIController::activate (BasebandSPIDevice * device, BasebandSPIProtocol * protocol)
Definition at line 342 of file BasebandSPIController.cpp.
References changeState(), DEBUG_CRITICAL, fDevice, fProtocol, fState, getWorkLoop(), BasebandSPIProtocol::isSRDYStateHigh(), kStateActive, kStateInactive, BasebandSPILogger::logGeneral(), SPI_ASSERT, SPI_LOG, and stateAsString().
Referenced by dumpRegisters(), and exitLowPower().
 {
         SPI_ASSERT( getWorkLoop()->inGate(), ==, true );
         switch ( fState )
         {
         case kStateInactive:
                 break;
         default:
                 SPI_LOG( DEBUG_CRITICAL, "Can't activate when state is %s\n",
                         stateAsString( fState ) );
                 return kIOReturnNotPermitted;
         }
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "AC", 0, (protocol) ? protocol->isSRDYStateHigh() : false );
 #else
         BasebandSPILogger::logGeneral( "AC", 0 );
 #endif
         changeState( kStateActive );
         fDevice                 = device;
         fProtocol               = protocol;
         return kIOReturnSuccess;
 }
void BasebandSPIController::beginBlockInterrupt (void)
Disallow SPI-specific interrupts.
Definition at line 1144 of file BasebandSPIController.cpp.
References fInterruptGuard, kBlocked, and BasebandSPILogger::logGeneral().
Referenced by canStartTransfer(), deactivate(), and transferCompleteTimeoutAction().
 {
 #if SPI_USE_REAL_ISR
         // assumption: assignment is atomic here
         fInterruptGuard = kBlocked;
         BasebandSPILogger::logGeneral( "DSRDY", 0 );
 #endif
 }
IOReturn BasebandSPIController::cancelAll (void)
Definition at line 682 of file BasebandSPIController.cpp.
References cancelDMA(), DEBUG_SPEW, fPendingDMAs, fRxDMAES, fTxDMAES, kRxDMA, kTxDMA, and SPI_TRACE.
Referenced by deactivate(), dumpRegisters(), and transferCompleteTimeoutAction().
 {
         SPI_TRACE( DEBUG_SPEW );
         IOReturn finalRet = kIOReturnSuccess;
         IOReturn ret;
         if ( fPendingDMAs & kRxDMA )
         {
                 ret = cancelDMA( fRxDMAES );
                 if ( ret != kIOReturnSuccess )
                 {
                         finalRet = ret;
                 }
         }
         if ( fPendingDMAs & kTxDMA )
         {
                 ret = cancelDMA( fTxDMAES );
                 if ( ret != kIOReturnSuccess )
                 {
                         finalRet = ret;
                 }
         }
         return finalRet;
 }
IOReturn BasebandSPIController::cancelDMA (IODMAEventSource * es) inline private
Definition at line 998 of file BasebandSPIController.cpp.
References DEBUG_INFO, and SPI_TRACE.
Referenced by cancelAll().
 {
         SPI_TRACE( DEBUG_INFO );
         es->stopDMACommand( false );
         return kIOReturnSuccess;
 }
void BasebandSPIController::cancelTransferCompleteTimer (void) inline private
Definition at line 1029 of file BasebandSPIController.cpp.
References fTransferCompleteTimeout.
Referenced by handleDMACompleteOnActive(), and handleDMACompleteOnCancel().
 {
         fTransferCompleteTimeout->disable();
         fTransferCompleteTimeout->cancelTimeout();
 }
bool BasebandSPIController::canStartTransfer (void) const inline
Definition at line 149 of file BasebandSPIController.h.
References beginBlockInterrupt(), configureHardware(), endBlockInterrupt(), fEnteringLowPower, fVolatileHardwareStateFlags, getSnapshot(), kFlagHardwareActive, kFlagTransferActive, loadConfiguration(), preflightSetupHardware(), startHardware(), unconfigureHardware(), and validateDeviceTypeAndChip().
         {
                 UInt32 flags = fVolatileHardwareStateFlags;
                 return ( flags & kFlagHardwareActive )
                         && !( flags & kFlagTransferActive )
                         && !fEnteringLowPower;
         }
void BasebandSPIController::changeState (State newState) inline private
Definition at line 65 of file BasebandSPIController.cpp.
References DEBUG_INFO, fCommandGate, fState, SPI_LOG, and stateAsString().
Referenced by activate(), and deactivate().
 {
         SPI_LOG( DEBUG_INFO, "State goes from %s to %s\n",
                 stateAsString( fState ), stateAsString( newState ) );
         fState = newState;
         fCommandGate->commandWakeup( &fState );
 }
IOReturn BasebandSPIController::configure (IODMACommand * receiveCommand, IODMACommand * transmitCommand, IOByteCount size)
Definition at line 561 of file BasebandSPIController.cpp.
References configureDMA(), configureHardware(), DEBUG_SPEW, dumpRegisters(), fHardwareStateFlags, fPendingDMAs, fProtocol, fState, fVolatileHardwareStateFlags, BasebandSPIProtocol::isSRDYStateHigh(), kBasebandSPIReturnTransferActive, kFlagHardwareActive, kFlagTransferActive, kRxDMA, kStateActive, kTxDMA, BasebandSPILogger::logGeneral(), SPI_ASSERT, SPI_ASSERT_SUCCESS, SPI_LOG, and SPI_TRACE.
Referenced by dumpRegisters().
 {
         SPI_TRACE( DEBUG_SPEW );
 #if SPI_PEDANTIC_ASSERT
         SPI_ASSERT( fState, ==, kStateActive );
 #endif
         UInt32 currentVolatileFlags = fVolatileHardwareStateFlags;
         SPI_LOG( DEBUG_SPEW, "currentVolatile = %p, hardware state = %p, rx = %p, tx = %p\n",
                 currentVolatileFlags, fHardwareStateFlags, receiveCommand, transmitCommand );
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "PSTAT", ( currentVolatileFlags <<  16 )  | fHardwareStateFlags, ((fProtocol) ? fProtocol->isSRDYStateHigh() : false) );
 #else
         BasebandSPILogger::logGeneral( "PSTAT", ( currentVolatileFlags <<  16 )  | fHardwareStateFlags );
 #endif
         IOReturn ret;
         if ( currentVolatileFlags & kFlagTransferActive )
         {
                 // don't allow it because we're currently in the middle of a transfer
                 ret = kBasebandSPIReturnTransferActive;
 #if SPI_SRDY_DEBUG
                 BasebandSPILogger::logGeneral( "PREP", 4, ((fProtocol) ? fProtocol->isSRDYStateHigh() : false) );
 #else
                 BasebandSPILogger::logGeneral( "PREP", 4 );
 #endif
         }
         else
         {
                 if ( transmitCommand )
                 {
                         ret = configureDMA( transmitCommand, size, kTxDMA );
 #if SPI_PEDANTIC_ASSERT
                         SPI_ASSERT_SUCCESS( ret );
 #else
                         (void)ret;
 #endif
                 }
                 if ( receiveCommand )
                 {
                         ret = configureDMA( receiveCommand, size, kRxDMA );
 #if SPI_PEDANTIC_ASSERT
                         SPI_ASSERT_SUCCESS( ret );
 #else
                         (void)ret;
 #endif
                 }
 #if SPI_SRDY_DEBUG
                 BasebandSPILogger::logGeneral( "PREP", 2, ((fProtocol) ? fProtocol->isSRDYStateHigh() : false) );
 #else
                 BasebandSPILogger::logGeneral( "PREP", 2 );
 #endif
                 ret = configureHardware( fPendingDMAs, size );
                 if ( ret != kIOReturnSuccess )
                 {
                         goto bail;
                 }
                 currentVolatileFlags |= kFlagHardwareActive;
         }
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "PREP", 3, ((fProtocol) ? fProtocol->isSRDYStateHigh() : false) );
 #else
         BasebandSPILogger::logGeneral( "PREP", 3 );
 #endif
         // Set the volatile flags to the current one
         fVolatileHardwareStateFlags     = currentVolatileFlags;
 bail:
         dumpRegisters( DEBUG_SPEW );
         return ret;
 }
IOReturn BasebandSPIController::configureDMA (IODMACommand * command, IOByteCount size, DMAFlags what) private
Definition at line 521 of file BasebandSPIController.cpp.
References DEBUG_SPEW, fPendingDMAs, fPendingReceiveCommand, fPendingSendCommand, fProtocol, fRxDMAES, fTxDMAES, BasebandSPIProtocol::isSRDYStateHigh(), kBasebandSPIReturnAlreadyQueued, kRxDMA, kTxDMA, BasebandSPILogger::logGeneral(), queueDMAWithCommand(), and SPI_TRACE.
Referenced by configure().
 {
         SPI_TRACE( DEBUG_SPEW );
         if ( fPendingDMAs & what )
         {
                 return kBasebandSPIReturnAlreadyQueued;
         }
         fPendingDMAs |= what;
         IODMAEventSource * es;
         IODirection direction;
         switch ( what )
         {
         case kTxDMA:
                 fPendingSendCommand                     = command;
                 es                                                      = fTxDMAES;
                 direction                                       = kIODirectionOut;
                 break;
         case kRxDMA:
         default:
                 fPendingReceiveCommand          = command;
                 es                                                      = fRxDMAES;
                 direction                                       = kIODirectionIn;
                 break;
         }
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "PREP", 1 | ( what << 8 ), ((fProtocol) ? fProtocol->isSRDYStateHigh() : false) );
 #else
         BasebandSPILogger::logGeneral( "PREP", 1 | ( what << 8 ) );
 #endif
         IOReturn ret;
         ret = queueDMAWithCommand( es, direction, command, size );
         return ret;
 }
virtual IOReturn BasebandSPIController::configureHardware (UInt32 dmaFlags, IOByteCount size) protected pure virtual
Power up the hardware
Parameters
dmaFlags Flags saying which DMAs we want
size The transfer size
Implemented in AppleS5L8920XBasebandSPIController, and AppleS5L8900XBasebandSPIController.
Referenced by canStartTransfer(), and configure().
IOReturn BasebandSPIController::createEventSources (void) inline private
Definition at line 711 of file BasebandSPIController.cpp.
References DEBUG_CRITICAL, dmaCompleteAction(), dmaNotifyAction(), fProvider, fRxDMAES, fTransferCompleteTimeout, fTxDMAES, getWorkLoop(), SPI_LOG, and transferCompleteTimeoutAction().
Referenced by start().
 {
         IOReturn ret;
         IODMAEventAction notifyAction;
 #if SPI_HANDLE_DMA_NOTIFY
         notifyAction = OSMemberFunctionCast( IODMAEventAction, this, &BasebandSPIController::dmaNotifyAction );
 #else
         notifyAction = NULL;
 #endif
         // Only operate in DMA mode
         fTxDMAES = IODMAEventSource::dmaEventSource(this, fProvider, OSMemberFunctionCast(IODMAEventAction, this,
                 &BasebandSPIController::dmaCompleteAction), notifyAction, 0);
         if ( !fTxDMAES )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't get TxDMA Event source\n" );
                 return kIOReturnError;
         }
         ret = getWorkLoop()->addEventSource( fTxDMAES );
         if ( ret != kIOReturnSuccess )
         {
                 fTxDMAES->release();
                 fTxDMAES = NULL;
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't add source for TxDMA, ret = %p\n", ret );
                 return ret;
         }
         fRxDMAES = IODMAEventSource::dmaEventSource(this, fProvider, OSMemberFunctionCast(IODMAEventAction, this,
                 &BasebandSPIController::dmaCompleteAction), notifyAction, 1);
         if ( !fRxDMAES )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't get RxDMA Event source\n" );
                 return kIOReturnError;
         }
         ret = getWorkLoop()->addEventSource( fRxDMAES );
         if ( ret != kIOReturnSuccess )
         {
                 fRxDMAES->release();
                 fRxDMAES = NULL;
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't add source for RxDMA, ret = %p\n", ret );
                 return ret;
         }
         fTransferCompleteTimeout = IOTimerEventSource::timerEventSource(this, OSMemberFunctionCast(IOTimerEventSource::Action,
                 this, &BasebandSPIController::transferCompleteTimeoutAction ));
         if ( !fTransferCompleteTimeout )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't get Transfer complete timeout event source\n" );
                 return kIOReturnError;
         }
         ret = getWorkLoop()->addEventSource( fTransferCompleteTimeout );
         if ( ret != kIOReturnSuccess )
         {
                 fTransferCompleteTimeout->release();
                 fTransferCompleteTimeout = NULL;
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't add source for SRDY Timeout, ret = %p\n", ret );
                 return ret;
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIController::deactivate (void)
Definition at line 371 of file BasebandSPIController.cpp.
References beginBlockInterrupt(), cancelAll(), changeState(), DEBUG_CRITICAL, endBlockInterrupt(), fDevice, fInLowPower, fProtocol, fState, getWorkLoop(), BasebandSPIProtocol::isSRDYStateHigh(), kStateActive, kStateDeactivating, kStateInactive, BasebandSPILogger::logGeneral(), SPI_ASSERT, SPI_ASSERT_SUCCESS, SPI_LOG, stateAsString(), unconfigure(), and waitForDMACompletion().
Referenced by dumpRegisters(), and enterLowPower().
 {
         SPI_ASSERT( getWorkLoop()->inGate(), ==, true );
         switch ( fState )
         {
         case kStateActive:
                 break;
         default:
                 SPI_LOG( DEBUG_CRITICAL, "State is %s, clearing low power state\n",
                         stateAsString( fState ) );
                 // we must clear this anyway, if we are in low power, we
                 // are in the inactive state, but the fInLowPower flag is true
                 // so we need to clear it since we may close down SPI before we
                 // get the exit low power call from the system
                 fInLowPower = false;
                 return kIOReturnSuccess;
         }
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "DE", 0, fProtocol->isSRDYStateHigh() );
 #else
         BasebandSPILogger::logGeneral( "DE", 0 );
 #endif
         beginBlockInterrupt();
         IOReturn ret;
         ret = unconfigure();
         if ( ret != kIOReturnSuccess )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Unconfiguring failed, ret = %p\n", ret );
         }
         endBlockInterrupt();
         changeState( kStateDeactivating );
         //BasebandSPILogger::report();
         //BasebandSPILogger::clear();
         ret = cancelAll();
         SPI_ASSERT_SUCCESS( ret );
         ret = waitForDMACompletion();
         SPI_ASSERT_SUCCESS( ret );
         changeState( kStateInactive );
         fDevice                 = NULL;
         fProtocol               = NULL;
         fInLowPower             = false;
         return ret;
 }
void BasebandSPIController::dmaCompleteAction (IODMAEventSource * es, IODMACommand * command, IOReturn status, IOByteCount byteCount) private
Definition at line 931 of file BasebandSPIController.cpp.
References DEBUG_INFO, DEBUG_SPEW, dumpRegisters(), eventSourceAsString(), fPendingDMAs, fRxDMAES, fVolatileHardwareStateFlags, handleDMACompleteOnActive(), handleDMACompleteOnCancel(), handleDMACompleteOnError(), kFlagError, kFlagTransferActive, kRxDMA, kTxDMA, BasebandSPILogger::logDMACancel(), BasebandSPILogger::logDMAComplete(), BasebandSPILogger::logDMAError(), SPI_LOG, and SPI_TRACE.
Referenced by createEventSources().
 {
         SPI_TRACE( DEBUG_SPEW );
         const char * eventSourceStr = eventSourceAsString( es );
         SPI_LOG( DEBUG_SPEW, "es = %p, command = %p, status = %p, bytecount = %p, pending DMAs %p, (%s)\n",
                 es, command, status, byteCount, fPendingDMAs, eventSourceStr );
         dumpRegisters();
         if ( es == fRxDMAES )
         {
                 fPendingDMAs &= ~ kRxDMA;
         }
         else
         {
                 fPendingDMAs &= ~ kTxDMA;
         }
         SPI_LOG( DEBUG_SPEW, "Pending DMAs = %p\n", fPendingDMAs );
         UInt32 flags = fVolatileHardwareStateFlags;
         if ( flags & kFlagTransferActive )
         {
                 BasebandSPILogger::logDMAComplete( eventSourceStr );
                 handleDMACompleteOnActive( es, (IODMACommand *)command, status, byteCount );
         }
         else if ( flags & kFlagError )
         {
                 SPI_LOG( DEBUG_SPEW, "In DMA Error\n" );
                 BasebandSPILogger::logDMAError( eventSourceStr );
                 handleDMACompleteOnError( es, (IODMACommand *)command, status, byteCount );
         }
         else
         {
                 SPI_LOG( DEBUG_INFO, "Received cancelled DMA command\n" );
                 BasebandSPILogger::logDMACancel( eventSourceStr );
                 handleDMACompleteOnCancel( es, (IODMACommand *)command, status, byteCount );
         }
 }
void BasebandSPIController::dmaNotifyAction (IODMAEventSource * es, IODMACommand * command, IOReturn status, IOByteCount byteCount) private
Definition at line 811 of file BasebandSPIController.cpp.
References DEBUG_SPEW, eventSourceAsString(), fPendingDMAs, SPI_LOG, and SPI_TRACE.
Referenced by createEventSources().
 {
         SPI_TRACE( DEBUG_SPEW );
         SPI_LOG( DEBUG_SPEW, "es = %p (%s), command = %p, status = %p, byteCount = %p,  pending DMAs = %p\n",
                 es, eventSourceAsString( es ), command, status, byteCount, fPendingDMAs );
 }
void BasebandSPIController::dumpRegisters (int level = DEBUG_SPEW) inline protected
Definition at line 109 of file BasebandSPIController.h.
References activate(), cancelAll(), configure(), deactivate(), DEBUG_LEVEL, dumpRegistersInternal(), enterLowPower(), eventSourceAsString(), exitLowPower(), getNewSnapshot(), reportError(), startTransfer(), takeSnapshot(), and unconfigure().
Referenced by configure(), dmaCompleteAction(), startTransfer(), and unconfigure().
         {
                 if ((level) <= DEBUG_LEVEL)
                 {
                         dumpRegistersInternal();
                 }
         }
virtual void BasebandSPIController::dumpRegistersInternal (void) protected pure virtual
Implemented in AppleS5L8920XBasebandSPIController, and AppleS5L8900XBasebandSPIController.
Referenced by dumpRegisters().
bool BasebandSPIController::endBlockInterrupt (void)
Allow SPI-specific interrupts to fisre again
Returns
True if we missed an interrupt while we blocked it
Definition at line 1153 of file BasebandSPIController.cpp.
References fInterruptGuard, kBlocked, kOpen, and BasebandSPILogger::logGeneral().
Referenced by canStartTransfer(), deactivate(), and transferCompleteTimeoutAction().
 {
 #if SPI_USE_REAL_ISR
         // OSCompareAndSwap will return false if the guard isn't 1, in which case we know an SRDY interrupt came by and was turned away
         bool pending = !OSCompareAndSwap( kBlocked, kOpen, (volatile UInt32 *)&fInterruptGuard );
         BasebandSPILogger::logGeneral( "ESRDY", pending );
         return pending;
 #else
         return false;
 #endif
 }
IOReturn BasebandSPIController::enterLowPower (void)
Definition at line 452 of file BasebandSPIController.cpp.
References deactivate(), DEBUG_INFO, fEnteringLowPower, fInLowPower, fState, fStateBeforeLowPower, kStateActive, kStateDeactivating, kStateInactive, SPI_ASSERT, SPI_ASSERT_SUCCESS, SPI_TRACE, waitForDMACompletion(), and waitForStateChange().
Referenced by dumpRegisters().
 {
         SPI_TRACE( DEBUG_INFO );
         SPI_ASSERT( fInLowPower, ==, false );
         fEnteringLowPower = true;
         switch( fState )
         {
         case kStateActive:
                 fStateBeforeLowPower = fState;
                 deactivate();
                 break;
         case kStateDeactivating:
                 {
                         IOReturn ret = waitForDMACompletion();
                         SPI_ASSERT_SUCCESS( ret );
                         ret = waitForStateChange( kStateDeactivating );
                         SPI_ASSERT_SUCCESS( ret );
                         // in the very unlikely event we went active again, we need to tear down
                         // and break
                         if ( fState == kStateActive )
{
                                 fStateBeforeLowPower = fState;
                                 deactivate();
                                 break;
                         }
                 }
                 // fall through
         case kStateInactive:
                 fStateBeforeLowPower = fState;
                 break;
         }
         fEnteringLowPower                       = false;
         fInLowPower                             = true;
         return kIOReturnSuccess;
 }
const char * BasebandSPIController::eventSourceAsString (IODMAEventSource * es) const protected
Definition at line 34 of file BasebandSPIController.cpp.
References fProtocol, fRxDMAES, fTxDMAES, and BasebandSPIProtocol::isSRDYStateHigh().
Referenced by dmaCompleteAction(), dmaNotifyAction(), dumpRegisters(), and queueDMAWithCommand().
 {
         bool bSRDYHigh = (fProtocol) ? fProtocol->isSRDYStateHigh() : false;
         if ( es == fTxDMAES )
         {
                 if ( bSRDYHigh )
                 {
                         return ( "Tx DMA (SRDYHI)" );
                 }
                 else
                 {
                         return ( "Tx DMA (SRDYLO)" );
                 }
         }
         else if ( es == fRxDMAES )
         {
                 if ( bSRDYHigh )
                 {
                         return ( "Rx DMA (SRDYHI)" );
                 }
                 else
                 {
                         return ( "Rx DMA (SRDYLO)" );
                 }
         }
         else
         {
                 return "Dunno";
         }
 }
IOReturn BasebandSPIController::exitLowPower (BasebandSPIDevice * device, BasebandSPIProtocol * protocol)
Definition at line 497 of file BasebandSPIController.cpp.
References activate(), DEBUG_INFO, fInLowPower, fState, fStateBeforeLowPower, kStateActive, SPI_ASSERT, SPI_ASSERT_SUCCESS, and SPI_TRACE.
Referenced by dumpRegisters().
 {
         SPI_TRACE( DEBUG_INFO );
         SPI_ASSERT( fInLowPower, ==, true );
         fInLowPower     = false;
         switch( fStateBeforeLowPower )
         {
         case kStateActive:
                 {
                         IOReturn ret = activate( device, protocol );
                         SPI_ASSERT_SUCCESS( ret );
                         fState  = fStateBeforeLowPower;
                 }
                 break;
         default:
                 break;
         }
         return kIOReturnSuccess;
 }
const char* BasebandSPIController::getDebugName (void) const inline protected
Definition at line 104 of file BasebandSPIController.h.
         {
                 return "BasebandSPIController";
         }
IOReturn BasebandSPIController::getNewSnapshot (const char * reason) protected
Definition at line 1195 of file BasebandSPIController.cpp.
References fProtocol, fSavedSnapshot, BasebandSPIProtocol::getSnapshot(), BasebandSPIControllerSnapshot::injectProtocolSnapshot(), BasebandSPIControllerSnapshot::kDunno, and takeSnapshot().
Referenced by dumpRegisters(), getSnapshot(), and reportError().
 {
         IOReturn ret;
         // We will always report unknown for the reset state with <rdar://problem/9457884>
         BasebandSPIControllerSnapshot::PinState resetDetectState = BasebandSPIControllerSnapshot::kDunno;
         ret = takeSnapshot( reason, resetDetectState, &fSavedSnapshot );
         if ( ret == kIOReturnSuccess )
         {
                 if ( fProtocol )
                 {
                         fSavedSnapshot->injectProtocolSnapshot( fProtocol->getSnapshot() );
                 }
         }
         return ret;
 }
UInt32 BasebandSPIController::getOverrideClockPeriod (void) const protected
Definition at line 1165 of file BasebandSPIController.cpp.
 {
         static const char * kSCLKPeriodOverrideKey = "baseband-spi-sclk-period";
         UInt32 period = 0;
         PE_parse_boot_argn( kSCLKPeriodOverrideKey, &period, sizeof( period ) );
         return period;
 }
IOReturn BasebandSPIController::getSnapshot (BasebandSPIControllerSnapshot ** snapshot)
Definition at line 1175 of file BasebandSPIController.cpp.
References DEBUG_CRITICAL, fSavedSnapshot, getNewSnapshot(), and SPI_LOG.
Referenced by canStartTransfer().
 {
         if ( !fSavedSnapshot )
         {
                 IOReturn ret = getNewSnapshot( "snapshot" );
                 if ( ret != kIOReturnSuccess )
                 {
                         SPI_LOG( DEBUG_CRITICAL, "Failed to create new snapshot, ret = %p\n", ret );
                         *snapshot = NULL;
                         return ret;
                 }
         }
         *snapshot               = fSavedSnapshot;
         fSavedSnapshot  = NULL;
         return kIOReturnSuccess;
 }
IOWorkLoop * BasebandSPIController::getWorkLoop (void) const virtual
Definition at line 233 of file BasebandSPIController.cpp.
References fWorkLoop.
Referenced by activate(), createEventSources(), deactivate(), BasebandSPIProtocol::getWorkLoop(), BasebandSPIProtocol::init(), releaseEventSources(), start(), and stop().
 {
         return fWorkLoop;
 }
IOReturn BasebandSPIController::handleCancelledRxDMACommand (IODMACommand * command) inline private
Definition at line 1014 of file BasebandSPIController.cpp.
References DEBUG_INFO, fProtocol, BasebandSPIProtocol::handleCancelledRxCommand(), and SPI_TRACE.
Referenced by handleDMACompleteOnCancel().
 {
         SPI_TRACE( DEBUG_INFO );
         return fProtocol->handleCancelledRxCommand( command );
 }
IOReturn BasebandSPIController::handleCancelledTxDMACommand (IODMACommand * command) inline private
Definition at line 1007 of file BasebandSPIController.cpp.
References DEBUG_INFO, fProtocol, BasebandSPIProtocol::handleCancelledTxCommand(), and SPI_TRACE.
Referenced by handleDMACompleteOnCancel().
 {
         SPI_TRACE( DEBUG_INFO );
         return fProtocol->handleCancelledTxCommand( command );
 }
IOReturn BasebandSPIController::handleDMACompleteOnActive (IODMAEventSource * eventSource, IODMACommand * command, IOReturn status, IOByteCount byteCount) private
Definition at line 897 of file BasebandSPIController.cpp.
References cancelTransferCompleteTimer(), DEBUG_SPEW, fCurrentReceiveCommand, fCurrentSendCommand, fDiags, fPendingDMAs, fProtocol, fRxDMAES, BasebandSPIProtocol::handleTransferComplete(), kNone, BasebandSPIDiagnostics::markDMACompletion(), BasebandSPIDiagnostics::markRxHandlingComplete(), SPI_ASSERT, and SPI_TRACE.
Referenced by dmaCompleteAction().
 {
         SPI_TRACE( DEBUG_SPEW );
         if ( eventSource == fRxDMAES )
         {
                 fCurrentReceiveCommand = command;
         }
         else
         {
                 fCurrentSendCommand = command;
         }
         if ( fPendingDMAs == kNone )
         {
                 fDiags->markDMACompletion();
                 cancelTransferCompleteTimer();
 #if SPI_PEDANTIC_ASSERT
                 SPI_ASSERT( fProtocol, !=, NULL );
 #endif
                 fProtocol->handleTransferComplete( fCurrentReceiveCommand, fCurrentSendCommand );
                 fCurrentReceiveCommand = NULL;
                 fCurrentSendCommand = NULL;
                 fDiags->markRxHandlingComplete();
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIController::handleDMACompleteOnCancel (IODMAEventSource * eventSource, IODMACommand * command, IOReturn status, IOByteCount byteCount) private
Definition at line 821 of file BasebandSPIController.cpp.
References cancelTransferCompleteTimer(), DEBUG_INFO, fCommandGate, fCurrentReceiveCommand, fCurrentSendCommand, fPendingDMAs, fProtocol, fTxDMAES, handleCancelledRxDMACommand(), handleCancelledTxDMACommand(), BasebandSPIProtocol::handleTransferCancelled(), kNone, and SPI_TRACE.
Referenced by dmaCompleteAction(), and handleDMACompleteOnError().
 {
         SPI_TRACE( DEBUG_INFO );
         if ( eventSource == fTxDMAES )
         {
                 if ( command )
                 {
                         handleCancelledTxDMACommand( command );
                         fCurrentSendCommand = NULL; // We cancelled the Tx so we have to mark it as not available as well otherwise it could be reused in handleTransferComplete
                 }
                 if ( fCurrentReceiveCommand )
                 {
                         handleCancelledRxDMACommand( fCurrentReceiveCommand );
                         fCurrentReceiveCommand = NULL;
                 }
         }
         else
         {
                 if ( command )
                 {
                         handleCancelledRxDMACommand( command );
                         fCurrentReceiveCommand = NULL; // We cancelled the Rx so we have to mark it as not available as well otherwise it could be reused in handleTransferComplete
                 }
                 if ( fCurrentSendCommand )
                 {
                         handleCancelledTxDMACommand( fCurrentSendCommand );
                         fCurrentSendCommand = NULL;
                 }
         }
         if ( fPendingDMAs == kNone )
         {
                 cancelTransferCompleteTimer();
                 fCommandGate->commandWakeup( &fPendingDMAs );
                 fProtocol->handleTransferCancelled();
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIController::handleDMACompleteOnError (IODMAEventSource * eventSource, IODMACommand * command, IOReturn status, IOByteCount byteCount) private
Definition at line 864 of file BasebandSPIController.cpp.
References fPendingDMAs, fVolatileHardwareStateFlags, handleDMACompleteOnCancel(), kBasebandSPIReturnHWError, kFlagTransferActive, kNone, and reportError().
Referenced by dmaCompleteAction().
 {
         IOReturn ret = handleDMACompleteOnCancel( eventSource, command, status, byteCount );
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         // If we've gotten all the DMA callbacks we need, we can now throw up the error
         if ( fPendingDMAs == kNone )
         {
                 static const char * reason;
                 UInt32 flags = fVolatileHardwareStateFlags;
                 // TODO: this should go in the protocol
                 if ( flags & kFlagTransferActive )
                 {
                         reason = "DMA Timeout";
                 }
                 else
                 {
                         reason = "SRDY Timeout";
                 }
                 // all commands are returned, we can now report the error
                 reportError( kBasebandSPIReturnHWError, reason );
         }
         return kIOReturnSuccess;
 }
bool BasebandSPIController::init (OSDictionary * dict) virtual
Reimplemented in AppleS5LFamilyBasebandSPIController.
Definition at line 94 of file BasebandSPIController.cpp.
References DEBUG_INFO, fCommandGate, fCurrentReceiveCommand, fCurrentSendCommand, fDevice, fDiags, fEnteringLowPower, fHardwareStateFlags, fInLowPower, fInterruptGuard, fPendingDMAs, fPendingReceiveCommand, fPendingSendCommand, fProtocol, fProvider, fRxDMAES, fSavedSnapshot, fState, fTransferCompleteTimeout, fTxDMAES, fVolatileHardwareStateFlags, kNone, kOpen, kStateInactive, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         fState                                  = kStateInactive;
         fHardwareStateFlags                             = 0;
         fVolatileHardwareStateFlags             = 0;
         fProvider                               = NULL;
         fCommandGate                    = NULL;
         fPendingReceiveCommand  = NULL;
         fPendingSendCommand             = NULL;
         fCurrentReceiveCommand  = NULL;
         fCurrentSendCommand             = NULL;
         fTransferCompleteTimeout                = NULL;
         fTxDMAES                                                = NULL;
         fRxDMAES                                                = NULL;
         fPendingDMAs                    = kNone;
         fInLowPower                             = false;
         fEnteringLowPower                       = false;
         fDiags                                  = NULL;
         fSavedSnapshot                  = NULL;
         fInterruptGuard                 = kOpen;
         fDevice                                 = NULL;
         fProtocol                               = NULL;
         bool ret = super::init( dict );
         if ( !ret )
         {
                 return false;
         }
         return true;
 }
bool BasebandSPIController::intendToInterrupt (void) inline
Ask if we can interrupt, this is typically called from ISR context
Returns
True if we can interrupt
Definition at line 196 of file BasebandSPIController.h.
References fInterruptGuard, and kOpen.
         {
 #if SPI_USE_REAL_ISR
                 if ( fInterruptGuard == kOpen )
                 {
                         return true;
                 }
                 else
                 {
                         fInterruptGuard = kOpen;
                         return false;
                 }
 #else
                 return true;
 #endif
         }
bool BasebandSPIController::isEnteringLowPower (void) const inline
Definition at line 144 of file BasebandSPIController.h.
References fEnteringLowPower.
         {
                 return fEnteringLowPower;
         };
IOReturn BasebandSPIController::loadConfiguration (void) protected virtual
Parses through the configuration and extract necessary information.
Reimplemented in AppleS5L8920XBasebandSPIController, AppleS5L8900XBasebandSPIController, and AppleS5LFamilyBasebandSPIController.
Definition at line 280 of file BasebandSPIController.cpp.
References DEBUG_CRITICAL, fConfiguration, and SPI_LOG.
Referenced by canStartTransfer(), and start().
 {
         OSData * data = OSDynamicCast(OSData, getProvider()->getProperty("config"));
         if (!data)
         {
                 SPI_LOG( DEBUG_CRITICAL, "config property not found\n" );
                 return kIOReturnError;
         }
         if (data->getLength() != sizeof(BasebandSPIConfig))
         {
                 SPI_LOG( DEBUG_CRITICAL, "data size %d is less than config size %d\n",
                                         data->getLength(), sizeof(BasebandSPIConfig) );
                 return kIOReturnError;
         }
         {
                 BasebandSPIConfig * config = (BasebandSPIConfig *)data->getBytesNoCopy();
                 memcpy( &fConfiguration, config, sizeof( BasebandSPIConfig ) );
         }
         return kIOReturnSuccess;
 }
BasebandSPIController::OSDeclareAbstractStructors (BasebandSPIController) private
virtual IOReturn BasebandSPIController::preflightSetupHardware (void) protected pure virtual
Do a preflight setup of the hardware.
Implemented in AppleS5L8920XBasebandSPIController, and AppleS5L8900XBasebandSPIController.
Referenced by canStartTransfer().
IOService * BasebandSPIController::probe (IOService * provider, SInt32 * score) virtual
Definition at line 141 of file BasebandSPIController.cpp.
References DEBUG_INFO, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         const char * providerName = provider->getName();
         *score = 5000;
     SPI_LOG( DEBUG_INFO, "provider = 0x%08x, providerName = %s, score = %d, \n", provider, providerName , *score );
         return super::probe( provider, score );
 }
IOReturn BasebandSPIController::queueDMAWithCommand (IODMAEventSource * es, IODirection direction, IODMACommand * command, IOByteCount size) inline private
Definition at line 979 of file BasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_SPEW, eventSourceAsString(), SPI_LOG, and SPI_TRACE.
Referenced by configureDMA().
 {
         SPI_TRACE( DEBUG_SPEW );
         SPI_LOG( DEBUG_SPEW, "Start DMA on ES %s, MD %p, size %u\n",
                 eventSourceAsString( es ), command->getMemoryDescriptor(), size );
         IOReturn ret = es->startDMACommand( command, direction, size, 0 );
         if ( ret != kIOReturnSuccess )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Failed to start DMA with %s, ret = %p\n",
                         eventSourceAsString( es ), ret );
                 return ret;
         }
         return ret;
 }
IOReturn BasebandSPIController::releaseEventSources (void) inline private
Definition at line 782 of file BasebandSPIController.cpp.
References DEBUG_SPEW, fRxDMAES, fTransferCompleteTimeout, fTxDMAES, getWorkLoop(), and SPI_TRACE.
Referenced by stop().
 {
         SPI_TRACE( DEBUG_SPEW );
         if ( fTxDMAES )
         {
                 getWorkLoop()->removeEventSource( fTxDMAES );
                 fTxDMAES->release();
                 fTxDMAES = NULL;
         }
         if ( fRxDMAES )
         {
                 getWorkLoop()->removeEventSource( fRxDMAES );
                 fRxDMAES->release();
                 fRxDMAES = NULL;
         }
         if ( fTransferCompleteTimeout )
         {
                 getWorkLoop()->removeEventSource( fTransferCompleteTimeout );
                 fTransferCompleteTimeout->release();
                 fTransferCompleteTimeout = NULL;
         }
         return kIOReturnSuccess;
 }
bool BasebandSPIController::reportError (BasebandSPIReturn err, const char * details)
Definition at line 1053 of file BasebandSPIController.cpp.
References BasebandSPIControllerSnapshot::copyAsString(), DEBUG_CRITICAL, fDevice, fProvider, fSavedSnapshot, fState, getNewSnapshot(), kStateDeactivating, kStateInactive, BasebandSPIDevice::reportError(), SPI_ASSERT, SPI_LOG, and SPIsnprintf().
Referenced by dumpRegisters(), handleDMACompleteOnError(), and BasebandSPIIFXProtocol::handleSRDYTimeoutAction().
 {
         switch( fState )
         {
         case kStateInactive:
         case kStateDeactivating:
                 // if we're not enabled, then don't throw up an error.
                 return false;
         default:
                 break;
         }
         {
                 char buff[256];
                 SPIsnprintf( buff, sizeof( buff ), "%s/%p", details, err );
                 IOReturn ret = getNewSnapshot( buff );
                 if ( ret != kIOReturnSuccess )
                 {
                         SPI_LOG( DEBUG_CRITICAL, "Failed to create new snapshot, ret = %p\n", ret );
                 }
                 else
                 {
                         SPI_ASSERT( fSavedSnapshot, !=, NULL );
                         fSavedSnapshot->copyAsString( buff, sizeof( buff ) );
                         SPI_LOG( DEBUG_CRITICAL, "Error: %s\n", buff );
                 }
         }
         bool ret;
         if ( fSavedSnapshot )
         {
                 if ( fDevice )
                 {
                         fDevice->reportError( err );
                 }
                 ret = true;
         }
         else
         {
                 // Delete the snapshot if the error is not being reported to upper layers
                 if ( fSavedSnapshot )
                 {
                         delete fSavedSnapshot;
                         fSavedSnapshot = NULL;
                 }
                 ret = false;
         }
 #if SPI_ASSERT_GPIO_ON_ERROR
         AppleARMFunction * function = AppleARMFunction::withProvider(fProvider, "function-fail_gpio");
         if ( function )
         {
                 UInt32 value;
                 IOReturn ret;
                 SPI_LOG( DEBUG_CRITICAL, "Triggering GPIO\n" );
                 value = 1;
                 ret = function->callFunction( &value );
                 SPI_ASSERT( kIOReturnSuccess, ==, ret );
                 IOSleep( 20 );
                 value = 0;
                 ret = function->callFunction( &value );
                 SPI_ASSERT( kIOReturnSuccess, ==, ret );
                 IOSleep( 100 );
                 value = 1;
                 ret = function->callFunction( &value );
                 SPI_ASSERT( kIOReturnSuccess, ==, ret );
 bail:
                 function->release();
         }
 #endif
         return ret;
 }
bool BasebandSPIController::start (IOService * provider) virtual
Reimplemented in AppleS5L8920XBasebandSPIController, AppleS5L8900XBasebandSPIController, and AppleS5LFamilyBasebandSPIController.
Definition at line 155 of file BasebandSPIController.cpp.
References createEventSources(), DEBUG_CRITICAL, DEBUG_INFO, DEBUG_SPEW, fCommandGate, fDiags, fProvider, fWorkLoop, getWorkLoop(), loadConfiguration(), SPI_LOG, SPI_TRACE, validateHardware(), and BasebandSPIDiagnostics::withProvider().
 {
         SPI_TRACE( DEBUG_INFO );
         fProvider = OSDynamicCast( AppleARMIODevice, provider );
         if (!fProvider) return false;
         /*
         {
                 mach_timespec_t ts = {0, 20*1000*1000};
                 IOService * baseband = IOService::waitForService( serviceMatching( "baseband" ), &ts );
                 if ( baseband == NULL )
                 {
                         SPI_LOG( DEBUG_CRITICAL, "baseband doesn't exist\n" );
                         return false;
                 }
         }
         */
         fProvider->retain();
         fWorkLoop = IOWorkLoop::workLoop();
         if ( !fWorkLoop )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Failed to create work loop\n" );
                 return false;
         }
         fCommandGate = IOCommandGate::commandGate( this );
         if ( fCommandGate == NULL )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Failed to create command gate\n" );
                 return false;
         }
         IOReturn ret = getWorkLoop()->addEventSource( fCommandGate );
         if ( ret != kIOReturnSuccess )
         {
                 fCommandGate->release();
                 fCommandGate = NULL;
                 SPI_LOG( DEBUG_CRITICAL, "Failed to add command gate to workloop, ret = %p\n", ret );
                 return false;
         }
         ret = createEventSources();
         if ( ret != kIOReturnSuccess )
         {
                 return false;
         }
         ret = validateHardware();
         if ( ret != kIOReturnSuccess )
         {
                 return false;
         }
         ret = loadConfiguration();
         if ( ret != kIOReturnSuccess )
         {
                 return false;
         }
         fDiags = BasebandSPIDiagnostics::withProvider( fProvider );
         if ( !fDiags )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Failed to set up diags\n" );
                 return false;
         }
         SPI_LOG( DEBUG_SPEW, "All OK, registering service\n" );
         return true;
 }
virtual IOReturn BasebandSPIController::startHardware (void) protected pure virtual
Start the hardware for the transfer.
Implemented in AppleS5L8920XBasebandSPIController, and AppleS5L8900XBasebandSPIController.
Referenced by canStartTransfer(), and startTransfer().
IOReturn BasebandSPIController::startTransfer (void)
Definition at line 669 of file BasebandSPIController.cpp.
References DEBUG_SPEW, dumpRegisters(), fVolatileHardwareStateFlags, kFlagTransferActive, SPI_TRACE, and startHardware().
Referenced by dumpRegisters().
 {
         SPI_TRACE( DEBUG_SPEW );
         fVolatileHardwareStateFlags |= kFlagTransferActive;
         IOReturn ret = startHardware();
         dumpRegisters( DEBUG_SPEW );
         return ret;
 }
void BasebandSPIController::startTransferCompleteTimer (void) inline private
Definition at line 1021 of file BasebandSPIController.cpp.
References fTransferCompleteTimeout, and kTransferCompleteTimeoutInterval.
 {
         fTransferCompleteTimeout->cancelTimeout();
         fTransferCompleteTimeout->setTimeoutMS( kTransferCompleteTimeoutInterval );
         fTransferCompleteTimeout->enable();
 }
const char * BasebandSPIController::stateAsString (State state) static protected
Definition at line 23 of file BasebandSPIController.cpp.
References kStateActive, kStateDeactivating, and kStateInactive.
Referenced by activate(), changeState(), deactivate(), and waitForStateChange().
 {
         switch ( state )
         {
         case kStateInactive:            return "Inactive";
         case kStateActive:                      return "Active";
         case kStateDeactivating:        return "Deactivating";
         default:                                        return "???";
         }
 }
void BasebandSPIController::stop (IOService * provider) virtual
Reimplemented in AppleS5LFamilyBasebandSPIController.
Definition at line 304 of file BasebandSPIController.cpp.
References DEBUG_INFO, fCommandGate, fDiags, fProvider, fSavedSnapshot, fWorkLoop, getWorkLoop(), releaseEventSources(), and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         if ( fSavedSnapshot )
         {
                 delete fSavedSnapshot;
                 fSavedSnapshot = NULL;
         }
         if ( fDiags )
         {
                 fDiags->release();
                 fDiags = NULL;
         }
         releaseEventSources();
         if ( fCommandGate  )
         {
                 getWorkLoop()->removeEventSource( fCommandGate );
                 fCommandGate->release();
                 fCommandGate = NULL;
         }
         if ( fWorkLoop )
         {
                 fWorkLoop->release();
                 fWorkLoop = NULL;
         }
         if ( fProvider )
         {
                 fProvider->release();
                 fProvider = NULL;
         }
 }
virtual IOReturn BasebandSPIController::takeSnapshot (const char * comment, BasebandSPIControllerSnapshot::PinState resetDetectState, BasebandSPIControllerSnapshot ** snapshot) protected pure virtual
Implemented in AppleS5L8920XBasebandSPIController, AppleS5L8900XBasebandSPIController, and AppleS5LFamilyBasebandSPIController.
Referenced by dumpRegisters(), and getNewSnapshot().
void BasebandSPIController::transferCompleteTimeoutAction (IOTimerEventSource * es) private
Definition at line 1035 of file BasebandSPIController.cpp.
References beginBlockInterrupt(), cancelAll(), DEBUG_CRITICAL, endBlockInterrupt(), fHardwareStateFlags, fPendingDMAs, fVolatileHardwareStateFlags, kFlagError, kFlagTransferActive, SPI_LOG, SPI_TRACE, and unconfigure().
Referenced by createEventSources().
 {
         SPI_TRACE( DEBUG_CRITICAL );
         SPI_LOG( DEBUG_CRITICAL, "Pending DMA's %d, HW status %p, volatile HW status %p\n",
                 fPendingDMAs, fHardwareStateFlags, fVolatileHardwareStateFlags );
         beginBlockInterrupt();
         unconfigure();
         fVolatileHardwareStateFlags = ( fVolatileHardwareStateFlags & ~ kFlagTransferActive ) | kFlagError;
         endBlockInterrupt();
         cancelAll();
 }
IOReturn BasebandSPIController::unconfigure (void)
Definition at line 641 of file BasebandSPIController.cpp.
References DEBUG_SPEW, dumpRegisters(), fHardwareStateFlags, fProtocol, fVolatileHardwareStateFlags, BasebandSPIProtocol::isSRDYStateHigh(), kFlagHardwareActive, kFlagTransferActive, BasebandSPILogger::logGeneral(), SPI_TRACE, and unconfigureHardware().
Referenced by deactivate(), dumpRegisters(), and transferCompleteTimeoutAction().
 {
         SPI_TRACE( DEBUG_SPEW );
 #if SPI_SRDY_DEBUG
         BasebandSPILogger::logGeneral( "DPREP", ( fVolatileHardwareStateFlags <<  16 )  | fHardwareStateFlags, ((fProtocol) ? fProtocol->isSRDYStateHigh() : false) );
 #else
         BasebandSPILogger::logGeneral( "DPREP", ( fVolatileHardwareStateFlags <<  16 )  | fHardwareStateFlags );
 #endif
         dumpRegisters( DEBUG_SPEW );
         IOReturn ret;
         ret = unconfigureHardware();
         if ( ret != kIOReturnSuccess )
         {
                 goto bail;
         }
         fVolatileHardwareStateFlags &= ~ ( kFlagHardwareActive | kFlagTransferActive );
 bail:
         return ret;
 }
virtual IOReturn BasebandSPIController::unconfigureHardware (void) protected pure virtual
Power down the hardware.
Implemented in AppleS5L8920XBasebandSPIController, and AppleS5L8900XBasebandSPIController.
Referenced by canStartTransfer(), and unconfigure().
virtual bool BasebandSPIController::validateDeviceTypeAndChip (const char * deviceType, UInt32 chipRevision) const protected pure virtual
Validates the device type and chip revision
Parameters
deviceTyp the Device type
chipRevision the chip revision
Returns
True if OK, false if not compatible
Implemented in AppleS5L8920XBasebandSPIController, and AppleS5L8900XBasebandSPIController.
Referenced by canStartTransfer(), and validateHardware().
IOReturn BasebandSPIController::validateHardware (void) private
Definition at line 238 of file BasebandSPIController.cpp.
References DEBUG_SPEW, kBasebandSPIReturnHardwareIncompatible, SPI_ASSERT, SPI_LOG, and validateDeviceTypeAndChip().
Referenced by start().
 {
         static const char * kPlatformDeviceName = "arm-io";
         IOService * service = IOService::waitForService( nameMatching( kPlatformDeviceName ) );
         OSObject * object;
         object = service->getProperty( "chip-revision" );
         SPI_ASSERT( object, !=, NULL );
         OSData * data = OSDynamicCast( OSData, object );
         SPI_ASSERT( data, !=, NULL );
         UInt32 chipRevision = *( (UInt32 *)data->getBytesNoCopy() );
         object = service->getProperty( "device_type" );
         SPI_ASSERT( object, !=, NULL );
         OSData * str = OSDynamicCast( OSData, object );
         SPI_ASSERT( str, !=, NULL );
         char deviceType[32];
         strncpy( deviceType, (const char *)str->getBytesNoCopy(), MIN( str->getLength(), sizeof( deviceType ) ) );
         bool ret = validateDeviceTypeAndChip( deviceType, chipRevision );
         if ( ret )
         {
                 SPI_LOG( DEBUG_SPEW, "Hardware is OK\n" );
                 return kIOReturnSuccess;
         }
         else
         {
                 SPI_LOG( DEBUG_SPEW, "Hardware is not compatible\n" );
                 return kBasebandSPIReturnHardwareIncompatible;
         }
 }
IOReturn BasebandSPIController::waitForDMACompletion (void) private
Definition at line 429 of file BasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, fCommandGate, fPendingDMAs, and SPI_LOG.
Referenced by deactivate(), and enterLowPower().
 {
         SPI_LOG( DEBUG_INFO, "Pending DMAs = %p\n", fPendingDMAs );
         while ( fPendingDMAs )
         {
                 IOReturn ret;
                 ret = fCommandGate->commandSleep( &fPendingDMAs, THREAD_UNINT );
                 if ( ret != kIOReturnSuccess )
                 {
                         SPI_LOG( DEBUG_CRITICAL, "Sleeping failed, ret = %p\n", ret );
                         return ret;
                 }
                 //BasebandSPILogger::report();
                 //BasebandSPILogger::clear();
                 SPI_LOG( DEBUG_INFO, "Updated Pending DMAs = %p\n", fPendingDMAs );
         }
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIController::waitForStateChange (State expectedState) private
Definition at line 74 of file BasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, fCommandGate, fState, SPI_LOG, and stateAsString().
Referenced by enterLowPower().
 {
         while ( fState == fromState )
         {
                 IOReturn ret;
                 SPI_LOG( DEBUG_INFO, "Current state %s, from %s",
                         stateAsString( fState ), stateAsString( fromState ) );
                 ret = fCommandGate->commandSleep( &fState, THREAD_UNINT );
                 if ( ret != kIOReturnSuccess )
                 {
                         SPI_LOG( DEBUG_CRITICAL, "Sleeping failed, ret = %p\n", ret );
                         return ret;
                 }
         }
         return kIOReturnSuccess;
 }
Member Data Documentation
IOCommandGate* BasebandSPIController::fCommandGate protected
Definition at line 223 of file BasebandSPIController.h.
Referenced by changeState(), handleDMACompleteOnCancel(), init(), start(), stop(), waitForDMACompletion(), and waitForStateChange().
BasebandSPIConfig BasebandSPIController::fConfiguration protected
Definition at line 242 of file BasebandSPIController.h.
Referenced by AppleS5LFamilyBasebandSPIController::loadConfiguration(), and loadConfiguration().
IODMACommand* BasebandSPIController::fCurrentReceiveCommand protected
Definition at line 218 of file BasebandSPIController.h.
Referenced by handleDMACompleteOnActive(), handleDMACompleteOnCancel(), and init().
IODMACommand* BasebandSPIController::fCurrentSendCommand protected
Definition at line 219 of file BasebandSPIController.h.
Referenced by handleDMACompleteOnActive(), handleDMACompleteOnCancel(), and init().
BasebandSPIDevice* BasebandSPIController::fDevice protected
Definition at line 240 of file BasebandSPIController.h.
Referenced by activate(), deactivate(), init(), and reportError().
BasebandSPIDiagnostics* BasebandSPIController::fDiags protected
Definition at line 244 of file BasebandSPIController.h.
Referenced by handleDMACompleteOnActive(), init(), start(), and stop().
bool BasebandSPIController::fEnteringLowPower protected
Definition at line 233 of file BasebandSPIController.h.
Referenced by canStartTransfer(), enterLowPower(), init(), and isEnteringLowPower().
UInt32 BasebandSPIController::fHardwareStateFlags protected
Definition at line 228 of file BasebandSPIController.h.
Referenced by configure(), init(), transferCompleteTimeoutAction(), and unconfigure().
bool BasebandSPIController::fInLowPower protected
Definition at line 232 of file BasebandSPIController.h.
Referenced by deactivate(), enterLowPower(), exitLowPower(), and init().
volatile InterruptGuardState BasebandSPIController::fInterruptGuard protected
Definition at line 248 of file BasebandSPIController.h.
Referenced by beginBlockInterrupt(), endBlockInterrupt(), init(), and intendToInterrupt().
UInt32 BasebandSPIController::fPendingDMAs protected
Definition at line 231 of file BasebandSPIController.h.
Referenced by cancelAll(), configure(), configureDMA(), dmaCompleteAction(), dmaNotifyAction(), handleDMACompleteOnActive(), handleDMACompleteOnCancel(), handleDMACompleteOnError(), init(), transferCompleteTimeoutAction(), and waitForDMACompletion().
IODMACommand* BasebandSPIController::fPendingReceiveCommand protected
Definition at line 215 of file BasebandSPIController.h.
Referenced by configureDMA(), and init().
IODMACommand* BasebandSPIController::fPendingSendCommand protected
Definition at line 216 of file BasebandSPIController.h.
Referenced by configureDMA(), and init().
BasebandSPIProtocol* BasebandSPIController::fProtocol protected
Definition at line 241 of file BasebandSPIController.h.
Referenced by activate(), configure(), configureDMA(), deactivate(), eventSourceAsString(), getNewSnapshot(), handleCancelledRxDMACommand(), handleCancelledTxDMACommand(), handleDMACompleteOnActive(), handleDMACompleteOnCancel(), init(), and unconfigure().
AppleARMIODevice* BasebandSPIController::fProvider protected
Definition at line 221 of file BasebandSPIController.h.
Referenced by AppleS5LFamilyBasebandSPIController::configurePins(), createEventSources(), AppleS5LFamilyBasebandSPIController::enableClock(), init(), AppleS5LFamilyBasebandSPIController::loadConfiguration(), reportError(), start(), and stop().
IODMAEventSource* BasebandSPIController::fRxDMAES protected
Definition at line 236 of file BasebandSPIController.h.
Referenced by cancelAll(), configureDMA(), createEventSources(), dmaCompleteAction(), eventSourceAsString(), handleDMACompleteOnActive(), init(), and releaseEventSources().
BasebandSPIControllerSnapshot* BasebandSPIController::fSavedSnapshot protected
Definition at line 246 of file BasebandSPIController.h.
Referenced by getNewSnapshot(), getSnapshot(), init(), reportError(), and stop().
State BasebandSPIController::fState protected
Definition at line 226 of file BasebandSPIController.h.
Referenced by activate(), changeState(), configure(), deactivate(), enterLowPower(), exitLowPower(), init(), reportError(), and waitForStateChange().
State BasebandSPIController::fStateBeforeLowPower protected
Definition at line 227 of file BasebandSPIController.h.
Referenced by enterLowPower(), and exitLowPower().
IOTimerEventSource* BasebandSPIController::fTransferCompleteTimeout protected
Definition at line 238 of file BasebandSPIController.h.
Referenced by cancelTransferCompleteTimer(), createEventSources(), init(), releaseEventSources(), and startTransferCompleteTimer().
IODMAEventSource* BasebandSPIController::fTxDMAES protected
Definition at line 235 of file BasebandSPIController.h.
Referenced by cancelAll(), configureDMA(), createEventSources(), eventSourceAsString(), handleDMACompleteOnCancel(), init(), and releaseEventSources().
volatile UInt32 BasebandSPIController::fVolatileHardwareStateFlags protected
Definition at line 229 of file BasebandSPIController.h.
Referenced by canStartTransfer(), configure(), dmaCompleteAction(), handleDMACompleteOnError(), init(), startTransfer(), transferCompleteTimeoutAction(), and unconfigure().
IOWorkLoop* BasebandSPIController::fWorkLoop protected
Definition at line 224 of file BasebandSPIController.h.
Referenced by getWorkLoop(), start(), and stop().
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPIController.h
/BasebandSPI/BasebandSPIController.cpp