BasebandSPIDiagnostics Class Reference
BasebandSPIDiagnostics Class Reference
#include <BasebandSPIDiagnostics.h>
Inherits OSObject.
Public Member Functions
void markDMACompletion (void)
void markRaiseMRDYMasterInitiated (void)
void markRaiseMRDYSlaveInitiated (void)
void markRxHandlingComplete (void)
void markSRDYInterrupt (void)
Static Public Member Functions
static BasebandSPIDiagnostics * withProvider (IOService *provider)
Private Member Functions
bool enabled (void) const
virtual void free (void)
virtual bool init (IOService *provider)
void markDMACompletionInternal (void)
void markRaiseMRDYMasterInitiatedInternal (void)
void markRaiseMRDYSlaveInitiatedInternal (void)
void markRxHandlingCompleteInternal (void)
void markSRDYInterruptInternal (void)
OSDeclareAbstractStructors (BasebandSPIDiagnostics)
void setGPIO (UInt32 high)
void toggleGPIO (void)
Static Private Member Functions
static const char * getDebugName (void)
Private Attributes
AppleARMFunction * fGPIOFunction
UInt32 fGPIOLevel
Static Private Attributes
static const bool kEnabled = false
Detailed Description
Definition at line 18 of file BasebandSPIDiagnostics.h.
Member Function Documentation
bool BasebandSPIDiagnostics::enabled (void) const inline private
Definition at line 38 of file BasebandSPIDiagnostics.h.
References fGPIOFunction.
Referenced by markDMACompletion(), markRaiseMRDYMasterInitiated(), markRaiseMRDYSlaveInitiated(), markRxHandlingComplete(), and markSRDYInterrupt().
         {
                 return kEnabled && fGPIOFunction;
         }
void BasebandSPIDiagnostics::free (void) private virtual
Definition at line 88 of file BasebandSPIDiagnostics.cpp.
References fGPIOFunction.
Referenced by getDebugName().
 {
         fGPIOFunction->release();
         fGPIOFunction = NULL;
 }
static const char* BasebandSPIDiagnostics::getDebugName (void) inline static private
Definition at line 25 of file BasebandSPIDiagnostics.h.
References free(), init(), and withProvider().
         {
                 return "BasebandSPIDiagnostics";
         }
bool BasebandSPIDiagnostics::init (IOService * provider) private virtual
Definition at line 31 of file BasebandSPIDiagnostics.cpp.
References DEBUG_CRITICAL, fGPIOFunction, fGPIOLevel, kEnabled, and SPI_LOG.
Referenced by getDebugName(), and withProvider().
 {
         static const char * kGPIOKey = "function-diag_gpio1";
         if ( !kEnabled )
         {
                 fGPIOFunction = NULL;
                 return true;
         }
         fGPIOFunction = AppleARMFunction::withProvider(provider, kGPIOKey );
         if ( !fGPIOFunction )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Warning: Couldn't find function for '%s'\n", kGPIOKey );
         }
         fGPIOLevel = 0;
         return true;
 }
void BasebandSPIDiagnostics::markDMACompletion (void) inline
Definition at line 72 of file BasebandSPIDiagnostics.h.
References enabled(), and markDMACompletionInternal().
Referenced by BasebandSPIController::handleDMACompleteOnActive().
         {
                 if ( enabled() )
                 {
                         markDMACompletionInternal();
                 }
         }
void BasebandSPIDiagnostics::markDMACompletionInternal (void) private
Definition at line 77 of file BasebandSPIDiagnostics.cpp.
References toggleGPIO().
Referenced by markDMACompletion(), and markRxHandlingComplete().
 {
         toggleGPIO();
 }
void BasebandSPIDiagnostics::markRaiseMRDYMasterInitiated (void) inline
Definition at line 48 of file BasebandSPIDiagnostics.h.
References enabled(), and markRaiseMRDYMasterInitiatedInternal().
         {
                 if ( enabled() )
                 {
                         markRaiseMRDYMasterInitiatedInternal();
                 }
         }
void BasebandSPIDiagnostics::markRaiseMRDYMasterInitiatedInternal (void) private
Definition at line 62 of file BasebandSPIDiagnostics.cpp.
References toggleGPIO().
Referenced by markRaiseMRDYMasterInitiated(), and markRxHandlingComplete().
 {
         toggleGPIO();
 }
void BasebandSPIDiagnostics::markRaiseMRDYSlaveInitiated (void) inline
Definition at line 56 of file BasebandSPIDiagnostics.h.
References enabled(), and markRaiseMRDYSlaveInitiatedInternal().
         {
                 if ( enabled() )
                 {
                         markRaiseMRDYSlaveInitiatedInternal();
                 }
         }
void BasebandSPIDiagnostics::markRaiseMRDYSlaveInitiatedInternal (void) private
Definition at line 67 of file BasebandSPIDiagnostics.cpp.
References toggleGPIO().
Referenced by markRaiseMRDYSlaveInitiated(), and markRxHandlingComplete().
 {
         toggleGPIO();
 }
void BasebandSPIDiagnostics::markRxHandlingComplete (void) inline
Definition at line 80 of file BasebandSPIDiagnostics.h.
References enabled(), markDMACompletionInternal(), markRaiseMRDYMasterInitiatedInternal(), markRaiseMRDYSlaveInitiatedInternal(), markRxHandlingCompleteInternal(), markSRDYInterruptInternal(), and setGPIO().
Referenced by BasebandSPIController::handleDMACompleteOnActive().
         {
                 if ( enabled() )
                 {
                         markRxHandlingCompleteInternal();
                 }
         }
void BasebandSPIDiagnostics::markRxHandlingCompleteInternal (void) private
Definition at line 82 of file BasebandSPIDiagnostics.cpp.
References toggleGPIO().
Referenced by markRxHandlingComplete().
 {
         toggleGPIO();
 }
void BasebandSPIDiagnostics::markSRDYInterrupt (void) inline
Definition at line 64 of file BasebandSPIDiagnostics.h.
References enabled(), and markSRDYInterruptInternal().
         {
                 if ( enabled() )
                 {
                         markSRDYInterruptInternal();
                 }
         }
void BasebandSPIDiagnostics::markSRDYInterruptInternal (void) private
Definition at line 72 of file BasebandSPIDiagnostics.cpp.
References toggleGPIO().
Referenced by markRxHandlingComplete(), and markSRDYInterrupt().
 {
         toggleGPIO();
 }
BasebandSPIDiagnostics::OSDeclareAbstractStructors (BasebandSPIDiagnostics) private
void BasebandSPIDiagnostics::setGPIO (UInt32 high) private
Definition at line 53 of file BasebandSPIDiagnostics.cpp.
References DEBUG_CRITICAL, fGPIOFunction, and SPI_LOG.
Referenced by markRxHandlingComplete(), and toggleGPIO().
 {
         IOReturn ret = fGPIOFunction->callFunction( &high );
         if ( ret != kIOReturnSuccess )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Failed to toggle gpio\n" );
         }
 }
void BasebandSPIDiagnostics::toggleGPIO (void) inline private
Definition at line 97 of file BasebandSPIDiagnostics.h.
References setGPIO().
Referenced by markDMACompletionInternal(), markRaiseMRDYMasterInitiatedInternal(), markRaiseMRDYSlaveInitiatedInternal(), markRxHandlingCompleteInternal(), and markSRDYInterruptInternal().
         {
                 fGPIOLevel = fGPIOLevel ? 0 : 1;
                 setGPIO( fGPIOLevel );
         };
BasebandSPIDiagnostics * BasebandSPIDiagnostics::withProvider (IOService * provider) static
Definition at line 16 of file BasebandSPIDiagnostics.cpp.
References init().
Referenced by getDebugName(), and BasebandSPIController::start().
 {
         BasebandSPIDiagnostics * me = new BasebandSPIDiagnostics();
         bool ret = me->init( provider );
         if ( !ret )
         {
                 delete me;
                 me = NULL;
         }
         return me;
 }
Member Data Documentation
AppleARMFunction* BasebandSPIDiagnostics::fGPIOFunction private
Definition at line 44 of file BasebandSPIDiagnostics.h.
Referenced by enabled(), free(), init(), and setGPIO().
UInt32 BasebandSPIDiagnostics::fGPIOLevel private
Definition at line 45 of file BasebandSPIDiagnostics.h.
Referenced by init().
const bool BasebandSPIDiagnostics::kEnabled = false static private
Definition at line 23 of file BasebandSPIDiagnostics.h.
Referenced by init().
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPIDiagnostics.h
/BasebandSPI/BasebandSPIDiagnostics.cpp