BasebandSPICommandVersion1 Class Reference
BasebandSPICommandVersion1 Class Reference
Inherits BasebandSPICommand.
Classes
struct SPIHeader
Public Member Functions
void assertFlowControl (void)
void assertMoreToTransfer (void)
void clearHeader (void)
void dumpFrameInternal (int logLevel) const
void finalize (IOByteCount framePayloadSize, IOByteCount frameSize)
virtual const char * getDebugName (void) const
IOByteCount getPayloadLength (void) const
bool indicatesFlowControl (void) const
bool indicatesMoreToTransfer (void) const
virtual void reset (void)
virtual IOByteCount writeData (UInt8 *source, IOByteCount amount, IOByteCount dataSize)
Public Member Functions inherited from BasebandSPICommand
virtual IOReturn clearMemoryDescriptor (void)
void dumpFrame (int level) const
void * getCookie (void) const
BasebandSPICommand * getNext (void) const
bool isFinalized (void) const
IOReturn setMemoryDescriptor (IOMemoryDescriptor *md, UInt8 *buffer, void *cookie)
void setNext (BasebandSPICommand *command)
Static Public Member Functions
static BasebandSPICommandVersion1 * create (IODirection direction)
static const char * getDebugNameStatic (void)
Static Public Attributes
static const unsigned kSPIHeaderDataSizeBits = 12
static const unsigned kSPIHeaderMaxDataSize = ((1UL << kSPIHeaderDataSizeBits) - 1)
Protected Member Functions
virtual IOReturn init (IODirection direction)
Protected Member Functions inherited from BasebandSPICommand
void clearFinalized (void)
virtual void free (void)
void setFinalized (void)
Private Member Functions
void dumpHeader (int logLevel) const
SPIHeader * getHeader (void) const
UInt8 * getPayload (void) const
OSDeclareDefaultStructors (BasebandSPICommandVersion1)
Private Attributes
IOByteCount fWriteOffset
Friends
class BasebandSPICommand
class BasebandSPILogger
Additional Inherited Members
Protected Attributes inherited from BasebandSPICommand
UInt8 * fBuffer
void * fCookie
IODirection fDirection
bool fIsFinalized
IOMemoryDescriptor * fMemoryDescriptor
BasebandSPICommand * fNext
Detailed Description
Definition at line 12 of file BasebandSPIIFXProtocolVersion1.cpp.
Member Function Documentation
void BasebandSPICommandVersion1::assertFlowControl (void) inline
Definition at line 56 of file BasebandSPIIFXProtocolVersion1.cpp.
References BasebandSPICommandVersion1::SPIHeader::cts_rts, and getHeader().
Referenced by BasebandSPIIFXProtocolVersion1::prepareTransferIfNeeded().
         {
                 getHeader()->cts_rts = 1;
         }
void BasebandSPICommandVersion1::assertMoreToTransfer (void) inline
Definition at line 61 of file BasebandSPIIFXProtocolVersion1.cpp.
References getHeader(), and BasebandSPICommandVersion1::SPIHeader::more.
Referenced by BasebandSPIIFXProtocolVersion1::prepareTransferIfNeeded().
         {
                 getHeader()->more = 1;
         }
void BasebandSPICommandVersion1::clearHeader (void) inline
Definition at line 47 of file BasebandSPIIFXProtocolVersion1.cpp.
References getHeader(), and SPI_ASSERT.
Referenced by BasebandSPIIFXProtocolVersion1::prepareTransferIfNeeded().
         {
                 SPI_ASSERT( sizeof( SPIHeader ), ==, sizeof( UInt32 ) );
                 UInt32 * p = (UInt32 *)getHeader();
                 *p = 0;
         };
BasebandSPICommandVersion1 * BasebandSPICommandVersion1::create (IODirection direction) static
Definition at line 115 of file BasebandSPIIFXProtocolVersion1.cpp.
References DEBUG_CRITICAL, init(), and SPI_LOG_STATIC.
Referenced by BasebandSPIIFXProtocolVersion1::allocateCommand().
 {
         BasebandSPICommandVersion1 * command = new BasebandSPICommandVersion1();
         IOReturn ret = command->init( direction );
         if ( ret != kIOReturnSuccess )
         {
                 SPI_LOG_STATIC( DEBUG_CRITICAL, "Command initialization failed with error %p\n", ret );
                 command->release();
                 command = NULL;
         }
         return command;
 }
void BasebandSPICommandVersion1::dumpFrameInternal (int logLevel) const virtual
Implements BasebandSPICommand.
Definition at line 187 of file BasebandSPIIFXProtocolVersion1.cpp.
References BasebandSPICommandVersion1::SPIHeader::curr_data_size, Dbg_hexdump, dumpHeader(), BasebandSPICommand::fBuffer, BasebandSPICommand::fDirection, getHeader(), getPayload(), kSPIHeaderMaxDataSize, and SPI_LOG_PLAIN.
Referenced by getDebugName().
 {
         IOMemoryDescriptor * md = (IOMemoryDescriptor *)getMemoryDescriptor();
         IOMemoryMap * map = md->map();
         SPI_LOG_PLAIN( logLevel, "--------------------------------------------------\n" );
         SPI_LOG_PLAIN( logLevel, "Direction: %s\tHeader: %p(%p), %d\tMD: %p\n", fDirection == kIODirectionOut ? "Tx" : "Rx",
                 fBuffer, map->getPhysicalAddress(), sizeof( struct BasebandSPICommandVersion1::SPIHeader ), md );
         SPI_LOG_PLAIN( logLevel, "..................................................\n" );
         map->release();
         bool valid = fBuffer != NULL;
         if ( valid )
         {
                 dumpHeader( logLevel );
         }
         else
         {
                 SPI_LOG_PLAIN( logLevel, "INVALID FRAME\n" );
         }
         SPI_LOG_PLAIN( logLevel, "..................................................\n" );
         if (valid && ( getHeader()->curr_data_size != kSPIHeaderMaxDataSize ) ) {
                 IOByteCount size = MIN( md->getLength(), getHeader()->curr_data_size );
                 Dbg_hexdump( logLevel, getPayload(), size );
         }
         SPI_LOG_PLAIN( logLevel, "--------------------------------------------------\n" );
 }
void BasebandSPICommandVersion1::dumpHeader (int logLevel) const inline private
Definition at line 224 of file BasebandSPIIFXProtocolVersion1.cpp.
References BasebandSPICommandVersion1::SPIHeader::crc_err, BasebandSPICommandVersion1::SPIHeader::cts_rts, BasebandSPICommandVersion1::SPIHeader::curr_data_size, Dbg_hexdump, BasebandSPICommandVersion1::SPIHeader::dcd, BasebandSPICommandVersion1::SPIHeader::dsr_dtr, getHeader(), BasebandSPICommandVersion1::SPIHeader::more, BasebandSPICommandVersion1::SPIHeader::next_data_size, BasebandSPICommandVersion1::SPIHeader::pkt_id, BasebandSPICommandVersion1::SPIHeader::ri, and SPI_LOG_PLAIN.
Referenced by dumpFrameInternal(), and getDebugName().
 {
         Dbg_hexdump(logLevel, getHeader(), sizeof(struct SPIHeader));
         SPIHeader * header = getHeader();
         SPI_LOG_PLAIN( logLevel, "\tcurr_data_size: %#3lx\tnext_data_size: %#3lx\n", header->curr_data_size, header->next_data_size );
         SPI_LOG_PLAIN( logLevel, "\tri: %d\tcts: %d\tdcd: %d\tdsr: %d\tmore: %d\n", header->ri, header->cts_rts, header->dcd, header->dsr_dtr, header->more );
         SPI_LOG_PLAIN( logLevel, "\trx_err: %d\tpkt_id: %#x\n", header->crc_err, header->pkt_id );
 }
void BasebandSPICommandVersion1::finalize (IOByteCount framePayloadSize, IOByteCount frameSize) inline
Definition at line 152 of file BasebandSPIIFXProtocolVersion1.cpp.
References BasebandSPICommandVersion1::SPIHeader::curr_data_size, BasebandSPICommand::fMemoryDescriptor, fWriteOffset, getHeader(), BasebandSPICommandVersion1::SPIHeader::next_data_size, and BasebandSPICommand::setFinalized().
Referenced by BasebandSPIIFXProtocolVersion1::prepareTransferIfNeeded().
 {
         SPIHeader * header = getHeader();
         // set our size fields
         header->curr_data_size = fWriteOffset;
         header->next_data_size = framePayloadSize;
         // store the data from cache to memory
         fMemoryDescriptor->performOperation( kIOMemoryIncoherentIOStore, 0, frameSize );
         // mark this as finalized
         setFinalized();
 }
virtual const char* BasebandSPICommandVersion1::getDebugName (void) const inline virtual
Implements BasebandSPICommand.
Definition at line 87 of file BasebandSPIIFXProtocolVersion1.cpp.
References dumpFrameInternal(), dumpHeader(), and getDebugNameStatic().
         {
                 return getDebugNameStatic();
         };
static const char* BasebandSPICommandVersion1::getDebugNameStatic (void) inline static
Definition at line 82 of file BasebandSPIIFXProtocolVersion1.cpp.
Referenced by getDebugName().
         {
                 return "BasebandSPICommandVersion1";
         };
SPIHeader* BasebandSPICommandVersion1::getHeader (void) const inline private
Definition at line 98 of file BasebandSPIIFXProtocolVersion1.cpp.
References BasebandSPICommand::fBuffer.
Referenced by assertFlowControl(), assertMoreToTransfer(), clearHeader(), dumpFrameInternal(), dumpHeader(), finalize(), getPayloadLength(), indicatesFlowControl(), and indicatesMoreToTransfer().
         {
                 return (SPIHeader *)fBuffer;
         }
UInt8* BasebandSPICommandVersion1::getPayload (void) const inline private
Definition at line 103 of file BasebandSPIIFXProtocolVersion1.cpp.
References BasebandSPICommand::fBuffer.
Referenced by dumpFrameInternal(), and writeData().
         {
                 return fBuffer + sizeof( SPIHeader );
         };
IOByteCount BasebandSPICommandVersion1::getPayloadLength (void) const inline
Definition at line 76 of file BasebandSPIIFXProtocolVersion1.cpp.
References BasebandSPICommandVersion1::SPIHeader::curr_data_size, and getHeader().
Referenced by BasebandSPIIFXProtocolVersion1::handleTransferComplete().
         {
                 return getHeader()->curr_data_size;
         }
bool BasebandSPICommandVersion1::indicatesFlowControl (void) const inline
Definition at line 66 of file BasebandSPIIFXProtocolVersion1.cpp.
References BasebandSPICommandVersion1::SPIHeader::cts_rts, and getHeader().
Referenced by BasebandSPIIFXProtocolVersion1::handleTransferComplete().
         {
                 return getHeader()->cts_rts;
         };
bool BasebandSPICommandVersion1::indicatesMoreToTransfer (void) const inline
Definition at line 71 of file BasebandSPIIFXProtocolVersion1.cpp.
References getHeader(), and BasebandSPICommandVersion1::SPIHeader::more.
Referenced by BasebandSPIIFXProtocolVersion1::handleTransferComplete().
         {
                 return getHeader()->more;
         }
IOReturn BasebandSPICommandVersion1::init (IODirection direction) protected virtual
Reimplemented from BasebandSPICommand.
Definition at line 132 of file BasebandSPIIFXProtocolVersion1.cpp.
References fWriteOffset, and BasebandSPICommand::init().
Referenced by create().
 {
         IOReturn ret = BasebandSPICommand::init( direction );
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         fWriteOffset = 0;
         return kIOReturnSuccess;
 }
BasebandSPICommandVersion1::OSDeclareDefaultStructors (BasebandSPICommandVersion1) private
void BasebandSPICommandVersion1::reset (void) virtual
Implements BasebandSPICommand.
Definition at line 146 of file BasebandSPIIFXProtocolVersion1.cpp.
References BasebandSPICommand::clearFinalized(), and fWriteOffset.
 {
         fWriteOffset = 0;
         clearFinalized();
 }
IOByteCount BasebandSPICommandVersion1::writeData (UInt8 * source, IOByteCount amount, IOByteCount dataSize) virtual
Writes some data into this command
Parameters
source The buffer representing the source of the data to write
amount The amount of data to write from the buffer
dataSize The maximum data that can be written to this command (in total, including what's already written)
Returns
the amount written
Implements BasebandSPICommand.
Definition at line 167 of file BasebandSPIIFXProtocolVersion1.cpp.
References fWriteOffset, and getPayload().
 {
         IOByteCount remaining = dataSize - fWriteOffset;
         // if we have less room than allows, then only write for how much room we have
         if ( remaining < amount )
         {
                 amount = remaining;
         }
         // copy the data over
         memcpy( getPayload() + fWriteOffset, source, amount );
         // increase the write offset
         fWriteOffset += amount;
          return amount;
 }
Friends And Related Function Documentation
friend class BasebandSPICommand friend
Definition at line 17 of file BasebandSPIIFXProtocolVersion1.cpp.
friend class BasebandSPILogger friend
Definition at line 16 of file BasebandSPIIFXProtocolVersion1.cpp.
Member Data Documentation
IOByteCount BasebandSPICommandVersion1::fWriteOffset private
Definition at line 106 of file BasebandSPIIFXProtocolVersion1.cpp.
Referenced by finalize(), init(), reset(), and writeData().
const unsigned BasebandSPICommandVersion1::kSPIHeaderDataSizeBits = 12 static
Definition at line 20 of file BasebandSPIIFXProtocolVersion1.cpp.
const unsigned BasebandSPICommandVersion1::kSPIHeaderMaxDataSize = ((1UL << kSPIHeaderDataSizeBits) - 1) static
Definition at line 21 of file BasebandSPIIFXProtocolVersion1.cpp.
Referenced by dumpFrameInternal(), and BasebandSPIIFXProtocolVersion1::handleTransferComplete().
The documentation for this class was generated from the following file:
/BasebandSPI/BasebandSPIIFXProtocolVersion1.cpp