AppleS5L8920XBasebandSPIController Class Reference
AppleS5L8920XBasebandSPIController Class Reference
#include <AppleS5L8920XBasebandSPIController.h>
Inherits AppleS5LFamilyBasebandSPIController.
Public Member Functions
virtual bool start (IOService *provider)
Public Member Functions inherited from AppleS5LFamilyBasebandSPIController
virtual bool init (OSDictionary *dict)
virtual void stop (IOService *provider)
Public Member Functions inherited from BasebandSPIController
IOReturn activate (BasebandSPIDevice *device, BasebandSPIProtocol *protocol)
void beginBlockInterrupt (void)
Disallow SPI-specific interrupts.
IOReturn cancelAll (void)
bool canStartTransfer (void) const
IOReturn configure (IODMACommand *receiveCommand, IODMACommand *transmitCommand, IOByteCount size)
IOReturn deactivate (void)
bool endBlockInterrupt (void)
IOReturn enterLowPower (void)
IOReturn exitLowPower (BasebandSPIDevice *device, BasebandSPIProtocol *protocol)
IOReturn getSnapshot (BasebandSPIControllerSnapshot **snapshot)
virtual IOWorkLoop * getWorkLoop (void) const
bool intendToInterrupt (void)
bool isEnteringLowPower (void) const
virtual IOService * probe (IOService *provider, SInt32 *score)
bool reportError (BasebandSPIReturn err, const char *details)
IOReturn startTransfer (void)
IOReturn unconfigure (void)
Protected Member Functions
virtual IOReturn configureHardware (UInt32 dmaFlags, IOByteCount size)
const char * getDebugName (void) const
virtual IOReturn loadConfiguration (void)
Parses through the configuration and extract necessary information.
virtual IOReturn preflightSetupHardware (void)
Do a preflight setup of the hardware.
virtual IOReturn startHardware (void)
Start the hardware for the transfer.
virtual IOReturn takeSnapshot (const char *comment, BasebandSPIControllerSnapshot::PinState resetDetectState, BasebandSPIControllerSnapshot **snapshot)
virtual IOReturn unconfigureHardware (void)
Power down the hardware.
virtual bool validateDeviceTypeAndChip (const char *deviceType, UInt32 chipRevision) const
Protected Member Functions inherited from AppleS5LFamilyBasebandSPIController
bool clockEnabled (void) const
void enableClock (bool enable)
const char * getDebugName (void) const
UInt32 readReg32 (UInt32 offset)
void writeReg32 (UInt32 offset, UInt32 data)
Protected Member Functions inherited from BasebandSPIController
void dumpRegisters (int level=DEBUG_SPEW)
const char * eventSourceAsString (IODMAEventSource *es) const
const char * getDebugName (void) const
IOReturn getNewSnapshot (const char *reason)
UInt32 getOverrideClockPeriod (void) const
Private Member Functions
virtual void dumpRegistersInternal (void)
OSDeclareDefaultStructors (AppleS5L8920XBasebandSPIController)
Private Attributes
UInt32 _spiClkConReg
UInt32 _spiClockPeriod
UInt32 _spiConReg
UInt32 _spiIDDReg
UInt32 _spiPreReg
UInt32 _spiWordSize
UInt32 _spiWordTime
Additional Inherited Members
Public Types inherited from BasebandSPIController
enum DMAFlags { kNone = 0, kRxDMA = 1UL << 0, kTxDMA = 1UL << 1 }
Static Protected Member Functions inherited from BasebandSPIController
static const char * stateAsString (State state)
Protected Attributes inherited from AppleS5LFamilyBasebandSPIController
UInt64 fNCLKFrequency
UInt64 fPCLKFrequency
Protected Attributes inherited from BasebandSPIController
IOCommandGate * fCommandGate
BasebandSPIConfig fConfiguration
IODMACommand * fCurrentReceiveCommand
IODMACommand * fCurrentSendCommand
BasebandSPIDevice * fDevice
BasebandSPIDiagnostics * fDiags
bool fEnteringLowPower
UInt32 fHardwareStateFlags
bool fInLowPower
volatile InterruptGuardState fInterruptGuard
UInt32 fPendingDMAs
IODMACommand * fPendingReceiveCommand
IODMACommand * fPendingSendCommand
BasebandSPIProtocol * fProtocol
AppleARMIODevice * fProvider
IODMAEventSource * fRxDMAES
BasebandSPIControllerSnapshot * fSavedSnapshot
State fState
State fStateBeforeLowPower
IOTimerEventSource * fTransferCompleteTimeout
IODMAEventSource * fTxDMAES
volatile UInt32 fVolatileHardwareStateFlags
IOWorkLoop * fWorkLoop
Detailed Description
Definition at line 83 of file AppleS5L8920XBasebandSPIController.h.
Member Function Documentation
IOReturn AppleS5L8920XBasebandSPIController::configureHardware (UInt32 dmaFlags, IOByteCount size) protected virtual
Power up the hardware
Parameters
dmaFlags Flags saying which DMAs we want
size The transfer size
Implements BasebandSPIController.
Definition at line 175 of file AppleS5L8920XBasebandSPIController.cpp.
References kS5L8920XSPCLKCON, kS5L8920XSPCLKCONEnable, kS5L8920XSPCLKCONFlushRx, kS5L8920XSPCLKCONFlushTx, kS5L8920XSPCNT, kS5L8920XSPCON, kS5L8920XSPCONFullDuplexMode, kS5L8920XSPCONRxOnlyMode, kS5L8920XSPCONSPIModeDMA, kS5L8920XSPIDD, kS5L8920XSPIHANGD, kS5L8920XSPIRTO, kS5L8920XSPPIN, kS5L8920XSPPRE, kS5L8920XSPSTA, kS5L8920XSPSTAIntAll, and kS5L8920XSPTDCNT.
 {
         enableClock(true);
         // Reset & Clear Interrupts
         _spiClkConReg = kS5L8920XSPCLKCONEnable;
         // disable the clock
         writeReg32(kS5L8920XSPCLKCON, kS5L8920XSPCLKCONFlushTx | kS5L8920XSPCLKCONFlushRx);
         writeReg32(kS5L8920XSPPIN, 0);
         // Configure controller mode
         writeReg32(kS5L8920XSPCNT, 0);
         writeReg32(kS5L8920XSPTDCNT, 0);
         writeReg32(kS5L8920XSPPRE, _spiPreReg);
         writeReg32(kS5L8920XSPIDD, _spiIDDReg);
         writeReg32(kS5L8920XSPIRTO, 0xffffffff);
         writeReg32(kS5L8920XSPIHANGD, 0);
         writeReg32(kS5L8920XSPSTA, kS5L8920XSPSTAIntAll);
         size = size >> (_spiWordSize >> 1);
         writeReg32( kS5L8920XSPCNT, size );
         UInt32 spiConReg = _spiConReg | kS5L8920XSPCONSPIModeDMA;
         if ( dmaFlags & kTxDMA )
         {
                 writeReg32( kS5L8920XSPTDCNT, size );
                 spiConReg |= kS5L8920XSPCONFullDuplexMode;
         }
         else
         {
                 spiConReg |= kS5L8920XSPCONRxOnlyMode;
         }
         // set the SPI controller register
         writeReg32(kS5L8920XSPCON, spiConReg);
         return kIOReturnSuccess;
 }
void AppleS5L8920XBasebandSPIController::dumpRegistersInternal (void) private virtual
Implements BasebandSPIController.
Definition at line 229 of file AppleS5L8920XBasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_SPEW, kS5L8920XSPCLKCON, kS5L8920XSPCNT, kS5L8920XSPCON, kS5L8920XSPIDD, kS5L8920XSPPRE, kS5L8920XSPSTA, kS5L8920XSPTDCNT, SPI_LOG, and SPI_LOG_PLAIN.
Referenced by getDebugName().
 {
         if ( !clockEnabled() )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Clock is off\n" );
                 return;
         }
         SPI_LOG_PLAIN( DEBUG_SPEW, "Register dump\n" );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\tSPCLKCON: %#8lx\n", readReg32(kS5L8920XSPCLKCON) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPCON: %#8lx\n", readReg32(kS5L8920XSPCON) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPSTA: %#8lx\n", readReg32(kS5L8920XSPSTA) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPIDD: %#8lx\n", readReg32(kS5L8920XSPIDD) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPPRE: %#8lx\n", readReg32(kS5L8920XSPPRE) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPCNT: %#8lx\n", readReg32(kS5L8920XSPCNT) );
         SPI_LOG_PLAIN( DEBUG_SPEW, "\t   SPTDCNT: %#8lx\n", readReg32(kS5L8920XSPTDCNT) );
 }
const char* AppleS5L8920XBasebandSPIController::getDebugName (void) const inline protected
Definition at line 103 of file AppleS5L8920XBasebandSPIController.h.
References dumpRegistersInternal(), and takeSnapshot().
         {
                 return "AppleS5L8920XBasebandSPIController";
         }
IOReturn AppleS5L8920XBasebandSPIController::loadConfiguration (void) protected virtual
Parses through the configuration and extract necessary information.
Reimplemented from AppleS5LFamilyBasebandSPIController.
Definition at line 102 of file AppleS5L8920XBasebandSPIController.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, DEBUG_SPEW, kS5L8920XSPCONBitOrderLSB, kS5L8920XSPCONClkActiveLow, kS5L8920XSPCONClkEnable, kS5L8920XSPCONClkMissingLast, kS5L8920XSPCONClkSelNClk, kS5L8920XSPCONDataSwap, kS5L8920XSPCONDMAReqOne, kS5L8920XSPCONMasterMode, kS5L8920XSPCONWordSizeShift, SPI_ASSERT, and SPI_LOG.
 {
         IOReturn ret;
         ret = super::loadConfiguration();
         if ( ret != kIOReturnSuccess )
         {
                 return ret;
         }
         _spiConReg = kS5L8920XSPCONClkSelNClk | kS5L8920XSPCONClkEnable | kS5L8920XSPCONMasterMode;
         if (fConfiguration.spiClockPolarity) _spiConReg |= kS5L8920XSPCONClkActiveLow;
         if (fConfiguration.spiClockPhase) _spiConReg |= kS5L8920XSPCONClkMissingLast;
         if (!fConfiguration.spiBitFirst) _spiConReg |= kS5L8920XSPCONBitOrderLSB;
         UInt32 sclkPeriod = fConfiguration.spiClockPeriod;
         {
                 UInt32 period = getOverrideClockPeriod();
                 if ( period != 0 )
                 {
                         sclkPeriod = period;
                         SPI_LOG( DEBUG_CRITICAL, "Overriding SCLK to %uns\n", period );
                 }
         }
         SPI_LOG( DEBUG_SPEW, "polarity %p, phase %p\n", fConfiguration.spiClockPolarity, fConfiguration.spiClockPhase );
         switch ( fConfiguration.spiWordSize )
         {
         case 8:
                 _spiWordSize = 0;
                 break;
         case 16:
                 _spiWordSize = 1;
                 break;
         case 32:
                 _spiWordSize = 2;
                 break;
         default:
                 SPI_ASSERT( fConfiguration.spiWordSize, ==, 8 );
         }
         _spiConReg |= _spiWordSize << kS5L8920XSPCONWordSizeShift;
         _spiWordSize = 1 << _spiWordSize;
 #if SPI_WORD32
         // Request in the unit of every one buffer. The documentation
         // states one byte however it is wrong.
         // TODO Is it worse to poll the last 4 buffers
         _spiConReg |= kS5L8920XSPCONDMAReqOne;
 #endif
         if ( !fConfiguration.spiBigEndian )
         {
                 _spiConReg |= kS5L8920XSPCONDataSwap;
         }
         // SPI Clock Value = Cell Clock / prescale
         UInt64 tmp = (((UInt64)fNCLKFrequency * (UInt64)sclkPeriod) + 1000000000ULL - 1) / 1000000000ULL;
         _spiPreReg = tmp;
         SPI_LOG( DEBUG_CRITICAL, "NCLK Frequency %u, Prescaler %u\n", (unsigned)fNCLKFrequency, _spiPreReg );
         // SPI Inter-byte Delay = PCLK period * delay cycles
          _spiIDDReg = (((UInt64)fPCLKFrequency * fConfiguration.spiWordDelay) + 1000000000ULL - 1) / 1000000000ULL;
          SPI_LOG( DEBUG_INFO, "SPCON: %p\tWord Size: %p\n", (void *)_spiConReg, (void *)_spiWordSize );
          SPI_LOG( DEBUG_INFO, "SPPRE: %p\tSPIDD: %p\n", (void *)_spiPreReg, (void *)_spiIDDReg );
          return kIOReturnSuccess;
 }
AppleS5L8920XBasebandSPIController::OSDeclareDefaultStructors (AppleS5L8920XBasebandSPIController) private
IOReturn AppleS5L8920XBasebandSPIController::preflightSetupHardware (void) protected virtual
Do a preflight setup of the hardware.
Implements BasebandSPIController.
Definition at line 91 of file AppleS5L8920XBasebandSPIController.cpp.
References DEBUG_CRITICAL, kS5L8920XSPCLKCON, kS5L8920XSPCON, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_CRITICAL );
         // configure the clock registers
         writeReg32(kS5L8920XSPCON, _spiConReg);
         writeReg32(kS5L8920XSPCLKCON, _spiClkConReg);
         return kIOReturnSuccess;
 }
bool AppleS5L8920XBasebandSPIController::start (IOService * provider) virtual
Reimplemented from AppleS5LFamilyBasebandSPIController.
Definition at line 73 of file AppleS5L8920XBasebandSPIController.cpp.
References DEBUG_INFO, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         bool ret = super::start( provider );
         if ( !ret )
         {
                 return ret;
         }
         _spiClockPeriod = 0;
         registerService();
         return true;
 }
IOReturn AppleS5L8920XBasebandSPIController::startHardware (void) protected virtual
Start the hardware for the transfer.
Implements BasebandSPIController.
Definition at line 274 of file AppleS5L8920XBasebandSPIController.cpp.
References DEBUG_CRITICAL, kS5L8920XSPCLKCON, and SPI_LOG.
 {
         if ( clockEnabled() )
         {
                 writeReg32( kS5L8920XSPCLKCON, _spiClkConReg );
         }
         else
         {
                 SPI_LOG( DEBUG_CRITICAL, "AppleS5L8920XBasebandSPIController::startHardware: clock not enabled\n" );
         }
         return kIOReturnSuccess;
 }
IOReturn AppleS5L8920XBasebandSPIController::takeSnapshot (const char * comment, BasebandSPIControllerSnapshot::PinState resetDetectState, BasebandSPIControllerSnapshot ** snapshot) protected virtual
Implements AppleS5LFamilyBasebandSPIController.
Definition at line 247 of file AppleS5L8920XBasebandSPIController.cpp.
References AppleS5L8920XBasebandSPIControllerSnapshot::AppleS5L8920XBasebandSPIControllerSnapshot(), kS5L8920XSPCLKCON, kS5L8920XSPCNT, kS5L8920XSPCON, kS5L8920XSPSTA, and kS5L8920XSPTDCNT.
Referenced by getDebugName().
 {
         bool wasClockEnabled = clockEnabled();
         // Enable the SPI clock temporarily for snapshot, if not already enabled
         if (!wasClockEnabled)
         {
                 enableClock(true);
         }
         *snapshot = new AppleS5L8920XBasebandSPIControllerSnapshot( comment,
                                                 resetDetectState,
                                                 readReg32(kS5L8920XSPCLKCON),
                                                 readReg32(kS5L8920XSPCON),
                                                 readReg32(kS5L8920XSPSTA),
                                                 readReg32(kS5L8920XSPCNT),
                                                 readReg32(kS5L8920XSPTDCNT) );
         // Disable SPI clock temporarily for snapshot, if enabled just for duration of snapshot
         if (!wasClockEnabled)
         {
                 enableClock(false);
         }
         return kIOReturnSuccess;
 }
IOReturn AppleS5L8920XBasebandSPIController::unconfigureHardware (void) protected virtual
Power down the hardware.
Implements BasebandSPIController.
Definition at line 215 of file AppleS5L8920XBasebandSPIController.cpp.
References DEBUG_SPEW, kS5L8920XSPCLKCON, kS5L8920XSPCON, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         if ( clockEnabled() )
         {
                 writeReg32(kS5L8920XSPCON, _spiConReg);
                 writeReg32(kS5L8920XSPCLKCON, 0);
                 enableClock(false);
         }
         return kIOReturnSuccess;
 }
bool AppleS5L8920XBasebandSPIController::validateDeviceTypeAndChip (const char * deviceType, UInt32 chipRevision) const protected virtual
Validates the device type and chip revision
Parameters
deviceTyp the Device type
chipRevision the chip revision
Returns
True if OK, false if not compatible
Implements BasebandSPIController.
Definition at line 288 of file AppleS5L8920XBasebandSPIController.cpp.
References DEBUG_CRITICAL, and SPI_LOG.
 {
 #if 0  // Disable Chip ID check and always return true
         (void)deviceType;
         if ( chipRevision == 0 )
         {
                 for ( unsigned i = 0; i < 3; i++ )
                 {
                         SPI_LOG( DEBUG_CRITICAL, "!!!! Chip revision %u is not supported !!!!\n", chipRevision );
                         IOSleep( 1000 );
                 }
                 return false;
         }
         else
         {
                 return true;
         }
 #else
         return true;
 #endif
 }
Member Data Documentation
UInt32 AppleS5L8920XBasebandSPIController::_spiClkConReg private
Definition at line 119 of file AppleS5L8920XBasebandSPIController.h.
UInt32 AppleS5L8920XBasebandSPIController::_spiClockPeriod private
Definition at line 116 of file AppleS5L8920XBasebandSPIController.h.
UInt32 AppleS5L8920XBasebandSPIController::_spiConReg private
Definition at line 120 of file AppleS5L8920XBasebandSPIController.h.
UInt32 AppleS5L8920XBasebandSPIController::_spiIDDReg private
Definition at line 122 of file AppleS5L8920XBasebandSPIController.h.
UInt32 AppleS5L8920XBasebandSPIController::_spiPreReg private
Definition at line 121 of file AppleS5L8920XBasebandSPIController.h.
UInt32 AppleS5L8920XBasebandSPIController::_spiWordSize private
Definition at line 115 of file AppleS5L8920XBasebandSPIController.h.
UInt32 AppleS5L8920XBasebandSPIController::_spiWordTime private
Definition at line 114 of file AppleS5L8920XBasebandSPIController.h.
The documentation for this class was generated from the following files:
/BasebandSPI/AppleS5L8920XBasebandSPIController.h
/BasebandSPI/AppleS5L8920XBasebandSPIController.cpp