BasebandSPIProtocolSnapshot Class Reference
BasebandSPIProtocolSnapshot Class Reference abstract
#include <BasebandSPIProtocol.h>
Inherited by BasebandSPIIFXProtocolSnapshot.
Public Member Functions
virtual IOByteCount copyAsString (char *dest, IOByteCount capacity) const =0
virtual ~BasebandSPIProtocolSnapshot ()
Protected Member Functions
BasebandSPIProtocolSnapshot ()
Detailed Description
Definition at line 16 of file BasebandSPIProtocol.h.
Constructor & Destructor Documentation
BasebandSPIProtocolSnapshot::BasebandSPIProtocolSnapshot () inline protected
Definition at line 19 of file BasebandSPIProtocol.h.
         {
         }
virtual BasebandSPIProtocolSnapshot::~BasebandSPIProtocolSnapshot () inline virtual
Definition at line 24 of file BasebandSPIProtocol.h.
References copyAsString().
         {
         }
Member Function Documentation
virtual IOByteCount BasebandSPIProtocolSnapshot::copyAsString (char * dest, IOByteCount capacity) const pure virtual
Implemented in BasebandSPIIFXProtocolSnapshot.
Referenced by AppleS5L8920XBasebandSPIControllerSnapshot::copyAsString(), AppleS5L8900XBasebandSPIControllerSnapshot::copyAsString(), and ~BasebandSPIProtocolSnapshot().
The documentation for this class was generated from the following file:
/BasebandSPI/BasebandSPIProtocol.h