BasebandSPIDevice Class Reference
BasebandSPIDevice Class Reference
#include <BasebandSPIDevice.h>
Inherits IOService.
Public Member Functions
IOReturn activate (void *target, BasebandSPICompletionAction action)
IOReturn allowLowPower (void)
IOReturn copyTxBuffer (void *buffer, IOByteCount length, IOByteCount *remaining, bool txNow)
IOReturn deactivate (void)
IOReturn getControllerSnapshot (BasebandSPIControllerSnapshot **snapshot)
virtual IOByteCount getFrameSize ()
bool getLogEntry (char *buffer, IOByteCount capacity)
virtual UInt32 getMaxRxBufferCount ()
void invokeCompletionCallback (void *cookie, BasebandSPIReturn status, IOByteCount offset, IOByteCount length)
bool isMuxEnteringLowPower (void)
IOReturn preEnterLowPower (void)
IOReturn registerRxBuffer (IOMemoryDescriptor *md, UInt8 *virtualAddress, void *cookie)
void reportError (BasebandSPIReturn error)
Static Public Member Functions
static BasebandSPIDevice * withRegistryEntry (IORegistryEntry *from, IOService *provider)
Static Public Attributes
static const IOByteCount kErrorStringSize = 128
Protected Attributes
IOCommandGate * fCommandGate
State fState
State fStateBeforeLowPower
Private Types
enum LowPowerFlags { kFlagLowPowerAllowed = 1U << 0, kFlagSystemInLowPower = 1U << 1, kFlagLowPowerPreEnter = 1U << 2 }
enum State { kStateInactive, kStateActive, kStateLowPower, kStateError }
Private Member Functions
IOReturn enterLowPower (void)
IOReturn exitLowPower (void)
virtual bool init (OSDictionary *dict)
IOReturn initPM (void)
OSDeclareDefaultStructors (BasebandSPIDevice)
virtual IOService * probe (IOService *provider, SInt32 *score)
virtual IOReturn setPowerState (unsigned long whichState, IOService *whatDevice)
IOReturn setPowerStateGated (unsigned long whichState, IOService *whatDevice)
virtual bool start (IOService *provider)
virtual void stop (IOService *provider)
IOReturn stopPM (void)
Static Private Member Functions
static const char * getDebugName (void)
static const char * stateAsString (State state)
Private Attributes
BasebandSPICompletionAction fCompletionAction
void * fCompletionTarget
BasebandSPIController * fController
UInt32 fLowPowerFlags
BasebandSPIProtocol * fProtocol
Detailed Description
Definition at line 102 of file BasebandSPIDevice.h.
Member Enumeration Documentation
enum BasebandSPIDevice::LowPowerFlags private
Enumerator
kFlagLowPowerAllowed
kFlagSystemInLowPower
kFlagLowPowerPreEnter
Definition at line 119 of file BasebandSPIDevice.h.
         {
                 kFlagLowPowerAllowed = 1U << 0,
                 kFlagSystemInLowPower = 1U << 1,
                 kFlagLowPowerPreEnter = 1U << 2
         }
enum BasebandSPIDevice::State private
Enumerator
kStateInactive
kStateActive
kStateLowPower
kStateError
Definition at line 111 of file BasebandSPIDevice.h.
         {
                 kStateInactive,
                 kStateActive,
                 kStateLowPower,
                 kStateError
         } State;
Member Function Documentation
IOReturn BasebandSPIDevice::activate (void * target, BasebandSPICompletionAction action)
Activates the controller
Parameters
target The target of the callback
action The callback function
Returns
The result of activation
Definition at line 210 of file BasebandSPIDevice.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, kInvalidState, SPI_ASSERT_SUCCESS, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         // while this flag is set, we can't activate. We could get in here
         // if we had previuosly failed to complete a proper low power sequence
         // and then CommCenter or someone re-opened us while the system was still
         // in the process of entering sleep
         while( fLowPowerFlags & kFlagSystemInLowPower )
         {
                 IOReturn ret;
                 ret = fCommandGate->commandSleep( &fLowPowerFlags, THREAD_UNINT );
                 if ( ret != kIOReturnSuccess )
                 {
                         SPI_LOG( DEBUG_CRITICAL, "Couldn't wait for system wake\n" );
                         return ret;
                 }
         }
         switch ( fState )
         {
         case kStateInactive:
                 {
                         IOReturn ret;
                         ret = fController->activate( this, fProtocol );
                         SPI_ASSERT_SUCCESS( ret );
                         fState = kStateActive;
                         fCompletionTarget       = target;
                         fCompletionAction       = action;
                         fProtocol->activate();
                         SPI_ASSERT_SUCCESS( ret );
                         return kIOReturnSuccess;
                 }
         default:
                 SPI_LOG(DEBUG_CRITICAL, kInvalidState, stateAsString( fState ) );
                 return kIOReturnNotPermitted;
         }
 }
IOReturn BasebandSPIDevice::allowLowPower (void)
Notify the SPI driver that it's OK to go to low ower
Returns
The result
Definition at line 309 of file BasebandSPIDevice.cpp.
 {
         fLowPowerFlags |= kFlagLowPowerAllowed;
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIDevice::copyTxBuffer (void * buffer, IOByteCount length, IOByteCount * remaining, bool txNow)
Definition at line 182 of file BasebandSPIDevice.cpp.
References DEBUG_SPEW, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         return fProtocol->copyTxBuffer( (UInt8 *)buffer, length, remaining, txNow );
 }
IOReturn BasebandSPIDevice::deactivate (void)
Deactivates the controller
Returns
The result of deactivation
Definition at line 256 of file BasebandSPIDevice.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, kInvalidState, SPI_ASSERT_SUCCESS, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         IOReturn ret;
         switch ( fState )
         {
         case kStateLowPower:
                 {
                         ret = fProtocol->exitLowPower();
                         SPI_ASSERT_SUCCESS( ret );
                 }
                 // fall through
         case kStateActive:
         case kStateError:
                 {
                         ret = fProtocol->predeactivate();
                         SPI_ASSERT_SUCCESS( ret );
                         ret = fController->deactivate();
                         SPI_ASSERT_SUCCESS( ret );
                 }
                 break;
         default:
                 SPI_LOG(DEBUG_CRITICAL, kInvalidState, stateAsString( fState ) );
                 return kIOReturnNotPermitted;
         }
         ret = fProtocol->deactivate();
         SPI_ASSERT_SUCCESS( ret );
         fState = kStateInactive;
         fLowPowerFlags &= ~ kFlagLowPowerAllowed;
         //BasebandSPILogger::report();
         //BasebandSPILogger::clear();
         return kIOReturnSuccess;
 }
IOReturn BasebandSPIDevice::enterLowPower (void) private
Prepares driver for low power
Returns
The result of the operation
Definition at line 316 of file BasebandSPIDevice.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, kBasebandSPIReturnPMError, kInvalidState, SPI_ASSERT_SUCCESS, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         fLowPowerFlags &= ~kFlagLowPowerPreEnter;
         switch ( fState )
         {
         case kStateActive:
                 {
                         if ( !( fLowPowerFlags & kFlagLowPowerAllowed ) )
{
                                 fController->reportError( kBasebandSPIReturnPMError, "child driver did not allow low power" );
                         }
                         else
{
                                 fLowPowerFlags &= ~ kFlagLowPowerAllowed;
                         }
                 }
                 // fall through
         case kStateInactive:
                 {
                         IOReturn ret = fController->enterLowPower();
                         SPI_ASSERT_SUCCESS( ret );
                         ret = fProtocol->enterLowPower();
                         SPI_ASSERT_SUCCESS( ret );
                         fStateBeforeLowPower    = fState;
                         fState                                  = kStateLowPower;
                         fLowPowerFlags                  |= kFlagSystemInLowPower;
                 }
                 SPI_LOG( DEBUG_INFO, "In Low Power\n" );
                 return kIOReturnSuccess;
         default:
                 SPI_LOG(DEBUG_CRITICAL, kInvalidState, stateAsString( fState ) );
                 return kIOReturnNotPermitted;
         }
 }
IOReturn BasebandSPIDevice::exitLowPower (void) private
Brings driver out of low power
Returns
The result of the operation
Definition at line 358 of file BasebandSPIDevice.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, kInvalidState, SPI_ASSERT_SUCCESS, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         // always clear the flags
         fLowPowerFlags  &= ~ kFlagSystemInLowPower;
         fCommandGate->commandWakeup( &fLowPowerFlags );
         switch ( fState )
         {
         case kStateLowPower:
                 {
                         IOReturn ret = fController->exitLowPower( this, fProtocol );
                         SPI_ASSERT_SUCCESS( ret );
                         ret = fProtocol->exitLowPower();
                         SPI_ASSERT_SUCCESS( ret );
                         fState                  = fStateBeforeLowPower;
                         SPI_LOG( DEBUG_INFO, "Exited Low Power\n" );
                 }
                 return kIOReturnSuccess;
         default:
                 SPI_LOG( DEBUG_CRITICAL, kInvalidState, stateAsString( fState ) );
                 return kIOReturnNotPermitted;
         }
 }
IOReturn BasebandSPIDevice::getControllerSnapshot (BasebandSPIControllerSnapshot ** snapshot)
Definition at line 188 of file BasebandSPIDevice.cpp.
 {
         return fController->getSnapshot( snapshot );
 }
static const char* BasebandSPIDevice::getDebugName (void) inline static private
Definition at line 128 of file BasebandSPIDevice.h.
         {
                 return "BasebandSPIDevice";
         }
IOByteCount BasebandSPIDevice::getFrameSize () virtual
Definition at line 171 of file BasebandSPIDevice.cpp.
 {
         return fProtocol->getFrameSize();
 }
bool BasebandSPIDevice::getLogEntry (char * buffer, IOByteCount capacity)
Debugging and logging
Parameters
buffer The buffer to copy into
capacity The capacity of the buffer
Returns
true if something was copied, false otherwise This will be a string representation of the entry
Definition at line 472 of file BasebandSPIDevice.cpp.
References BasebandSPILogger::popLogEntryAsString().
 {
         return BasebandSPILogger::popLogEntryAsString( buffer, capacity );
 }
UInt32 BasebandSPIDevice::getMaxRxBufferCount () virtual
Definition at line 193 of file BasebandSPIDevice.cpp.
 {
         return fProtocol->getMaxRxBufferCount();
 }
bool BasebandSPIDevice::init (OSDictionary * dict) private virtual
Definition at line 72 of file BasebandSPIDevice.cpp.
References DEBUG_SPEW, SPI_ASSERT, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         bool ret = super::init( dict );
         SPI_ASSERT( ret, ==, true );
         fState                  = kStateInactive;
         fController             = NULL;
         fProtocol               = NULL;
         fCompletionTarget               = NULL;
         fCompletionAction               = NULL;
         fLowPowerFlags = 0;
         return true;
 }
IOReturn BasebandSPIDevice::initPM (void) private
Definition at line 389 of file BasebandSPIDevice.cpp.
References DEBUG_CRITICAL, DEBUG_INFO, kNumPowerStates, SPI_LOG, SPI_TRACE, and sPowerStates.
 {
         SPI_TRACE( DEBUG_INFO );
         static const unsigned kIOPMPowerOff = 0;
         bzero( &sPowerStates, sizeof( sPowerStates ) );
         sPowerStates[0].version                                 = kIOPMPowerStateVersion1;
         sPowerStates[0].capabilityFlags                 = kIOPMPowerOff;
         sPowerStates[0].outputPowerCharacter    = kIOPMPowerOff;
         sPowerStates[0].inputPowerRequirement   = kIOPMPowerOff;
         sPowerStates[1].version                                 = kIOPMPowerStateVersion1;
         sPowerStates[1].capabilityFlags                 = kIOPMPowerOn;
         sPowerStates[1].outputPowerCharacter    = kIOPMPowerOn;
         sPowerStates[1].inputPowerRequirement   = kIOPMPowerOn;
         PMinit();
         fController->joinPMtree( this );
         IOReturn ret = registerPowerDriver( this, sPowerStates, kNumPowerStates );
         if ( ret != kIOReturnSuccess )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't register as power driver, ret = %p\n",
                         (void *)ret );
         }
         return ret;
 }
void BasebandSPIDevice::invokeCompletionCallback (void * cookie, BasebandSPIReturn status, IOByteCount offset, IOByteCount length) inline
Definition at line 210 of file BasebandSPIDevice.h.
Referenced by BasebandSPIProtocol::exitLowPower(), and BasebandSPIProtocol::unregisterAllRxBuffers().
         {
                 if ( fCompletionAction )
                 {
                         fCompletionAction( fCompletionTarget, cookie, status, offset, length );
                 }
         }
bool BasebandSPIDevice::isMuxEnteringLowPower (void) inline
Indicate if Mux is in the process of entering low power
Returns
The result
Definition at line 229 of file BasebandSPIDevice.h.
         {
                 return ( (fLowPowerFlags & kFlagLowPowerPreEnter) != 0 );
         }
BasebandSPIDevice::OSDeclareDefaultStructors (BasebandSPIDevice) private
IOReturn BasebandSPIDevice::preEnterLowPower (void)
Notify the SPI driver that Mux is attempting to enter low power
Returns
The result
Definition at line 302 of file BasebandSPIDevice.cpp.
 {
         fLowPowerFlags |= kFlagLowPowerPreEnter;
         return kIOReturnSuccess;
 }
IOService * BasebandSPIDevice::probe (IOService * provider, SInt32 * score) private virtual
Definition at line 63 of file BasebandSPIDevice.cpp.
References DEBUG_SPEW, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         *score = 5000;
         return super::probe( provider, score );
 }
IOReturn BasebandSPIDevice::registerRxBuffer (IOMemoryDescriptor * md, UInt8 * virtualAddress, void * cookie)
Definition at line 176 of file BasebandSPIDevice.cpp.
References DEBUG_SPEW, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         return fProtocol->registerRxBuffer( md, virtualAddress, cookie );
 }
void BasebandSPIDevice::reportError (BasebandSPIReturn error) inline
Definition at line 219 of file BasebandSPIDevice.h.
Referenced by BasebandSPIController::reportError().
         {
                 invokeCompletionCallback( NULL, error, 0, 0 );
         }
IOReturn BasebandSPIDevice::setPowerState (unsigned long whichState, IOService * whatDevice) private virtual
Definition at line 433 of file BasebandSPIDevice.cpp.
References setPowerStateGated().
 {
         IOCommandGate::Action action = OSMemberFunctionCast( IOCommandGate::Action, this,
                                                                         &BasebandSPIDevice::setPowerStateGated );
         return fCommandGate->runAction( action, (void *)whichState, whatDevice );
 }
IOReturn BasebandSPIDevice::setPowerStateGated (unsigned long whichState, IOService * whatDevice) private
Definition at line 441 of file BasebandSPIDevice.cpp.
References DEBUG_INFO, SPI_ASSERT_SUCCESS, SPI_LOG, and SPI_TRACE.
Referenced by setPowerState().
 {
         typedef enum
         {
                 kSelectorOff,
                 kSelectorOn
         }
         Selector;
         SPI_TRACE( DEBUG_INFO );
         IOReturn ret;
         switch ( whichState )
         {
         case kSelectorOff:
                 SPI_LOG( DEBUG_INFO, "sleeping\n" );
                 ret = enterLowPower();
                 SPI_ASSERT_SUCCESS( ret );
                 break;
         case kSelectorOn:
         default:
                 SPI_LOG( DEBUG_INFO, "waking\n" );
                 exitLowPower();
                 break;
         }
         return kIOReturnSuccess;
 }
bool BasebandSPIDevice::start (IOService * provider) private virtual
Definition at line 93 of file BasebandSPIDevice.cpp.
References BasebandSPIProtocol::create(), DEBUG_CRITICAL, DEBUG_SPEW, SPI_ASSERT, SPI_LOG, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         //PE_enter_debugger( "blah" );
         bool ret = super::start( provider );
         SPI_ASSERT( ret, ==, true );
         fController = OSDynamicCast(BasebandSPIController, provider);
         if (!fController){
                 SPI_LOG( DEBUG_CRITICAL, "Controller seems invalid\n" );
                 return false;
         }
                 fCommandGate = IOCommandGate::commandGate( this );
         if ( fCommandGate == NULL )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Failed to create command gate\n" );
                 return false;
         }
         SPI_ASSERT( getWorkLoop(), !=, NULL );
         IOReturn result;
         result = getWorkLoop()->addEventSource( fCommandGate );
         if ( result != kIOReturnSuccess )
         {
                 fCommandGate->release();
                 fCommandGate = NULL;
                 SPI_LOG( DEBUG_CRITICAL, "Failed to add command gate to workloop, ret = %p\n", result );
                 return false;
         }
         fProtocol = BasebandSPIProtocol::create( fController, this );
         if ( !fProtocol )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Creating protocol failed\n" );
                 return false;
         }
         result = initPM();
         if ( result != kIOReturnSuccess )
         {
                 SPI_LOG( DEBUG_CRITICAL, "Couldn't initialize PM\n" );
         }
         registerService();
         return true;
 }
const char * BasebandSPIDevice::stateAsString (State state) static private
Utility method for string representation of the state
Parameters
state The state
Returns
the string representation of state
Definition at line 198 of file BasebandSPIDevice.cpp.
 {
         switch ( state )
         {
                 case kStateInactive:    return "inactive";
                 case kStateActive:              return "active";
                 case kStateError:               return "error";
                 case kStateLowPower:    return "lowpower";
                 default:                                return "???";
         }
 }
void BasebandSPIDevice::stop (IOService * provider) private virtual
Definition at line 147 of file BasebandSPIDevice.cpp.
References DEBUG_SPEW, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_SPEW );
         (void)provider;
         if ( fProtocol )
         {
                 fProtocol->release();
                 fProtocol = NULL;
         }
         stopPM();
         if ( fCommandGate  )
         {
                 getWorkLoop()->removeEventSource( fCommandGate );
                 fCommandGate->release();
                 fCommandGate = NULL;
         }
         super::stop( provider );
 }
IOReturn BasebandSPIDevice::stopPM (void) private
Definition at line 423 of file BasebandSPIDevice.cpp.
References DEBUG_INFO, and SPI_TRACE.
 {
         SPI_TRACE( DEBUG_INFO );
         PMstop();
         return kIOReturnSuccess;
 }
static BasebandSPIDevice* BasebandSPIDevice::withRegistryEntry (IORegistryEntry * from, IOService * provider) static
Member Data Documentation
IOCommandGate* BasebandSPIDevice::fCommandGate protected
Definition at line 248 of file BasebandSPIDevice.h.
BasebandSPICompletionAction BasebandSPIDevice::fCompletionAction private
Definition at line 255 of file BasebandSPIDevice.h.
void* BasebandSPIDevice::fCompletionTarget private
Definition at line 254 of file BasebandSPIDevice.h.
BasebandSPIController* BasebandSPIDevice::fController private
Definition at line 251 of file BasebandSPIDevice.h.
UInt32 BasebandSPIDevice::fLowPowerFlags private
Definition at line 257 of file BasebandSPIDevice.h.
BasebandSPIProtocol* BasebandSPIDevice::fProtocol private
Definition at line 252 of file BasebandSPIDevice.h.
State BasebandSPIDevice::fState protected
Definition at line 245 of file BasebandSPIDevice.h.
State BasebandSPIDevice::fStateBeforeLowPower protected
Definition at line 246 of file BasebandSPIDevice.h.
const IOByteCount BasebandSPIDevice::kErrorStringSize = 128 static
Definition at line 107 of file BasebandSPIDevice.h.
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPIDevice.h
/BasebandSPI/BasebandSPIDevice.cpp