AppleS5L8920XBasebandSPIControllerSnapshot Class Reference
AppleS5L8920XBasebandSPIControllerSnapshot Class Reference
Inherits BasebandSPIControllerSnapshot.
Public Member Functions
AppleS5L8920XBasebandSPIControllerSnapshot (const char *comment, PinState resetDetectState, UInt32 spclkcon, UInt32 spcon, UInt32 spsta, UInt32 spcnt, UInt32 sptdcnt)
virtual IOByteCount copyAsString (char *dest, IOByteCount capacity) const
virtual ~AppleS5L8920XBasebandSPIControllerSnapshot ()
Public Member Functions inherited from BasebandSPIControllerSnapshot
void injectProtocolSnapshot (BasebandSPIProtocolSnapshot *snapshot)
bool resetDetectIsHigh (void) const
virtual ~BasebandSPIControllerSnapshot ()
Private Attributes
UInt32 fSPCLKCON
UInt32 fSPCNT
UInt32 fSPCON
UInt32 fSPSTA
UInt32 fSPTDCNT
Additional Inherited Members
Public Types inherited from BasebandSPIControllerSnapshot
enum PinState { kLow = 0, kHigh = 1, kDunno = 2 }
Static Public Member Functions inherited from BasebandSPIControllerSnapshot
static const char * pinStateAsString (PinState state)
Protected Member Functions inherited from BasebandSPIControllerSnapshot
BasebandSPIControllerSnapshot (const char *comment, PinState resetDetectState)
Protected Attributes inherited from BasebandSPIControllerSnapshot
char fComment [kMaxCommentSize]
BasebandSPIProtocolSnapshot * fProtocolSnapshot
PinState fResetDetectState
Detailed Description
Definition at line 23 of file AppleS5L8920XBasebandSPIController.cpp.
Constructor & Destructor Documentation
AppleS5L8920XBasebandSPIControllerSnapshot::AppleS5L8920XBasebandSPIControllerSnapshot (const char * comment, PinState resetDetectState, UInt32 spclkcon, UInt32 spcon, UInt32 spsta, UInt32 spcnt, UInt32 sptdcnt) inline
Definition at line 33 of file AppleS5L8920XBasebandSPIController.cpp.
Referenced by AppleS5L8920XBasebandSPIController::takeSnapshot().
                 : BasebandSPIControllerSnapshot( comment, resetDetectState ),
                 fSPCLKCON( spclkcon ),
                 fSPCON( spcon ),
                 fSPSTA( spsta ),
                 fSPCNT( spcnt ),
                 fSPTDCNT( sptdcnt )
         {
         }
virtual AppleS5L8920XBasebandSPIControllerSnapshot::~AppleS5L8920XBasebandSPIControllerSnapshot () inline virtual
Definition at line 49 of file AppleS5L8920XBasebandSPIController.cpp.
         {
         }
Member Function Documentation
virtual IOByteCount AppleS5L8920XBasebandSPIControllerSnapshot::copyAsString (char * dest, IOByteCount capacity) const inline virtual
Implements BasebandSPIControllerSnapshot.
Definition at line 53 of file AppleS5L8920XBasebandSPIController.cpp.
References BasebandSPIProtocolSnapshot::copyAsString(), BasebandSPIControllerSnapshot::fComment, BasebandSPIControllerSnapshot::fProtocolSnapshot, BasebandSPIControllerSnapshot::fResetDetectState, BasebandSPIControllerSnapshot::pinStateAsString(), and SPIsnprintf().
         {
                 IOByteCount written = 0;
                 written += SPIsnprintf( dest + written, capacity - written, "%s: ", fComment );
                 written += SPIsnprintf( dest + written, capacity - written, "RESET_DET: %s, ",
                                                 pinStateAsString( fResetDetectState ) );
                 written += SPIsnprintf( dest + written, capacity - written, "SPCLKCON %p, SPCON %p, SPSTA %p, SPCNT %p, SPTDCNT %p",
                                                 fSPCLKCON, fSPCON, fSPSTA, fSPCNT, fSPTDCNT );
                 if ( fProtocolSnapshot )
                 {
                         written += fProtocolSnapshot->copyAsString( dest + written, capacity - written );
                 }
                 return written;
         }
Member Data Documentation
UInt32 AppleS5L8920XBasebandSPIControllerSnapshot::fSPCLKCON private
Definition at line 26 of file AppleS5L8920XBasebandSPIController.cpp.
UInt32 AppleS5L8920XBasebandSPIControllerSnapshot::fSPCNT private
Definition at line 29 of file AppleS5L8920XBasebandSPIController.cpp.
UInt32 AppleS5L8920XBasebandSPIControllerSnapshot::fSPCON private
Definition at line 27 of file AppleS5L8920XBasebandSPIController.cpp.
UInt32 AppleS5L8920XBasebandSPIControllerSnapshot::fSPSTA private
Definition at line 28 of file AppleS5L8920XBasebandSPIController.cpp.
UInt32 AppleS5L8920XBasebandSPIControllerSnapshot::fSPTDCNT private
Definition at line 30 of file AppleS5L8920XBasebandSPIController.cpp.
The documentation for this class was generated from the following file:
/BasebandSPI/AppleS5L8920XBasebandSPIController.cpp