BasebandSPIControllerSnapshot Class Reference
BasebandSPIControllerSnapshot Class Reference abstract
#include <BasebandSPIDevice.h>
Inherited by AppleS5L8900XBasebandSPIControllerSnapshot, and AppleS5L8920XBasebandSPIControllerSnapshot.
Public Types
enum PinState { kLow = 0, kHigh = 1, kDunno = 2 }
Public Member Functions
virtual IOByteCount copyAsString (char *dest, IOByteCount capacity) const =0
void injectProtocolSnapshot (BasebandSPIProtocolSnapshot *snapshot)
bool resetDetectIsHigh (void) const
virtual ~BasebandSPIControllerSnapshot ()
Static Public Member Functions
static const char * pinStateAsString (PinState state)
Protected Member Functions
BasebandSPIControllerSnapshot (const char *comment, PinState resetDetectState)
Protected Attributes
char fComment [kMaxCommentSize]
BasebandSPIProtocolSnapshot * fProtocolSnapshot
PinState fResetDetectState
Private Member Functions
BasebandSPIControllerSnapshot (BasebandSPIControllerSnapshot *other)
Static Private Attributes
static const IOByteCount kMaxCommentSize = 64
Detailed Description
Definition at line 57 of file BasebandSPIDevice.h.
Member Enumeration Documentation
enum BasebandSPIControllerSnapshot::PinState
Enumerator
kLow
kHigh
kDunno
Definition at line 63 of file BasebandSPIDevice.h.
         {
                 kLow = 0,
                 kHigh = 1,
                 kDunno = 2
         }
Constructor & Destructor Documentation
BasebandSPIControllerSnapshot::BasebandSPIControllerSnapshot (BasebandSPIControllerSnapshot * other) inline private
Definition at line 72 of file BasebandSPIDevice.h.
References copyAsString(), and ~BasebandSPIControllerSnapshot().
                 : fProtocolSnapshot( NULL )
         {};
BasebandSPIControllerSnapshot::BasebandSPIControllerSnapshot (const char * comment, PinState resetDetectState) protected
Definition at line 43 of file BasebandSPIDevice.cpp.
References fComment, and kMaxCommentSize.
         : fResetDetectState( resetDetectState )
 {
         strncpy( fComment, comment, kMaxCommentSize );
 }
BasebandSPIControllerSnapshot::~BasebandSPIControllerSnapshot () virtual
Definition at line 479 of file BasebandSPIDevice.cpp.
References fProtocolSnapshot.
Referenced by BasebandSPIControllerSnapshot().
 {
         if ( fProtocolSnapshot )
         {
                 delete fProtocolSnapshot;
                 fProtocolSnapshot = NULL;
         }
 }
Member Function Documentation
virtual IOByteCount BasebandSPIControllerSnapshot::copyAsString (char * dest, IOByteCount capacity) const pure virtual
Implemented in AppleS5L8900XBasebandSPIControllerSnapshot, and AppleS5L8920XBasebandSPIControllerSnapshot.
Referenced by BasebandSPIControllerSnapshot(), and BasebandSPIController::reportError().
void BasebandSPIControllerSnapshot::injectProtocolSnapshot (BasebandSPIProtocolSnapshot * snapshot) inline
Definition at line 84 of file BasebandSPIDevice.h.
References fProtocolSnapshot.
Referenced by BasebandSPIController::getNewSnapshot().
         {
                 fProtocolSnapshot = snapshot;
         }
const char * BasebandSPIControllerSnapshot::pinStateAsString (PinState state) static
Definition at line 49 of file BasebandSPIDevice.cpp.
References kDunno, kHigh, and kLow.
Referenced by AppleS5L8920XBasebandSPIControllerSnapshot::copyAsString(), AppleS5L8900XBasebandSPIControllerSnapshot::copyAsString(), BasebandSPIIFXProtocolSnapshot::copyAsString(), and resetDetectIsHigh().
 {
         switch ( state )
         {
         case kHigh:
                 return "High";
         case kLow:
                 return "Low";
         case kDunno:
         default:
                 return "Dunno";
         }
 }
bool BasebandSPIControllerSnapshot::resetDetectIsHigh (void) const inline
Definition at line 89 of file BasebandSPIDevice.h.
References fResetDetectState, kHigh, and pinStateAsString().
         {
                 return fResetDetectState == kHigh;
         }
Member Data Documentation
char BasebandSPIControllerSnapshot::fComment[kMaxCommentSize] protected
Definition at line 97 of file BasebandSPIDevice.h.
Referenced by BasebandSPIControllerSnapshot(), AppleS5L8920XBasebandSPIControllerSnapshot::copyAsString(), and AppleS5L8900XBasebandSPIControllerSnapshot::copyAsString().
BasebandSPIProtocolSnapshot* BasebandSPIControllerSnapshot::fProtocolSnapshot protected
Definition at line 99 of file BasebandSPIDevice.h.
Referenced by AppleS5L8920XBasebandSPIControllerSnapshot::copyAsString(), AppleS5L8900XBasebandSPIControllerSnapshot::copyAsString(), injectProtocolSnapshot(), and ~BasebandSPIControllerSnapshot().
PinState BasebandSPIControllerSnapshot::fResetDetectState protected
Definition at line 98 of file BasebandSPIDevice.h.
Referenced by AppleS5L8920XBasebandSPIControllerSnapshot::copyAsString(), AppleS5L8900XBasebandSPIControllerSnapshot::copyAsString(), and resetDetectIsHigh().
const IOByteCount BasebandSPIControllerSnapshot::kMaxCommentSize = 64 static private
Definition at line 60 of file BasebandSPIDevice.h.
Referenced by BasebandSPIControllerSnapshot().
The documentation for this class was generated from the following files:
/BasebandSPI/BasebandSPIDevice.h
/BasebandSPI/BasebandSPIDevice.cpp